Uso de los datos para obtener las recomendaciones para el usuario
JoseJordanF/Claqueta pull request #103
Opened 2023-11-08 19:10 UTC by JoseJordanF

Este PR se centra en resolver el problema de las recomendaciones personalizadas para el usuario, a causa de su consumo, siendo este considerado como las películas en las que el usuario ha reseñado.

Qué datos vamos a usar para ello (closes #62)
Como debemos usar los datos para las recomendaciones (closes #63)
También se resuelven problemas derivados de estos problemas (closes #99) 
También cuando se va a actualizar dicha lista (closes #101)
Liminar el propio consumo del usuario (closes #102)
Problema para asegurar que cada user cree solo una review para cada película (closes #100)

2023-12-04 12:41 UTC, JJ approved these changes
Bien completado, con tests y demás. Si tienes tiempo y ganas, aplica una serie de buenas prácticas para que el código sea más limpio

2023-12-04 12:41 UTC, JJ commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        if (oldReview == null) {
Trata de reducir la complejidad de estos bucles; tienes tres ifs uno dentro de otro, eso va a ser muy complicado de testear. Considera si esos campos pueden realmente estar nulos, y trata de evitarlo donde se creen esos campos.

2023-12-04 12:41 UTC, JJ commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        var directorsUser: Set<String> = filtro.flatMap { films[it.filmId]?.movieDirectors.orEmpty() }.toSet()
Si los estás pasando a conjunto, ¿no será mejor almacenarlos así?

2023-12-04 12:41 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val atomicInteger = AtomicInteger(0)
¿Necesitas una clase y no una función? Mira bien el nombre de la clase entonces.

2023-12-04 12:43 UTC, JJ requested changes
Conviene que resuelvas #107 antes de fusionar este; si no pasas los tests automáticamente, no puedes afirmar que funciona.

2023-12-04 18:52 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        if (oldReview == null) {
Realmente se puede reducir solo al if que comprueba si el usuario ya escribió la reseña, los otros en un futuro no se van a necesitar porque va a ser imposible que pinchar en una película que no exista o ser un usuario que no exista

2023-12-04 18:55 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        var plataformsUser: Set<String> = filtro.flatMap { films[it.filmId]?.consPlataforms.orEmpty() }.toSet()
He puesto plataforms en vez de platforms,  lo cambiaré donde aparezaca, si es a eso a lo que te refieres.

2023-12-05 02:57 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        var directorsUser: Set<String> = filtro.flatMap { films[it.filmId]?.movieDirectors.orEmpty() }.toSet()
Te refieres a que las listas de directores sean directamente set en vez de listas??

2023-12-06 02:15 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
O sea dejo la calase como esta, pero saco las variables fuera?? O creo un objeto en vez de una clase y garantizo que es singleton?

2023-12-11 08:32 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
Eso es decisión tuya; abre un issue y discute en él las diferentes opciones que hay.

2023-12-13 09:07 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
Con constantes a novel de módulo te refieres a constantes globales imagino

2023-12-13 09:08 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
Hay constantes globales, y las hay que sólo tienen como ámbito el fichero donde están. Supongo que en Kotlin será igual, ¿no?

2023-12-16 11:15 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
Si claro, todas las que defino en el fichero snowflake solo es posible usarlas en ese fichero. Pero no entiendo qué me quieres decir. ¿Que es preferible usar una función en lugar de crear una clase para generar los IDs? https://github.com/JoseJordanF/Claqueta/pull/103#discussion_r1413814554. Yo creo que es mejor así, ya que es más flexible. Pero no entiendo tu punto y quizá por eso no lo veo. O quizás yo estoy mezclando los dos comentarios y me estoy haciendo un lío.

2023-12-16 11:17 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val atomicInteger = AtomicInteger(0)
Que sea generica que no sea SnowFlakeForFilm, sino SnowFlake no?

2023-12-16 11:42 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
Sí, esencialmente si. Hay que usar la estructura funcional que integre la funcionalidad de la forma más simple posible.

2023-12-16 11:43 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val atomicInteger = AtomicInteger(0)
Bueno, es una posibilidad; el nombre debe reflejar la función en arquitectura limpia para que sea auto-documentado.

2023-12-17 21:50 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
Perfecto, pues lo generalizaré para dejarlo como una clase. Lo discutiré en el issue

2023-12-18 09:41 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        var directorsUser: Set<String> = filtro.flatMap { films[it.filmId]?.movieDirectors.orEmpty() }.toSet()
He comprobado y aunque use set, voy a tener que hacer exactamente lo mismo, ya que flatMap te devuelve una lista, Y aunque la lista de reseñas sea un set en lugar de lista al llamar a flatMap también devolvería una lista.

2023-12-22 10:33 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +        var idFilm1 = getManager.newFilm(
27f2284ad2418e43e02e8eece17976d63c728cd8

2023-12-22 10:33 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +        var id2 = getManager.newFilm(
27f2284ad2418e43e02e8eece17976d63c728cd8

2023-12-22 10:33 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +        val currentTs = System.currentTimeMillis() - epoch
27f2284ad2418e43e02e8eece17976d63c728cd8

2023-12-22 10:33 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val atomicInteger = AtomicInteger(0)
27f2284ad2418e43e02e8eece17976d63c728cd8

2023-12-22 10:33 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        var plataformsUser: Set<String> = filtro.flatMap { films[it.filmId]?.consPlataforms.orEmpty() }.toSet()
27f2284ad2418e43e02e8eece17976d63c728cd8

2023-12-22 10:34 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +        if (oldReview == null) {
27f2284ad2418e43e02e8eece17976d63c728cd8

2023-12-22 10:49 UTC, JJ requested changes
Aparte de lo comentado, estoy viendo aquí código de otro PR, quizás sería conveniente que hicieras este PR de la otra rama, no de master. El resto son temas de detalle que, como es tu primer uso de GHA, me gustaría que consideraras. En todo caso, como documentación para estos tests puedes mirar el objetivo 6 de IV, y también el objetivo 4

2023-12-22 10:49 UTC, JJ commented on .github/workflows/junit_test.yml
> +      - name: Set up JDK 11
¿Por qué usas precisamente esta versión?
Las mejores prácticas en versiones suelen ser probar la versión LTS más antigua, la versión actual, y la versión en desarrollo. Para ello hay que genera un workflow con lo que se llama "matrix".  Quizás un poco avanzado para esta fase de desarrollo, pero sí deberías asegurarte de testear al menos la versión estable actual.

2023-12-22 10:49 UTC, JJ commented on .github/workflows/junit_test.yml
> +        uses: actions/setup-java@v2
Tienes que tener un poco de cuidado con el código de GitHub actions que te genera CoPilot, que no suele usar casi nunca la última versión disponible. Busca siempre en GitHub a ver cuál es la última versión y úsala.

2023-12-22 10:49 UTC, JJ commented on .github/workflows/junit_test.yml
> +          chmod +x gradlew  # Asegúrate de que el archivo gradlew sea ejecutable
¿Y por qué no te aseguras tú en el repo?

2023-12-22 10:49 UTC, JJ commented on claqueta_tfg/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
En versiones siempre tienes que asegurarte que se trata de la versión correcta.

2023-12-23 12:11 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +      - name: Set up JDK 11
¿Pero la versión en desarrollo no la puedo utilizar hasta que no salga no?, osea he estado biendo que la mas antigua es la 8, la actual es la 21 y la que está en desarrollo es la 25 que sale en 2025. O sea que no puedo usar la que esta en desarrollo no?. Usare la 8, la 17 y la 21

2023-12-23 12:25 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +          chmod +x gradlew  # Asegúrate de que el archivo gradlew sea ejecutable
No sé cómo hacerlo desde el repo. Te refieres a darle permisos manualmente?

2023-12-25 08:38 UTC, JJ commented on .github/workflows/junit_test.yml
> +      - name: Set up JDK 11
En ese caso lo conveniente es que uses la actual. Una versión random que además no es LTS tampoco parece que sea conveniente. Y no es cuestión de que la uses, sino de que la testees. ¿La 8 está en LTS?

2023-12-25 08:39 UTC, JJ commented on .github/workflows/junit_test.yml
> +          chmod +x gradlew  # Asegúrate de que el archivo gradlew sea ejecutable
Simplemente lo haces desde la línea de órdenes. El repo guarda también estos permisos. No sé si usarás Windows, pero si lo haces, también habrá forma de hacerlo, imagino.

2023-12-26 13:06 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +      - name: Set up JDK 11
Como tal en el comando me da todas estas posibilidades, la única que especifica LTS es la 21:
21.0.1+12.0.LTS, 21.0.0+35.0.LTS, 20.0.2+9, 20.0.1+9, 20.0.0+36, 19.0.2+7, 19.0.1+10, 19.0.0+36, 18.0.2+101, 18.0.2+9, 18.0.1+10, 18.0.0+36, 17.0.9+9, 17.0.8+101, 17.0.8+7, 17.0.7+7, 17.0.6+10, 17.0.5+8, 17.0.4+101, 17.0.4+8, 17.0.3+7, 17.0.2+8, 17.0.1+12, 17.0.0+35, 16.0.2+7, 16.0.1+9, 16.0.0+36, 15.0.2+7, 15.0.1+9, 15.0.0+36, 14.0.2+12, 14.0.1+7.1, 14.0.0+36.1, 13.0.2+8.1, 13.0.1+9.1, 13.0.0+33.1, 12.0.2+10.1, 12.0.1+12, 12.0.0+33, 11.0.21+9, 11.0.20+101, 11.0.20+8, 11.0.19+7, 11.0.18+10, 11.0.17+8, 11.0.16+101, 11.0.16+8, 11.0.15+10, 11.0.14+101, 11.0.14+9, 11.0.13+8, 11.0.12+7, 11.0.11+9, 11.0.10+9, 11.0.9+101, 11.0.9+11.1, 11.0.9+11, 11.0.8+10, 11.0.7+10.1, 11.0.6+10.1, 11.0.5+10.1, 11.0.4+11.1, 11.0.3+7, 11.0.2+9, 11.0.2+7, 11.0.1+13, 11.0.0+28, 10.0.2+13.1, 9.0.4+11, 9.0.0+181, 8.0.392+8, 8.0.382+5, 8.0.372+7, 8.0.362+9, 8.0.352+8, 8.0.345+1, 8.0.342+7, 8.0.332+9, 8.0.322+6, 8.0.312+7, 8.0.302+8, 8.0.292+10, 8.0.282+8, 8.0.275+1, 8.0.272+10, 8.0.265+1, 8.0.262+10, 8.0.252+9.1, 8.0.242+8.1, 8.0.232+9.1, 8.0.222+10.1, 8.0.212+4, 8.0.212+3, 8.0.202+8, 8.0.192+12, 8.0.181+13

2023-12-28 19:04 UTC, JJ commented on .github/workflows/junit_test.yml
> +      - name: Set up JDK 11
Es mejor que lo mires en la página de versiones que publique la JVM. Ahí especifica cuanto tiempo tiene soporte cada una.

2024-01-04 11:31 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +          chmod +x gradlew  # Asegúrate de que el archivo gradlew sea ejecutable
Me esta dando muchos problemas en windows, por otra parte he estado leyendo que es mas seguro hacerlo en el flujo, en vez de darle permiso a todos los usuarios

2024-01-04 11:34 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +      - name: Set up JDK 11
Listo he buscado una distribucion que tenga LTS la 8, 17 y 21

2024-01-07 09:27 UTC, JoseJordanF commented on claqueta_tfg/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
(713dd9ccc153fc7e09dae1c7101bb4827bd2e995)

2024-01-07 09:27 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +        uses: actions/setup-java@v2
(713dd9ccc153fc7e09dae1c7101bb4827bd2e995)

2024-01-07 09:27 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +      - name: Set up JDK 11
(713dd9ccc153fc7e09dae1c7101bb4827bd2e995)

2024-01-07 11:59 UTC, JJ commented on .github/workflows/junit_test.yml
> +          chmod +x gradlew  # Asegúrate de que el archivo gradlew sea ejecutable
Pero ¿no lo usas en local?

2024-01-07 12:02 UTC, JJ approved these changes
Salvo un par de detalles, parece correcto.

2024-01-07 12:02 UTC, JJ commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +import generatorId.generateUniqueId
¿Seguro que las buenas prácticas te dicen que no uses ningún tipo de espacio de nombres específico para la aplicación? Hasta ahora lo usabas...

2024-01-07 12:02 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlake.kt
> +    private var atomicInteger = AtomicInteger(0)
¿Esta indentación te la pide el linter?

2024-01-08 08:53 UTC, JoseJordanF commented on .github/workflows/junit_test.yml
> +          chmod +x gradlew  # Asegúrate de que el archivo gradlew sea ejecutable
Sí, el caso es que le he dado todos los permisos habidos y por haber, pero al ejecutarlo en el contenedor sigue dando el fallo de que no tiene permisos de ejecución. Por eso y al ver que es más seguro darle los permisos en el flujo y que no hay manera aunque le dé todos los permisos, creo que sería mejor hacerlo así

2024-01-08 08:55 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlake.kt
> +    private var atomicInteger = AtomicInteger(0)
Diría que no, ha sido cosa de android studio

2024-01-08 09:02 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +import generatorId.generateUniqueId
Eso fue al principio cuando hice el proyecto completo de una vez, pero al crear un proyecto sencillo y vacío para no subir al repo cosas que no debía. No existen los paquetes por defecto con el nombre de la app como "com.app.claquetatfg_2", pero vaya, eso es simplemente creando una carpeta que contenga las de ahora con el espacio de nombres especifico.

2024-01-09 10:05 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/domain/UserFilmReviewManager.kt
> +import generatorId.generateUniqueId
(f85fc001c1725b31bb55cd2905ca35a931220772)

2024-01-09 10:06 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlake.kt
> +    private var atomicInteger = AtomicInteger(0)
(f85fc001c1725b31bb55cd2905ca35a931220772)

2024-01-09 10:35 UTC, JJ commented
Estaba aprobado, fusiónalo cuando quieras.

2024-01-09 10:40 UTC, merged