Explicación de lo hecho en el código para las recomendaciones en la documentación
JoseJordanF/Claqueta pull request #105
Opened 2023-11-19 10:54 UTC by JoseJordanF

Explicación detallada de lo realizado en el código y la toma de decisiones en ciertos problemas (closes #104)

2023-12-22 10:44 UTC, JJ approved these changes
Lo veo bien, en todo caso me habría gustado ver una sección de la documentación explicando las elecciones tomadas en cuanto a bibliotecas de test; posiblemente haya opciones algo mejores que podría explorar. Funciona, en todo caso, como producto mínimamente viable; si quieres incorporar los cambios comentados antes de fusionarlo o en otro PR, como mejor veas.

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +package generatorId
¿Es esto una buena práctica, usar un nombre de package diferente del del fichero?

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val atomicInteger = AtomicInteger(0)
Igual, ¿cuál es la convención para valores privados? Mayúsculas se suele usar para constantes, ¿no se usará aquí un _ al principio?

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val maxFdirectorId = 1024 // 10 bits
En vez de un comentario, ¿no crees que sería mejor definir una constante que tenga esa información? por ejemplo BITSFORINCREMENT=12

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +            throw IllegalArgumentException("maxFdirectorId must be at least 1")
No es un argumento, es un valor privado. ¿Seguro que esta excepción es la que se adecúa más? Además, tú mismo la estás definiendo, ¿no será mejor que simplemente la definas correctamente?

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
>      @BeforeEach
¿Esto es un beforeEach o before all? ¿En cada test vas a hacer esto? ¿O vas a hacer un solo test?
Lo digo porque estás usando lateinit, pero igual tendrías simplemente que inicializarlas cuando las declares...

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +        assert(id1 != id2)
¿Has documentado ya la biblioteca de aserciones que estás usando? Lo digo porque parece bastante simple, e igual sería un poco mejor usar bibliotecas un poco más complejas que te permitieran todo tipo de aserciones (más allá de "esto es verdad")

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +                "En general una pelicula muy entretenida y con una buena trama",
Si usas el mismo literal en dos lugares, deberías definir una constante.

2023-12-22 10:44 UTC, JJ commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +            "Las actuaciones han sido buenas pero sobre todo el prota ha sobresalido",
... y más si lo repites tres veces.

2023-12-23 12:14 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val atomicInteger = AtomicInteger(0)
Es código antiguo, ese problema ya está solucionado en el otro PR

2023-12-23 12:16 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +    private val maxFdirectorId = 1024 // 10 bits
Es un mero comentario, lo borro y listo

2023-12-23 12:18 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +            throw IllegalArgumentException("maxFdirectorId must be at least 1")
Al pasar a una función en lugar de una clase no es necesario esa comprobación, luego esa parte está borrada. Es que este PR es solo de documentación, la parte de código está en el otro PR.

2023-12-23 12:21 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
>      @BeforeEach
Las inicializo justo abajo en el onBefore, es como un constructor antes de ejecutar los tests.

2023-12-23 12:22 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +        assert(id1 != id2)
Puede que más adelante, si necesito algo más complejo. Pero me desconcierta, si la finalidad es el producto mínimamente viable, usar algo más complejo para algo que no lo necesita sería contradictorio.

2023-12-23 12:24 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +                "En general una pelicula muy entretenida y con una buena trama",
Okay

2023-12-23 12:24 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +            "Las actuaciones han sido buenas pero sobre todo el prota ha sobresalido",
Si creare otro json para ejemplos de reviews

2023-12-24 09:00 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/generatorId/SnowFlakeForFilm.kt
> +package generatorId
Es el nombre del paquete donde se encuentra, snowflake se encuentra en la carpeta generatorId.

2024-01-16 16:32 UTC, JJ commented
Y perdóname que te insista, pero *todos* los commits tienen que tener relación con un issue, que a su vez esté relacionado con una HU. Si escribes cosas como el mensaje de este commit 10db04228c6a8d018a3d3968cd6ae42622802ea9 es imposible saber qué estás corrigiendo, qué estaba equivocado para empezar, y por tanto si lo que escribes ahora es más correcto (o no) que antes.

2024-01-16 16:32 UTC, JJ commented
Además, este PR estaba ya aprobado. ¿Por qué no lo fusionaste y abriste otro nuevo?

2024-01-16 16:50 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Por otra parte, se debe abordar la implementación de la integración continua (CI) \cite{CI_supp} como una pieza
O sea que hable más de Circle CI y Semaphore CI haciendo ver porque escojo GHA y viendo también las partes malas de GHA

2024-01-16 19:01 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Por otra parte, se debe abordar la implementación de la integración continua (CI) \cite{CI_supp} como una pieza
Bueno, tienes que hablar según los criterios que establezcas, y algún de ese criterio tiene que ser específico para tu proyecto. ¿Hay alguno, por ejemplo, que use Kotlin sin necesidad de contenedores?

2024-01-17 10:28 UTC, JoseJordanF commented
Siento el último commit me ha obligado en local

2024-01-17 10:28 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Por otra parte, se debe abordar la implementación de la integración continua (CI) \cite{CI_supp} como una pieza
(b488e5d63c6198dd33939c7bd5fa33501fcc8851)

2024-01-17 17:07 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +continua, y configurar de manera efectiva dicho sistema. Este caso pensamos directamente en GitHub Actions aunque
Si los criterios de búsqueda, los incluiré y veré si los sistemas que he explorado cumplen o no y así argumentar mejor la decisión final. Aunque más abajo digo que la elección del sistema se dará según las necesidades del proyecto y añado que es posible utilizar más de un sistema si se requiere.

Por la parte del sistema para Kotlin, no creo que tenga ningún problema en añadirlo pero el tema esta que en la documentación no debería ir en la parte de planificación, ya que yo se supone que no se qué lenguaje voy a usar hasta que llega el cap de implementación. Luego si añado el sistema de CI especifico para Kotlin la documentación de ello debería ir en el cap de implementación no?

2024-01-18 08:02 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +continua, y configurar de manera efectiva dicho sistema. Este caso pensamos directamente en GitHub Actions aunque
Pero entonces lo que no tiene que ir en la parte de planificación es la elección de un sistema de CI. Simplemente menciona que se van a usar.

2024-01-18 11:35 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +continua, y configurar de manera efectiva dicho sistema. Este caso pensamos directamente en GitHub Actions aunque
Vale menciono que son y que se usaran, y en la parte de implementación expongo los criterios de elección y llevo a cabo la comparación y si cumplen o no con los criterios y procedo a la elección

2024-01-20 09:31 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
>      @BeforeEach
Pues por eso, aunque haya variables globales, realmente no lo son porque cada test es independiente y se reinicializan las variables para cada test. Es la forma en la que se hacen los test unitarios con JUnit en Kotlin o eso es lo que he encontrado en todos los ejemplos.

2024-01-20 09:35 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +        assert(id1 != id2)
No entiendo que tiene que ver la elección de herramientas con que sean más simples o no. Además, no implica que porque en esos test use esos assert no pueda usar otros más complejos cuando los necesite. Aun así, la biblioteca usada para esos assert es Kotlin, es el pack por defecto de Kotlin, o sea que ni siquiera tienes que importar.

2024-01-20 12:54 UTC, JJ commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
>      @BeforeEach
"Reiniciar" las variables precisamente las hace dependientes, tienes que acordarte de hacerlo. Si no hay una forma mejor de hacerlo, no hay más que decir.

2024-01-20 12:54 UTC, JJ commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +        assert(id1 != id2)
Pero ¿no habías elegido JUnit? ¿No tiene otras aserciones JUnit?

2024-01-22 09:18 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/domain/UserFilmReviewManagerTest.kt
> +        assert(id1 != id2)
Pues voy a informarme supongo que si

2024-01-23 16:22 UTC, JoseJordanF commented
No he añadido los criterios de búsqueda para ejecutar el workflow de los test y la elección para saber si el del lint lo he hecho bien o no.

2024-01-23 17:11 UTC, JJ requested changes
Hay algunos problemas, señalados aquí: de estructura, de foco de un solo PR, pero también de considerar ciertas herramientas que posiblemente serían más específicas de Kotlin como TeamCity (y posiblemente otras, he buscado y es lo que he encontrado)

Principalmente lo que tienes que pensar es que debes usar una estructura en la memoria que coloque cada decisión donde quien la lee lo espera. Hay también otras cuestiones de detalle para considerar.

2024-01-23 17:11 UTC, JJ commented on doc/secciones/04_planificacion.tex
>  En resumen, GitHub proporciona un entorno centralizado donde se encuentran todas las herramientas necesarias para el desarrollo, incluyendo el código, la documentación y el seguimiento del progreso.
También tienes esto en el capítulo de planificación, donde *ya* estás diciendo que usas GitHub. El sistema que elijas tiene que ser una decisión de implementación, que vayas a usar un entorno integrado de control de fuentes y trabajo para la planificación *sí* es algo que debería estar en este capítulo.

2024-01-23 17:11 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
Estás poniendo todo esto en el capítulo de planificación. ¿Seguro que es el mejor lugar donde ponerlo?

2024-01-23 17:11 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +El objetivo principal de este hito inicial es establecer la estructura del Trabajo de Fin de Grado (TFG) y preparar el proyecto. Después de completar este hito, se espera que los primeros puntos de l
Esto sigue en el capítulo de planificación. ¿No será más bien implementación?

2024-01-23 17:11 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +lenguaje. Cada cambio, cada nueva incorporación al código, se debe asegurar su calidad. Para ello se busca un lint para
Tienes que explicar qué es un lint, o más bien un *linter*. #1 no tiene por qué saberlo.

2024-01-23 17:11 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Por otro lado, necesitaremos un flujo de trabajo que nos permita comprobar la calidad del código escrito en dicho
La preocupación constante por la calidad viene de uno de los principios de desarrollo ágil. Cada vez que hables de testear y de calidad, debes engancharlo con lo que deberías haber dicho en el capítulo de metodología sobre el mismo.

2024-01-23 17:11 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +de lint debe ser admitida, abarcando la ejecución de herramientas de análisis estático de código para identificar y
de *linting*

2024-01-23 17:11 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +  \item \textbf{Notificaciones y Retroalimentación:} Jenkins proporciona opciones para notificar resultados de manera
Estás comprobando muchas opciones, alguna de las cuales son comunes a cualquier sistema. Antes de sopesar opciones, tienes que establecer tanto los criterios de búsqueda como los criterios de aceptación. ¿No te parece que uno de los criterios de búsqueda debería ser "Se puede usar gratuitamente por tiempo indefinido online"? Jenkins no tiene una opción gratuita online.

2024-01-23 17:11 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +  \item \textbf{Soporte de Contenedores:} Jenkins es compatible con contenedores a través de plugins como ''Docker
Si son irrelevantes a tu proyecto, no lo menciones. Sólo añade ruido para #1

2024-01-23 22:10 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +  \item \textbf{Soporte de Contenedores:} Jenkins es compatible con contenedores a través de plugins como ''Docker
Okay

2024-01-23 22:17 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
>  En resumen, GitHub proporciona un entorno centralizado donde se encuentran todas las herramientas necesarias para el desarrollo, incluyendo el código, la documentación y el seguimiento del progreso.
Pero GitHub como repositorio no como sistema de integración continua, o no lo estoy entendiendo bien

2024-01-23 22:20 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
Supongo que no, ya que lo dices, solo quería expresar que se va a usar un sistema de integración continua.

2024-01-23 22:20 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +El objetivo principal de este hito inicial es establecer la estructura del Trabajo de Fin de Grado (TFG) y preparar el proyecto. Después de completar este hito, se espera que los primeros puntos de l
Este tema ya lo hablamos, el M0 de configuración y el M0.5 que se hizo para quitar carga al M0 son solo de configuración y de los 4 primeros capítulos de la documentación.  Pero si como veo en los comentarios de arriba, si decidir usar GitHub para albergar el repositorio es Implementación, pues se cambia, pero la verdad pensaba que eso ya estaba cerrado.

2024-01-23 22:21 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +lenguaje. Cada cambio, cada nueva incorporación al código, se debe asegurar su calidad. Para ello se busca un lint para
Okay

2024-01-23 22:21 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Por otro lado, necesitaremos un flujo de trabajo que nos permita comprobar la calidad del código escrito en dicho
Okay lo conectaré

2024-01-23 22:21 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +de lint debe ser admitida, abarcando la ejecución de herramientas de análisis estático de código para identificar y
okay

2024-01-23 22:21 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +  \item \textbf{Notificaciones y Retroalimentación:} Jenkins proporciona opciones para notificar resultados de manera
Me centraré en las necesarias

2024-01-24 08:06 UTC, JJ commented on doc/secciones/04_planificacion.tex
>  En resumen, GitHub proporciona un entorno centralizado donde se encuentran todas las herramientas necesarias para el desarrollo, incluyendo el código, la documentación y el seguimiento del progreso.
¿A ti que te parece? ¿Es parte  de la planificación del proyecto?

2024-01-24 08:07 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
Incluso aunque vayas a decir eso ¿de qué forma crees que forma parte de la planificación del proyecto? ¿En qué ayuda eso al tribunal a entender qué has planificado y  la metodología que has seguido para hacerlo?

2024-01-25 08:57 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
>  En resumen, GitHub proporciona un entorno centralizado donde se encuentran todas las herramientas necesarias para el desarrollo, incluyendo el código, la documentación y el seguimiento del progreso.
Yo fijándome en otros proyectos, creía que ese era su lugar. Por otra parte, mi duda está si quito todo el apartado de GitHub de la planificación. Que debo poner en la planificación

2024-01-25 09:02 UTC, JJ commented on doc/secciones/04_planificacion.tex
>  En resumen, GitHub proporciona un entorno centralizado donde se encuentran todas las herramientas necesarias para el desarrollo, incluyendo el código, la documentación y el seguimiento del progreso.
La respuesta  a "qué debo poner" es siempre lo que efectivamente hagas: en este caso para planificar. No se trata de qué debes poner, sino de qué debes hacer y dónde debes ponerlo. Si no estás planificando nada, evidentemente el capítulo estará vacío. Lo que no puedes hacer es poner cosas en un capítulo "porque hay que poner algo" y no ponerlas donde correspondan de forma natural.

2024-01-25 09:08 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
Si la elección de repositorio se debe dar en la implementación como he visto arriba, si entiendo que esta explicación no sea relevante en la planificación y sí en la implementación. Pero vuelvo al mismo problema de arriba que debo poner en la planificación

2024-01-25 09:19 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
Jose, la memoria debe ser un reflejo del trabajo hecho, y debe reflejar lo hecho con una estructura adecuada y comprensible. Si lo que me estás preguntando es "¿Qué voy a poner en el apartado de planificación si no he hecho ninguna planificación?" la respuesta, ¿cuál crees que es? Si la pregunta es ¿qué debo planificar para luego ponerlo en la memoria?, ¿crees que este es el sitio correcto para hacerlo? Los PRs deben tener un ámbito finito, porque si no pueden acabar abarcando todo el trabajo y toda la memoria. No hay nada en este PR, ni en los issues de los que trata, que hable de planificación. Lo más conveniente, si te parece bien, es que dejemos la planificación (o su ausencia) para cuando corresponda, ¿no te parece?

2024-01-25 10:40 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
Antes de cerrarlo, deja las partes que sí se han aprobado y mueve estas a donde veas más conveniente. Cambia también el cuerpo del mismo para que se ajuste más a lo que hay en él efectivamente.

2024-01-25 11:12 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
O sea solo dejo realmente las parte del principio que fue lo que se aprobó y por lo que se hizo el PR la explicación de lo hecho en el código para las recomendaciones. Y te refieres a cambiar el cuerpo del PR, o sea borrar todo lo que no tenga que ver realmente con el?

2024-01-25 11:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +proporcionar una base sólida para prácticas como la implementación continua y la mejora continua.
En todos estos comentarios se te han solicitado cambios; en algunos casos son cambios de lugar del texto, en otros que lo dejes aparte hasta más adelante. Cambia el objeto del PR para que hable sólo de estos cambios, míralos uno por uno, y haz lo que veas más conveniente.

2024-01-25 11:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +El objetivo principal de este hito inicial es establecer la estructura del Trabajo de Fin de Grado (TFG) y preparar el proyecto. Después de completar este hito, se espera que los primeros puntos de l
Por ejemplo, aquí se sugiere que consideres un cambio de capítulo. Si quieres cambiarlo en este PR, hazlo, si no, guárdalo y cuando llegues a ese capítulo lo incluyes.

2024-01-30 11:04 UTC, merged