Arreglos en la documentación del capitulo de implementación antes de proseguir
JoseJordanF/Claqueta pull request #111
Opened 2024-02-02 08:27 UTC by JoseJordanF

De esta manera se puede continuar con el cap de implementación tras atajar dichas confusiones en la documentación:

-closes(#110)

2024-02-05 09:06 UTC, JJ requested changes
Hay una parte que es correcta, donde explicas el M1, pero el resto convendría que le dieras una vuelta.

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +elegir. Teniendo en cuenta el uso de git como sistema de control de versiones debido a su naturaleza distribuida frente a
Generalmente un capítulo tendrá una sección de introducción donde se explicará cuál es el alcance del capítulo y a continuacion se dirá la estructura que se va a seguir, introduciendo las diferentes secciones. Así se entiende mejor de qué estamos tratando. ¿No has pensado meter estas decisiones que ya estás explicando en su propia sección?

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Como por ejemplo GitHub, GitLab y Bitbucket, plataformas de desarrollo colaborativo que comparten muchas características,
Usa siempre enlaces.

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Teniendo esto presente, tenemos varias opciones para escoger un repositorio basado en git que albergue nuestro proyecto.
Tienes que decir antes qué requisitos hay. En este caso ¿será que sea una solución gratuita y online, por ejemplo?

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +continua (CI/CD), a través de GitHub Actions, lo convierten en una opción poderosa y atractiva.
Cada vez que menciones cualquier cosa relacionada con los tests y demás, tendrás que hacer una referencia al desarrollo ágil.

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +GitLab, por otro lado, se centra en DevOps y CI/CD, ofreciendo un conjunto integral de herramientas, desde el seguimiento
GitLab es exactamente igual que GitHub. No se centra ni en una cosa ni en otra.
También convendría que expusieras los criterios por los que vas a hacer la elección de antemano, no poner en cada una de las herramientas diferentes factores que no tienen nada que ver con lo que lo hayas elegido o no.

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Bitbucket parte del ecosistema de Atlassian, se destaca por su estrecha integración con otras herramientas de Atlassian,
*es* parte.

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\subsection{M0. Configuración inicial del TFG - Estructura, objetivos y metodología usada}
¿De qué sección es esto subsección?

En todo caso, como creo que te he comentado, este capítulo se refiere a la implementación del *proyecto*, no la implementación del TFG  como producto. Establecer cuál es la metodología no parece que forme parte de la implementación, ¿no te parece?

Generalmente, estos primeros PMVs/milestones se suelen documentar como parte del capítulo de planificación.

2024-02-05 09:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\subsection{M05. Capítulo de planificación}
¿Crees que el capítulo de *planificación* debe explicarse dentro del capítulo de *implementación*? ¿O dentro del de planificación?

2024-02-05 09:07 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +habrá que discutir que herramientas van a usarse para desarrollar o llevar a cabo estos hitos y el porqué de su
Sí, no me di cuenta

2024-02-05 09:08 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Por lo tanto, ya que el desarrollo se va a basar en los productos mínimamente viables de los hitos. Lo primero que
Okay

2024-02-05 09:14 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +elegir. Teniendo en cuenta el uso de git como sistema de control de versiones debido a su naturaleza distribuida frente a
Si deberían ir en la sección de Herramientas que se usan durante el desarrollo. ¿Por lo demás, creo que si se hace una introducción y se comenta la estructura que tendrá el capítulo no?.

2024-02-05 09:16 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +elegir. Teniendo en cuenta el uso de git como sistema de control de versiones debido a su naturaleza distribuida frente a
Eso es lo que te digo, sí.

2024-02-05 09:18 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Teniendo esto presente, tenemos varias opciones para escoger un repositorio basado en git que albergue nuestro proyecto.
Si añadiré esos requisitos antes de nombrar las distintas opciones que tenemos

2024-02-05 09:19 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +continua (CI/CD), a través de GitHub Actions, lo convierten en una opción poderosa y atractiva.
Vale, lo he intentado en todas las partes relacionadas con ellos, pero me parecía ser muy pesado. Pero lo añadiré 😄

2024-02-05 09:24 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +GitLab, por otro lado, se centra en DevOps y CI/CD, ofreciendo un conjunto integral de herramientas, desde el seguimiento
Pero mi duda es si son exactamente iguales que criterio puedo usar para decidir entre ambos, es lo que me cuesta más. Cuando hay dos herramientas muy similares, como decido qué usar. Puedo alegar el tema de la comunidad, que por lo que decido escogerlo y lo señalo. Pero si no es criterio suficiente, no sé cómo escoger una herramienta u otra.

2024-02-05 09:27 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Bitbucket parte del ecosistema de Atlassian, se destaca por su estrecha integración con otras herramientas de Atlassian,
cierto

2024-02-05 09:29 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +GitLab, por otro lado, se centra en DevOps y CI/CD, ofreciendo un conjunto integral de herramientas, desde el seguimiento
La memoria del TFG no debe ser más que el reflejo de las decisiones tomadas de la forma más honesta posible. Si no has elegido Gitlab "porque está enfocado a DevOps", ponlo así. Si has elegido GitHub, di por qué lo has elegido y punto.
El poner el resto de las herramientas disponibles se hace por varias razones
1. Para mostrar al tribunal que conoces qué herramientas hay, y no simplemente has usado algo porque no te has molestado en buscar otras opciones. Una de las rúbricas evalúa si el estudiante sabe examinar las oportunidades que hay en el mercado y aprovecharlas.
2. Para mostrar al tribunal que eres consciente de cuales son las funcionalidades necesarias de una herramienta, y que la decisión tomada abarca esas funcionalidades. Es decir, no "has elegido postgresql porque me gusta" mientras que todo lo que necesitas en tu proyecto es una base de datos clave-valor, por ejemplo.
3. Para mostrar al tribunal que entiendes perfectamente qué es lo que estás usando y por qué. Si pones GitHub, gitLab y, no sé, Wordpress estás demostrando que no sabes lo que estás haciendo, sino tomando literalmente lo que haya en no sé qué página (aquí no hay mucha confusión posible, pero verás cuando se llegue a los framework de test o a los de microservicios)

2024-02-05 09:32 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\subsection{M0. Configuración inicial del TFG - Estructura, objetivos y metodología usada}
JJ este Milestone estaba en el cap de planificación, pero en el otro PR me dijiste que lo moviera. Pero antes estaba en la planificación 😓. Me habré confundido seguramente.

2024-02-05 09:37 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\subsection{M0. Configuración inicial del TFG - Estructura, objetivos y metodología usada}
Yo nunca te voy a decir que hagas algo, sino que consideres alternativas. Es tu TFG y son tus decisiones, no las mías, y si te digo que hagas algo estaré tomando decisiones por ti.
En general, en todos mis TFGs, digo lo mismo: los dos primeros milestones no son tanto implementación como infraestructura para la misma, son internos, y por tanto forman parte de la planificación; como tal, deben de ir en ese capítulo.
En la planificación, por otro lado, también hay que incluir la planificación *inicial* de un proyecto ágil. En desarrollo ágil no se planifica todo desde el principio, ni se planifican todos los PMVs, sino que se adapta a las necesidades del cliente y las necesidades que surjan. Pero hay que comenzar por algún sitio antes de implementar, y esa planificación inicial tiene que ir en el capítulo correspondiente, junto con la infraestructura que se haya creado para seguir esa planificación.
Siento en todo caso que lo hayas entendido así, pero te aconsejaría en todo caso que usaras un criterio propio (y relacionado con el HU correspondiente, #1, para establecer cuando y en qué momento comentar cada cosa).

2024-02-05 09:37 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\subsection{M05. Capítulo de planificación}
Perdona, pero este también estaba en planificación junto al M0. Pero me dijiste que lo moviera al igual que el M0.
https://github.com/JoseJordanF/Claqueta/pull/105#discussion_r1463634407

2024-02-05 09:41 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\subsection{M0. Configuración inicial del TFG - Estructura, objetivos y metodología usada}
Perfecto lo volveré a añadir al cap de planificación, yo también entiendo que es su sitio, ya que no tiene que ver con la implementación solo con la configuración inicial y los conceptos para llevar a cabo el proyecto. No te preocupes, seguramente haya sido una mala interpretación mía.

2024-02-05 09:43 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\subsection{M05. Capítulo de planificación}
Siento que lo hayas entendido mal. Me refería a esta frase:

> para ello se han adoptado las mejores prácticas haciendo uso de GitHub Actions 

*Se han adoptado* es una decisión de implementación. En planificación tendrás que decir que se debe garantizar la calidad de la documentación, para no pasar a etapas siguientes con errores en la misma. En el capítulo de implementación tendrás que decir qué has decidido usar para llevar a cabo ese tipo de prueba.

Insisto en lo mismo, sólo te hice una sugerencia sobre dónde podría ir. El problema es también que al usar líneas muy largas no se puede comentar en la línea específica donde suceda algo. Ya he visto que en texto sucesivo estás usando líneas de 80 caracteres, que hacen más fácil los comentarios atómicos.

2024-02-05 09:47 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\subsection{M05. Capítulo de planificación}
Como te decía arriba mala interpretación mía, no te preocupes, lo vuelvo a colocar en su sitio 😄. Sii es que esas líneas se escribieron antes, pero ahora intento que todas las lineas sean de 80

2024-02-05 09:48 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +GitLab, por otro lado, se centra en DevOps y CI/CD, ofreciendo un conjunto integral de herramientas, desde el seguimiento
Okay okay

2024-02-12 09:30 UTC, JJ commented
Creo que para que GitHub lo entienda no debes poner el issue entre paréntesis

2024-02-12 09:38 UTC, JJ requested changes
Aparte de los comentarios de detalle, conviene que te pares un poco antes de cada capítulo a pensar en la estructura del mismo, qué conocimientos dependen de otros, qué hay que contar, como hay que modularizarlo y demás.

2024-02-12 09:38 UTC, JJ commented on doc/bibliografia.bib
> +@misc{GH_web,
Creo que ya te lo he comentado, pero si no te lo repito: páginas web simplemente se enlazan, no se incluyen en la bibliografía.

2024-02-12 09:38 UTC, JJ commented on doc/bibliografia.bib
> +	title        = {GitHub wbsite},
Aparte de que en todos hay un error en el título.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +hitos y el porqué de su elección.
En desarrollo ágil, los PMVs no están *todos* establecidos desde el principio, así que tendrás que comentarlo. Recuerda que desarrollo ágil no es sólo algo que mencionas al principio, tiene una serie de principios que informan todas las decisiones que se van tomando de forma directa.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Primeramente, se decidirá en este caso que herramienta se usara para albergar el proyecto y poder definir los hitos,
qué lleva acento. ¿Estás seguro de que textidote está funcionando correctamente?

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +además de permitir un seguimiento del desarrollo mucho más controlado. Siguiendo así con el enfoque ágil visto en el
Siguiendo debe tener coma antes, no punto.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Por lo tanto, ya que el desarrollo se va a basar en los productos mínimamente viables. Lo primero que
¿Comienzas una sección con "Por lo tanto"? ¿Por lo tanto de qué?

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Por lo tanto, ya que el desarrollo se va a basar en los productos mínimamente viables. Lo primero que
El desarrollo no se "basa" en los PMVs, va avanzando a base de PMVs. Y por otro lado, también coma en vez de punto.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +debemos hacer es definir un repositorio en el que definir estos hitos. Por ello es la primera herramienta
Y esto debería ser un punto y coma, pero por lo pronto vamos a concentrarnos en usar bien las comas en vez de los puntos. 
Te aconsejaría que consultaras algún documento al respecto; las guías de estilo de algunos periódicos están publicadas online y te indican como usarlas; también textidote debería hacerlo, pero parece que no es el caso.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +que vamos a elegir. Teniendo en cuenta el uso de git como sistema de control de versiones debido a su
¿Lo usas por su naturaleza distribuida?
Aquí parece que estás explicando una decisión confrontando dos herramientas diferentes. Aunque en general esa es la forma de hacerlo, conviene *siempre* que expliques la justificación *real* que te ha llevado a usar uno u otro. Hoy por hoy, ¿cuál es la herramienta de control de fuentes que se usa de forma más generalizada? ¿Conoces a alguien que use subversion?

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +mercurial.
También está bazaar y SourceSafe, pero de veras que con `git` precisamente no sería necesaria hacer tanta justificación.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Teniendo esto presente, tenemos varias opciones para escoger un repositorio basado en git que albergue
La secuencia para justificar una decisión es siempre
1. Establecer los requisitos/criterios de búsqueda. Qué es apropiado para el proyecto.
2. Establecer una serie de medidas objetivas para la elección; alguna puede tener un cierto grado de subjetividad, pero en todo caso hay que escoger siempre lo que sea más adecuado *en términos del proyecto*
3. De qué forma las herramientas existentes cumplen los criterios.
4. Finalmente, se expresa la elección basada en las medidas objetivas que se han expresado antes.

En el caso específico de GitHub vs. otras plataformas, es muy difícil apreciar las ventajas de GitHub frente a GitLab, al menos al nivel que se está usando, por lo que usar simplemente familiaridad con la plataforma puede ser totalmente válido. Se puede justificar más adelante cuando se usen los workflows de GitHub y volverse a mencionar que ya se tenía conocimiento de los mismos y ofrecen la misma o más funcionalidad que GitLab, pero poco más.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +que ofrecen funciones más avanzadas y capacidad de escalar para adaptarse a las necesidades de equipos y
¿Son relevantes para tu proyecto los planes de pago? Si no es así, ¿por qué lo incluyes?
Lo que se busca con esta documentación no es rellenar ni apabullar al #1 , sino que este entienda la decisión que se ha tomado.

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +En general, las opciones gratuitas de estas plataformas son adecuadas para muchos proyectos pequeños y
En general, ¿crees que todo lo que has dicho antes de este párrafo es relevante?

2024-02-12 09:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Por otro lado, necesitaremos un flujo de trabajo que nos permita comprobar la calidad del código escrito en
¿En la misma sección?

2024-02-12 09:54 UTC, JoseJordanF commented on doc/bibliografia.bib
> +@misc{GH_web,
a pie de pagina??

2024-02-12 09:55 UTC, JJ commented on doc/bibliografia.bib
> +@misc{GH_web,
O un enlace en LaTeX directamente, con \url o \href; creo que uno está en el paquete urlx y otro en hyperref, si no me equivoco.

2024-02-12 10:20 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Primeramente, se decidirá en este caso que herramienta se usara para albergar el proyecto y poder definir los hitos,
Si se está pasando lo puedes ver tú mismo, pero no entiendo que "que" lleva acento, no hay ninguno con sentido interrogativo ni exclamativo

2024-02-12 10:22 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +además de permitir un seguimiento del desarrollo mucho más controlado. Siguiendo así con el enfoque ágil visto en el
Okay

2024-02-12 10:26 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Primeramente, se decidirá en este caso que herramienta se usara para albergar el proyecto y poder definir los hitos,
Es una [oración interrogativa ("¿qué herramienta?") indirecta](https://www.rae.es/espanol-al-dia/tilde-en-que-cuales-quienes-como-cuan-cuantoaosas-cuando-donde-y-adonde#:~:text=Las%20palabras%20qu%C3%A9%2C%20cu%C3%A1l%2Fes,tienen%20sentido%20interrogativo%20o%20exclamativo.)

2024-02-12 10:33 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +debemos hacer es definir un repositorio en el que definir estos hitos. Por ello es la primera herramienta
Okay

2024-02-12 10:35 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +que vamos a elegir. Teniendo en cuenta el uso de git como sistema de control de versiones debido a su
O sea, no justifico porque uso git simplemente digo que uso por su popularidad y ya?

2024-02-12 10:36 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +mercurial.
Tampoco creo que sea tanta justificación, son cuatro líneas. Pero vale haré lo que mencionas arriba y no mencionaré otras herramientas.

2024-02-12 10:38 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +que vamos a elegir. Teniendo en cuenta el uso de git como sistema de control de versiones debido a su
Di que lo usas *por la razón real que lo usas*. La memoria es para documentar las decisiones tomadas. ¿Lo usas porque es distribuido en vez de subversion que es centralizado? ¿No? Entonces, ¿hay una razón para incluir esa frase en la memoria?

2024-02-12 10:40 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Por otro lado, necesitaremos un flujo de trabajo que nos permita comprobar la calidad del código escrito en
Está en la sección de la elección del lenguaje de programación. ¿No debería estar ahí?

2024-02-12 10:41 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +En general, las opciones gratuitas de estas plataformas son adecuadas para muchos proyectos pequeños y
Okay dejaré solo él en general.

2024-02-12 10:42 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Teniendo esto presente, tenemos varias opciones para escoger un repositorio basado en git que albergue
Pero he justificado su uso por su fuerte comunidad, eso no es suficiente también?

2024-02-12 12:58 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Por otro lado, necesitaremos un flujo de trabajo que nos permita comprobar la calidad del código escrito en
¿El flujo de trabajo es parte del lenguaje de programación?

2024-02-15 11:35 UTC, JJ requested changes
A ver, previo al contenido, quizás tendrías que plantearte la estructura de este capítulo. Un capítulo de implementación tiene, a priori, una estructura clara: la de los milestones que se van implementando, uno por uno; los que has empezado a plantear en el capítulo de planificación, y los que vayan surgiendo efectivamente durante la implementación.
En esa estructura es donde tienes que tomar las diferentes decisiones tomadas, mostrando que sabes identificar los problemas que hay para implementar el PMV correspondiente e identificar los problemas que el cliente tiene.  Así que antes de añadir más contenido o corregir el contenido específico, me gustaría ver con más o menos claridad la estructura de este capítulo al menos hasta el segundo nivel (de subsecciones).
Lo mejor es que abras otro PR para esto, que luego puedes fusionar con esta rama si es necesario.

2024-02-15 11:35 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +debemos hacer es definir un repositorio en el que definir estos hitos. Por ello es la primera herramienta
... resuelve también cuando lo hayas visto.

2024-02-15 11:35 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +En general, las opciones gratuitas de estas plataformas son adecuadas para muchos proyectos pequeños y
¿Puedes quizás expresar "opciones gratuitas" mejor?

2024-02-15 11:35 UTC, JJ commented on doc/secciones/06_implementacion.tex
>  \subsection{Inyección de dependencias}
La lista de subsecciones tiene que tener algún tipo de coherencia. Puede ir de lo más concreto a lo más abstracto, pueden ser secuencias temporales, pueden ser enumeraciones de cosas del mismo tipo. ¿Te parece que "persistencia de datos" e "inyección de dependencias" tienen algún tipo de coherencia?

2024-02-15 11:35 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Por otro lado, necesitaremos un flujo de trabajo que nos permita comprobar la calidad del código escrito en
Los flujos de trabajo no solo son para testing. De hecho, los estás usando para pruebas de la memoria y es de lo primero que has implementado.

2024-02-15 11:35 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +
Espera, ¿esto es parte de Testing?

2024-02-15 11:57 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +
No ese es el flujo del linter

2024-02-15 11:58 UTC, JoseJordanF commented
Creo que te estás confundiendo de commit algunos comentarios como el de 
"... resuelve también cuando lo hayas visto."
No son del commit que te acabo de subir

2024-02-15 12:23 UTC, JJ commented
> Creo que te estás confundiendo de commit algunos comentarios como el de "... resuelve también cuando lo hayas visto." No son del commit que te acabo de subir

Es posible, pero es que voy viendo cosas...

En ese sentido, quizás sería un poco más práctico que en este capítulo fuéramos milestone por milestone, para poder ver bien la estructura de cada uno, ¿no? Este ya está hecho, no pasa nada, pero concéntrate quizá en corregir lo del milestone 0 y luego si acaso sacamos otro milestone

2024-03-11 11:22 UTC, JJ commented
Este PR no está fusionado, y además tiene conflictos; es que el falta para terminar el m0. ¿Cómo es que se ha quedado así?

2024-03-12 10:17 UTC, merged