Documentación y código relativo al M3
JoseJordanF/Claqueta pull request #121
Opened 2024-04-02 09:06 UTC by JoseJordanF

En este PR se pretende establecer porque se necesita una herramienta de persistencia de datos, qué criterios debe cumplir está para escoger entre las distintas herramientas que hay. Una vez escogida que necesitamos para poder usar dicha herramienta en nuestro proyecto:
(-closes #117)
(-closes #118)

Por otro lado, también discutimos sobre que son los registros/logs y porque nos podrían ayudar en nuestro proyecto, además de escoger una herramienta para ello:
(-closes #119)
(-closes #120)

2024-04-02 09:08 UTC, JJ commented
Deberías intentar concretar un poco más cuales son las necesidades y requisitos de las herramientas y especificarlo en el milestone antes de introducir este texto y la implementación correspondiente.

2024-04-02 09:14 UTC, JJ reviewed
Para establecer una herramienta de persistencia tienes que especificar antes
1. Qué tipo de aplicación estamos haciendo. ¿Es una sola instancia de la aplicación, que sirve para todo el mundo, o es una aplicación que pretendemos que la gente se instale para, no sé, un club de cine?
2. Si vas a usar las mismas herramientas para desplegar que para desarrollar y testear. ¿Se puede testear fácilmente la aplicación si usas una herramienta online?
3. Si quieres crear una herramienta monolítica o, al ser software libre, tienes quieres hacer una herramienta con una capa de persistencia genérica que pueda usar fácilmente diferentes capas de persistencia.

En todo caso, la capa de persistencia (y la de logs, y la de configuración) deben abstraerse y desacoplarse de la lógica de negocio, usando en cada una de ellas inyección de dependencias. Y en cualquiera de ellas tienes que usar, como te dije, un sistema de configuración.
Finalmente, no trates de hacer en un solo PR *todo* lo que pretendes hacer. En un proyecto, como te he comentado, tienes que hacer los PRs lo más atómicos posibles para que se pueda examinar cada cosa por sus propios méritos y un error en una parte no bloquee todo el PR

2024-04-02 09:14 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Una opción podría ser MongoDB, una base de datos NoSQL que usa un modelo de documentos JSON para almacenar datos,
Una opción ¿de qué? No has especificado cuales son los requisitos de la herramienta que necesitas, y no lo has hecho porque
1. No está especificado en el milestone qué es un producto mínimamente viable
2. No está especificado en los issues qué es lo que necesita el usuario.

2024-05-24 08:01 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +            exampleUsers[1].id,
¿Te das cuenta que estás poniendo dos variables con algo que con una iba que chutaba?

2024-05-24 08:04 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +El principio que se debe tener en cuenta es, inversión de dependencias
Nunca coma entre sujeto y predicado.

2024-05-24 14:17 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/User.kt
> +    val id: String,
Mi idea era simplemente usar el ID cuando lo hablamos de esa manera no es necesario ni siquiera comprobar si son o no el mismo usuario. Pero con otro nivel te refieres a la aplicación cliente, o sea el front que es donde realmente importa el nombre de usuario, porque a mí en back no me es necesario.

2024-05-24 14:17 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +    fun `When I want to save a list of reviews`() {
O historias de desarrollador no?

2024-05-24 14:19 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +    fun `When I want to save only one user`() {
Entiendo que tendré que crear una HD en la que el desarrollador quiera asegurar que los datos de sus usuarios no se pierden y que están disponibles siempre que lo deseen.

2024-05-24 14:19 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +            exampleUsers[1].id,
Sí, quitaré el username y dejaré el ID

2024-05-24 14:23 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/examples/usersExamples.json
> +    "id": "0",
Eso es un fichero de ejemplo, simplemente, ese valor está a mano porque no este vacío, pero es SnowFlake el que se encarga de generar el ID del usuario

2024-05-24 14:23 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +El principio que se debe tener en cuenta es, inversión de dependencias
Perdón

2024-05-24 14:34 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +            exampleUsers[1].id,
¿Y dónde metes entonces el username?

2024-05-24 14:36 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +            exampleUsers[1].id,
A ver, que igual no necesitas el username, en realidad... El userID Puede ser suficiente. Pero si en algún lado dice que los comentarios de un usuario deben ser reconocibles para ese usuario, entonces tendrás que usar un username y no un userid.

2024-05-24 14:38 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +            exampleUsers[1].id,
Si por eso lo usaba, pero he decidido añadir el id porque para trabajar con el obj usuario es más sencillo, además así el formato del id de las películas y el id del usuario es el mismo

2024-05-24 14:38 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +            exampleUsers[1].id,
Así asocio en el hashMap las reviews del usuario y las de la película con eficiencia constante

2024-05-24 17:29 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/User.kt
> +    val id: String,
([04913fe](https://github.com/JoseJordanF/Claqueta/pull/121/commits/04913fe529955c6141c3835527ab970b7551ffe9))

2024-05-24 17:29 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +                exampleReviews[i].userId,
([04913fe](https://github.com/JoseJordanF/Claqueta/pull/121/commits/04913fe529955c6141c3835527ab970b7551ffe9))

2024-05-27 07:51 UTC, JJ requested changes
Por favor, haz siempre cambios, incluso los que se soliciten en un ocmentario, sobre todo si son de calado, mediante un issue, historia de desarrollador o como quieras llamarlo. Sin issue no puedes saber como testear que lo estás haciendo correctamente. Recuerda que siempre hay que saber qué se va a hacer ahora, y si lo que se hace está bien.

2024-05-27 07:51 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +    var users: HashSet<String> = hashSetOf(),
Siempre deberías hacer cambios referenciando un issue y una historia de usuario, si no estás haciendo simplemente "lo que me dicen" sin tener una comprensión profunda de lo que estás haciendo y como afecta al modelo del problema.
En este caso, estás diciendo que un usuario se identifica simplemente por una cadena; tienes que intentar asegurarte de que esa cadena es única. Y eso deberías haberlo puesto en un issue que referenciara a una historia de usuario.

2024-05-27 07:51 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +        if (users.add(name.lowercase())) {
Aquí por ejemplo ¿estás imponiendo que el nombre esté en minúsculas? ¿A qué HU/HD responde eso, y por tanto como añade valor para el cliente?

2024-05-27 07:51 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +            val anotherUser = users.find { it == name }
Aquí no estás usando `name.lowercase()`. Una vez más, si no tienes un modelo claro desde el principio, puede que cometas este tipo de error.
Supongo que users.add devuelve *truish* si efectivamente es así, si no devuelve false y por eso se activa el `else`, ¿no?

2024-05-27 07:51 UTC, JJ commented on claqueta_tfg/src/test/resources/examples/reviewsExamples.json
> +    "userName": "JoseJordan",
¿Qué pasa si ahora añado también `josejordan`?

2024-05-27 07:56 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +    var users: HashSet<String> = hashSetOf(),
Si perdona, aún se me olvida crear issues para estos cambios o correcciones, sé que siempre debo referenciarlo en el commit así que debo crearlo, pero se me olvida cuando son correcciones.

2024-05-27 07:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +    var users: HashSet<String> = hashSetOf(),
Perdón ninguno, y no siempre va a hacer falta en correcciones, pero en este caso es un cambio de modelo del problema y sí sería conveniente.

2024-05-27 07:58 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +        if (users.add(name.lowercase())) {
Sisi claro no hay nada que explique eso, hago la HD en cuanto pueda y la referencio para resolver la conversación y las anteriores.

2024-05-27 08:01 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/examples/reviewsExamples.json
> +    "userName": "JoseJordan",
Pues daría error, uno de los test unitarios hace ese test. Ya que cuando lo vas a añadir se ve si ya hay un josejordan independientemente si es en minúscula o en mayúscula

2024-05-27 12:20 UTC, JJ commented on claqueta_tfg/src/test/resources/examples/reviewsExamples.json
> +    "userName": "JoseJordan",
¿Y eso a qué historia de usuario corresponde?

2024-05-27 15:03 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +        if (users.add(name.lowercase())) {
#140

2024-05-27 15:30 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/examples/reviewsExamples.json
> +    "userName": "JoseJordan",
#139

2024-05-27 15:31 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/ClaquetaManager.kt
> +    var users: HashSet<String> = hashSetOf(),
#139 #138

2024-05-27 16:35 UTC, JJ requested changes
El nivel de detalle sobre la implementación quizás deberías reconsiderarlo. Lo importante siempre en la memoria es dar detalles sobre las deciciones tomadas y lo que han implicado. Los nombres que se les den tendrás que plantearte si al tribunal les hace falta conocerlo.

2024-05-27 16:35 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +        assertEquals(filmList.toList()[1].id, loadList[loadList.size - 2].id)
¿No hay alguna alternativa a usar números mágicos en los tests?

2024-05-27 16:35 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +capa de persistencia que guarda y recupera datos de archivos Json llamada
No sé hasta qué punto tienes que dar detalles así sobre la implementación. Normalmente #1 no los necesita para evaluar.

2024-05-27 17:18 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +        assertEquals(filmList.toList()[1].id, loadList[loadList.size - 2].id)
No los consideraría mágicos, sabes que las 3 últimas películas deben coincidir con las tres introducidas, luego el índice debe ser ese sí o sí.

No sé si habría otra forma de hacerlo, pero vaya es acceder a las 3 últimas entradas en la lista, no sé si se podría hacer sin números, ya que el get de la lista necesita un índice.

2024-05-27 18:27 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/database/DatabasePersistenceLayerTest.kt
> +        assertEquals(filmList.toList()[1].id, loadList[loadList.size - 2].id)
En realidad, *todas* deberían coincidir con las introducidas, ¿no?
En todo caso, digo lo de siempre: comprobar que está ahí algo que se ha escrito no es que añada mucho valor al cliente. Se deben testear cosas relacionadas con las historias de usuario.

2024-05-28 08:02 UTC, JJ approved these changes
:+1:

2024-05-28 08:03 UTC, merged