Gestión de la configuración de la aplicación
JoseJordanF/Claqueta pull request #124
Opened 2024-04-04 22:44 UTC by JoseJordanF

En este PR se pretende establecer la introducción al M3, se discute que es un sistema de configuración y se decide porque usar uno y se discute cuál usar. Por la parte de código se añaden las dependencias necesarias y se crean los tests necesarios para demostrar el uso del sistema de configuración, además de crear los ficheros de configuración de prueba:

(-closes #122)
(-closes #123)

2024-04-05 10:23 UTC, JJ reviewed
¿Seguro que Config no te maneja también dotenv? Deberías intentar buscar una biblioteca que trabajara con todo; de esta forma tienes dos bibliotecas diferentes, con objetos diferentes.
Si no lo encuentras, deberías intentar en todo caso que el objeto configuración fuera único, y separado del objeto en el que lo vayas a incluir. Tienes que tratar de desacoplar los servicios de la lógica de negocio lo más posible. Por el principio de separacion de ocupaciones, un "userFilmReviewManager" no debería tener que ocuparse de leer la configuración.

2024-04-07 09:29 UTC, JoseJordanF commented
No entiendo qué está pasando, en local los test pasan perfectamente en los contenedores de docker. El error lo señala en el test de JSON, pero no hay ningún error, el test se pasa perfectamente tanto en el IDE como en los 3 contenedores de docker.

2024-04-07 10:10 UTC, JJ commented
En general, no debes usar mayúsculas en nombres de ficheros en repositorios, salvo que sea convencional hacerlo (Dockerfile, README.md)

2024-04-07 10:15 UTC, JJ requested changes
De veras que tienes que tratar de poner en práctica el concepto de producto *mínimamente* viable. Para este producto sólo haría falta un tipo de fichero de configuración, el que tú elijas (aparte de los habituales, .env, variables de entorno y opciones de línea de órdenes - que creo que no has cubierto -)

2024-04-07 10:15 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        val separador = if (pathFile.contains('/')) '/' else '\\'
Uf. Estás intentando manejar ficheros de diferentes tipos de sistemas de ficheros. No sé si el milestone te pedirá eso, pero si te lo pide, debes intentar usar una biblioteca para ello.

2024-04-07 10:15 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            pathFile.endsWith(".conf") -> {
¿Te parece que en un producto mínimamente viable haya que manejar todos estos formatos, y cada uno con un código diferente? ¿No puedes establecer en el milestone qué formato vas a usar, aparte de los habituales?

2024-04-07 10:15 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +                    println("Error: extensión de archivo no reconocida: ${e.message}")
Si no se lee la configuración, ¿se puede continuar? ¿Por qué capturas la excepción?

2024-04-12 07:10 UTC, JJ commented
Cierto, la pediste, perdona

2024-04-12 07:22 UTC, JJ requested changes
Lo importante en los ficheros de configuración no es tanto que puedas leer varios, sino que tu aplicación sea capaz de arrancar leyendo la configuración de ficheros con un nombre por omisión siguiendo un orden determinado. Primero busca un fichero, si no existe busca otro, y así sucesivamente.
Por eso tienes que tener bien claro cuál es el objetivo de lo que haces y ponerlo en el milestone, que es básicamente usar de forma indistinta diferentes ficheros de configuración que se usen de forma habitual. Y el desarrollador (que al fin y al cabo es un cliente) tiene que justificar su necesidad de usar varios formatos, en vez de uno solo.
El que se haga así en programas habituales es porque va a haber diferentes formas de pasar cosas como "secretos". Al parecer en Kotlin no se usan ni ficheros .env ni variables de entorno (aunque no tengo muy claro que no se usen variables de entorno).
Por eso la jerarquía habitual es
1. Se leen flags de línea de órdenes (no habitual en Kotlin, supongo)
2. Se leen ficheros con variables de entorno (no habitual en Kotlin, supongo)
3. Se leen variables de entorno (los ficheros de entorno se convierten en variables de entorno). *Esto* no lo estás haciendo y es el mecanismo habitual de pasar "secretos" (los secretos se incorporan al sistema de integración continua encriptados)
4. Se leen otros ficheros de configuración, en un formato que se decida (que puedes decidirlo tú).

Recuerda que *siempre* hay una justificación para hacer algo y *siempre* tienes que preguntarte el por qué.  Y en este caso, lo que debes entender es que hay que implementar un sistema de configuración que sea capaz de leer de diferentes fuentes, esencialmente fuentes "secretas" (de sistemas de CI) y fuentes "abiertas", que estén en el repo.
*Eso* es lo que hay que poner en el milestone, y eso es lo que hay que desarrollar en el issue, con lo que sea específico para Kotlin y para tu proyecto.

2024-04-12 07:22 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +    fun loadConfig(pathFile: String) {
¿Por qué no es esto parte del constructor? ¿Qué consigues cargando la configuración en dos pasos?

2024-04-12 07:22 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +incluso ficheros INI. Por lo tanto, al finalizar este hito se debería obtener un PMV, siendo este el proyecto
Considera incluir alguna referencia o enlace para esto.

2024-04-12 07:22 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +bibliotecas encontradas serían las siguientes, Apache Commons Configuration, Config de Lightbend, Config Magic,
Enlaces

2024-04-12 07:22 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +fuentes como JSON o YAML, pero pocas pueden leer de más de una de estas fuentes vistas; sin embargo, Config de
Enuncia *siempre* los criterios de aceptación de una o de otra antes de decir cuál vas a aceptar.

2024-04-12 07:22 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +respectivamente. Por ende cualquiera de estas dos bibliotecas puede ser escogida, pero Config de NetworkNT es una
Convendría que hubieras puesto antes un párrafo de cuales son los ficheros habituales de configuración y por qué tienes que dar soporte a dos o tres.
También en bibliotecas de configuración se habla de "jerarquía", es decir, en qué orden se leen.

2024-04-12 07:29 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +    fun loadConfig(pathFile: String) {
¿Pero sería buena idea que cada vez que quiera cargar una configuración se volviera a inicializar el objeto?

2024-04-12 07:31 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +incluso ficheros INI. Por lo tanto, al finalizar este hito se debería obtener un PMV, siendo este el proyecto
Sii hay una cita aun artículo en el que habla de las fuentes de configuración populares, no sé si te refieres a eso o a otra cosa

2024-04-12 07:31 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +bibliotecas encontradas serían las siguientes, Apache Commons Configuration, Config de Lightbend, Config Magic,
Enlaces a todas las bibliotecas, supongo, okay

2024-04-12 07:34 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +fuentes como JSON o YAML, pero pocas pueden leer de más de una de estas fuentes vistas; sin embargo, Config de
Si se me olvido especificar que escogería la que más fuentes populares pudiera leer

2024-04-12 07:47 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +respectivamente. Por ende cualquiera de estas dos bibliotecas puede ser escogida, pero Config de NetworkNT es una
Diría que está indicado arriba cuáles son los más populares, en el primer párrafo si no me equivoco. Eso sí, me ha faltado hablar de la jerarquía, también.

2024-04-12 07:51 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +    fun loadConfig(pathFile: String) {
¿tú qué crees?

2024-04-12 07:52 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +incluso ficheros INI. Por lo tanto, al finalizar este hito se debería obtener un PMV, siendo este el proyecto
No, a qué es un fichero Ini o Properties. ¿El tribunal va a saber qué son esas cosas?

2024-04-12 07:52 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +respectivamente. Por ende cualquiera de estas dos bibliotecas puede ser escogida, pero Config de NetworkNT es una
No, no se trata de eso. Lo he explicado un poco mejor en el comentario, creo.

2024-04-12 07:57 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +incluso ficheros INI. Por lo tanto, al finalizar este hito se debería obtener un PMV, siendo este el proyecto
Aa vale

2024-04-12 08:01 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +    fun loadConfig(pathFile: String) {
Si considero que no entendía que la idea era leer de varios ficheros, pero todos con los mismos datos, simplemente se usan distintas fuentes por si van fallando lecturas en la jerarquía. O al menos eso he pillado, todos tienen los mismos datos y se leen según cierta jerarquía, el primero en esta que no falle al leerse es el que se carga en la configuración. Así que si tendría sentido que se inicialice en cada lectura. Ya que va a ser lo primero en hacerse al iniciar la aplicación.

2024-04-16 06:47 UTC, JJ requested changes
Diría que ha mejorado, al menos conceptualmente, pero tienes que ser consciente de buenas prácticas a la hora de programar y aplicarlas en lo posible.

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +	envFilePath: String = "src/test/resources/configuration/configuracion.env",
Convencionalmente este fichero se llama simplemente `.env`. Y suele estar en el raíz. Y me da la impresión de que en el resto tampoco estás usando nombres estándar, incluyendo el hecho de que se llaman`configuracion` en español. Si les pones nombres por omisión, *usa* los nombres por omisión habituales.

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +	hoconFilePath: String = "src/test/resources/configuration/configuracion.conf"
Aparte, ¿no sería más fácil deducir el tipo de fichero simplemente por la extensión?

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            println("Configuracion yml cargada correctamente")
Uf, `println`...

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            successfully = true
¿Por qué pones esto? Si no se ha cargado correctamente, se levanta una excepción, ¿no?

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        return successfully
¿No debería devolver esto la configuración?

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +        Configurator.init("","","","",hoconFilePath)
Uf. ¿Te parece esto un interfaz razonable? ¿No se pueden usar parámetros con nombre en Kotlin para evitar esto? O simplemente usar un solo parametro, como te he indicado arriba.

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/test/resources/configuration/configuracion.conf
> +# Configuración básica
¿La codificación de este fichero es correcta?

2024-04-16 06:47 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        }else if (config.parseFile(File(envFilePath))){
Estás usando exactamente el mismo código independientemente del tipo de fichero.

2024-04-16 06:50 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            println("Configuracion yml cargada correctamente")
Aun no he introducido el segundo servicio, los cambiare por los logs

2024-04-16 06:51 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +	hoconFilePath: String = "src/test/resources/configuration/configuracion.conf"
Pero si se hace así entiendo que solamente le pasarías un fichero de manera que si ese falla no cargaría la configuración

2024-04-16 06:52 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            println("Configuracion yml cargada correctamente")
No es buena idea hacer print desde una subrutina nunca. Y la configuración es previa a los logs, recuerda que hay que usarla para configurarlos.

2024-04-16 06:53 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +	hoconFilePath: String = "src/test/resources/configuration/configuracion.conf"
Sólo se le pasa el fichero para test, entiendo. Trata de afinar bien la historia de desarrollador para que esté claro qué estás solucionando con este código y por qué.

2024-04-16 06:53 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            successfully = true
Okay, pues lanzaré simplemente una excepción

2024-04-16 06:54 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        return successfully
No entiendo qué me quieres decir, ya lo devuelve entonces entiendo que no debería devolverlo?

2024-04-16 06:56 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/configuration/configuracion.conf
> +# Configuración básica
Eso es un simple comentario

2024-04-16 06:57 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        }else if (config.parseFile(File(envFilePath))){
Claro, esta mal?

2024-04-16 07:03 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            println("Configuracion yml cargada correctamente")
Claro por eso este es el primer servicio anterior a los logs, pues quitaré los print solo los uso para depurar los test

2024-04-16 07:03 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        return successfully
Aunque estoy viendo [aquí](https://medium.com/@thejufo/enhancing-kotlin-performance-mastering-5-best-practices-4ff69be13e0c) que al parecer `apply`  debería usarse en ese sentido.

2024-04-16 07:04 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +        Configurator.init("","","","",hoconFilePath)
En este caso es para simular que los ficheros anteriores al .conf no funcionaran y debe cargar este

2024-04-16 07:04 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        }else if (config.parseFile(File(envFilePath))){
¿Y no será más fácil usar sólo un nombre de fichero? JConfig usa el mismo código, le da igual qué tipo de fichero sea.

2024-04-16 07:05 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +        Configurator.init("","","","",hoconFilePath)
¿Y te parece razonable eso?

2024-04-16 07:06 UTC, JJ commented on claqueta_tfg/src/test/resources/configuration/configuracion.conf
> +# Configuración básica
Mira como aparece esto en la pestaña "files" (que es la que deberías usar para revisar comentarios)
![Captura de pantalla de 2024-04-16 09-05-58](https://github.com/JoseJordanF/Claqueta/assets/500/a4506316-0273-498a-ac58-a9c84fb485fa)

2024-04-16 07:06 UTC, JJ commented on claqueta_tfg/src/test/resources/configuration/configuracion.yml
> +# Configuración básica
Este tiene el mismo problema.

2024-04-16 07:07 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +	hoconFilePath: String = "src/test/resources/configuration/configuracion.conf"
¿Qué necesita el desarrollador de este objeto?

2024-04-16 07:08 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +        Configurator.init("","","","",hoconFilePath)
> En este caso es para simular que los ficheros anteriores al .conf no funcionaran y debe cargar este.
> 
> Podría ponerlo de la siguiente forma: Configurator.init(propertiesFilePath="",envFilePath="",jsonFilePath="",ymlFilePath="",hoconFilePath)

¿O usar un solo argumento, ya que cómo se procesa el fichero no depende del tipo de fichero?

2024-04-16 07:10 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        return successfully
Voy a echarle un vistazo, aun así init() funciona como el constructor del objeto https://medium.com/@ranjeet123/init-block-in-kotlin-518b050cada1

2024-04-16 07:12 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +        Configurator.init("","","","",hoconFilePath)
¿Pero entonces, como lo hago, declaro variables internas en la función con los valores por defecto? Y solo le paso un archivo, aunque eso no garantice que sea ese archivo el que se vaya a abrir, luego solo tendría un test

2024-04-16 07:13 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/configuration/configuracion.conf
> +# Configuración básica
A vale las tildes, borraré el comentario

2024-04-16 07:14 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        }else if (config.parseFile(File(envFilePath))){
Sisi, pero si ese falla te quedas sin configuración, yo creía que tenía que poder cargar varios ficheros, como tú indicaste, primero prueba uno, si falla pasa al siguiente...

2024-04-16 07:14 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/configuration/configuracion.yml
> +# Configuración básica
los borro ahora mismo

2024-04-16 07:16 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +        Configurator.init("","","","",hoconFilePath)
Pero ¿qué variables internas? Prueba a usar un solo argumento, a ver si necesitas "variables internas"

2024-04-16 07:17 UTC, JJ commented on claqueta_tfg/src/test/resources/configuration/configuracion.conf
> +# Configuración básica
No es sólo el comentario, hay problemas en todo ese fichero. En otros ficheros, en los comentarios. Es un problema de codificación. Has copiado y pegado de un documento que usaba otro tipo de codificación del habitual (utf-16, o Latin1, en vez de UTF8)

2024-04-16 07:18 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        }else if (config.parseFile(File(envFilePath))){
De veras, tienes que especificar bien la historia de desarrollador y entender bien qué es lo que hace un objeto de configuración. ¿Cómo gestionas con este objeto los "secretos"? ¿Los has mencionado en la historia de desarrollador?

2024-04-16 07:28 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        return successfully
Pero en el object funciona de la misma manera

2024-04-16 07:31 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        return successfully
Si funciona de la misma manera, *tampoco* puede devolver un valor para indicar que ha funcionado correctamente. Si no funciona correctamente, levanta una excepción. Si funciona correctamente, cambia el estado del objeto. En todos los lenguajes, cuando se crea un objeto se devuelve ese objeto, no "true" si se ha creado correctamente. En Kotlin no creo que sea diferente.

2024-04-16 07:38 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/configuration/configuracion.conf
> +# Configuración básica
Pues probablemente

2024-04-16 07:45 UTC, JoseJordanF commented on claqueta_tfg/src/test/resources/configuration/configuracion.yml
> +# Configuración básica
Ya ya he visto el comentario de arriba

2024-04-17 16:04 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +    companion object{
Okay linkearé también el artículo que te pase

2024-04-17 16:09 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +            "src/test/resources/configuration/config.properties"
Okay

2024-04-17 16:17 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/config/ConfiguratorTest.kt
> +        val res = config.getConfig("SERVER_PORT")
Okay

2024-04-17 16:26 UTC, JJ requested changes
alguna cosa más que he visto.

2024-04-17 16:26 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +                instance.config.parseFile(File(path))
Por favor asegúrate de que se cumple la precedencia entre uno y otro método. Si hay alguna variable que ya tenga valor leído desde variables de entorno, aquí le cambiarías el valor rompiendo la precedencia.

2024-04-17 16:26 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        fun instance(path: String="src/test/resources/configuration/config.env"): Configurator {
El valor por efecto no puede ser el de los ficheros de variables de entorno, esos los tienes que leer *siempre* y con una precedencia específica. Usa el más habitual en programas en Java o Kotlin.

2024-04-17 16:32 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +        fun instance(path: String="src/test/resources/configuration/config.env"): Configurator {
Okay

2024-04-17 16:39 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +                instance.config.parseFile(File(path))
No parece un buen patrón, un bloque de código vacío. ¿No existe en Kotlin el patrón código or código? En todo caso, si niegas la expresión te ahorras el bloque de código vacío.

2024-04-18 15:06 UTC, JJ approved these changes
:clap: Al final las cosas van saliendo (y con menos de 100 comentarios :rofl: )

2024-04-18 15:06 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/config/Configurator.kt
> +            if (!instance.config.envVarFilter("CLAQUETA_")) {
Esto yo creo que se puede dejar directamente. ¿No hemos quedado que no se usan las variables de entorno?

2024-04-18 15:06 UTC, JJ commented on claqueta_tfg/src/test/resources/configuration/config.json
> +  "CLAQUETA_NAME": "Example configuration",
Esto ya no se usa, ¿no?

2024-04-18 15:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +dotenv y por último snakeyaml \footnote{\url{https://bitbucket.org/snakeyaml/snakeyaml/src/master/}} que cubre los
No creo que nadie lo mire, pero igual hay algún enlace mejor que el del repo

2024-04-18 15:06 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +De modo que la implementación de esta funcionalidad constara de una clase \begin{otherlanguage} {english}``\textit{\textbf{configurator}}''\end{otherlanguage}
Corrígelo con el nombre que le hayas llamado

2024-04-18 16:52 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +dotenv y por último snakeyaml \footnote{\url{https://bitbucket.org/snakeyaml/snakeyaml/src/master/}} que cubre los
Como en el repo viene toda la información, pensaba que sería lo más correcto, si encuentro algún enlace mejor lo cambiaré

2024-04-19 07:27 UTC, merged