Gestión del sistema de registro de la aplicación
JoseJordanF/Claqueta pull request #127
Opened 2024-04-24 16:59 UTC by JoseJordanF

En este PR se pretende establecer el segundo servicio esencial del M3, se discute porque son necesarios los logs y se discute que herramienta usar. Por la parte de código se añaden las dependencias necesarias y se crean los tests necesarios para demostrar el uso del sistema de logs:

(-closes #119)
(-closes #120)
(-closes #126)

2024-04-24 17:14 UTC, JJ requested changes
Aparte de lo dicho, debes afinar bien la historia de desarrollador para crear unos tests que comprueben si sucede correctamente o no. ¿Qué debe tener un log, aparte de lo que estás testeando, que realmente no comprueba nada? ¿No tendrás que comprobar que las secuencias ha sucedido en el orden correcto? 
Aparte, los diferentes niveles de log sirven para algo: los errores para errores, y demás. El log no tiene ningún sentido por si mismo, tiene sentido en el conjunto de la aplicación y dónde lo estés usando. Si hay un error, tendrás que logearlo y comprobar que se ha logeado correctamente, ¿no?

2024-04-24 17:14 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            val configFile = Configurator.instance().getConfig("CLAQUETA_LOGBACK_CONFIG")
No se deben usar nunca literales en el código; siempre se deben asignar a una constante.

2024-04-24 17:14 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +        fun instance(clazz: Class<*> = this::class.java): com.app.claquetaTfg.logs.Logger {
¿Este nombre de argumento sigue las mejores prácticas en Kotlin?

2024-04-24 17:14 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +class Logger {
¿No hereda de nada ni sigue un interfaz?

2024-04-24 18:48 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +class Logger {
Podría hacer que heredara de la propia Logger de slf4j

2024-04-24 18:54 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            val configFile = Configurator.instance().getConfig("CLAQUETA_LOGBACK_CONFIG")
Lo añado también como argumento para el constructor, pero le pongo ese valor por defecto¿?

2024-04-25 08:47 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +        fun instance(clazz: Class<*> = this::class.java): com.app.claquetaTfg.logs.Logger {
Un valor por defecto también es un literal.

2024-04-25 12:13 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +        fun instance(clazz: Class<*> = this::class.java): com.app.claquetaTfg.logs.Logger {
Pero lo malo es que si no pongo valor por defecto tendría que estar pasándoselo cada vez que llame a la instancia

2024-04-25 12:16 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +        fun instance(clazz: Class<*> = this::class.java): com.app.claquetaTfg.logs.Logger {
Lo que te estoy diciendo es que no uses nunca "valor tocho que es constante", sino

```
ESTA_CONSTANTE_SIRVE_PARA_ESTO = "valor tocho que es constante"
```
https://dev.to/ruben_alapont/magic-numbers-and-magic-strings-its-time-to-talk-about-it-ci2#:~:text=The%20most%20effective%20way%20to,the%20values%20have%20clear%20meanings.

Dev.to también es tu amigo.

2024-04-25 12:58 UTC, JJ requested changes
Ha mejorado, pero sería conveniente que conocieras y aplicaras las buenas prácticas habituales, en especial los principios SOLID.

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +     var logger = Logger.instance(this::class.java,"CLAQUETA_LOGBACK_CONFIG")
¿Es esa cadena una constante? ¿Se debería por tanto declarar como tal?

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                    logger.info("El usuario $userAuthor a creado una critica de la pelicula ${films[filmId]!!.title}")
Ay esas faltas de ortografía... 
Por otro lado, los logs no son una historia, se supone que se tienen que procesar automáticamente.

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
>              throw RuntimeException("Ya escribiste una reseña de esta pelicula")
Recuerda que conviene que las excepciones no sean genéricas, sino que se definan junto con las clases con las que trabajas. El objetico de las excepciones es identificar el error y poder, en la medida de lo posible, recuperarlo. Más en concreto, en este caso si "burbujea" hasta un API, tendrías que devolver un código de estado apropiado a lo que ha ocurrido (un 4xx)

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            System.setProperty("logback.configurationFile", configFile!!)
El objetivo de usar constantes en vez de literales es que el trabajo sea sencillo de refactorizar. Las constantes están en la parte alta del módulo, y tienen nombres apropiados. En este caso, imagínate que cambias de logBack a cualquier otra cosa. ¿Cuantos literales de este estilo tendrías que cambiar?

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            instance!!.logInMemory = mutableListOf()
El principio de responsabilidad única dice que cada clase, función, módulo, debe hacer una cosa y solo una. Si se usa para un logger, es para un logger. Si se usa para hacer un log en memoria, debe hacer un log en memoria. Si no, estás metiendo en memoria cosas que pueden no ser necesarias. O declarando un fichero para algo que tampoco lo es.

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +	System.setProperty("CLAQUETA_LOGBACK_CONFIG","src/main/resources/configLogB.xml")
¿Qué pasaría si tienes que cambiarle el nombre a esto? ¿Cambias 3 o más cadenas en n ficheros diferentes? ¿Y si defines una constante que tenga ese valor?

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            classType: Class<*> = this::class.java,
Sabes que este `this` no es el mismo `this` que estás usando cuando lo invocas, ¿no?
Tampoco entiendo muy bien por qué hace falta esto. ¿Cada clase tiene un log diferente?

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            instance!!.logger = LoggerFactory.getLogger(classType)
¿para qué se le pasa el tipo de clase para crear la instancia de logger? ¿Hay tantas instancias como clases entonces?

2024-04-25 12:58 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        assertTrue( sizeLogInMemoryAfter-sizeLogInMemoryBefore == 3 )
¿Te parece que el tamaño del log es lo único que hay que probar?

2024-04-25 13:21 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +     var logger = Logger.instance(this::class.java,"CLAQUETA_LOGBACK_CONFIG")
Okay miraré como la declaro para que sea accesible por todo fichero que la necesite

2024-04-25 13:22 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                    logger.info("El usuario $userAuthor a creado una critica de la pelicula ${films[filmId]!!.title}")
Otras para matarme

2024-04-25 13:24 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
>              throw RuntimeException("Ya escribiste una reseña de esta pelicula")
Okay

2024-04-25 13:28 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            instance!!.logInMemory = mutableListOf()
Pero si solo estoy inicializando la lista en el constructor, hago una clase solo para añadir logs a memoria?, y otra para el logger?

2024-04-25 13:29 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +	System.setProperty("CLAQUETA_LOGBACK_CONFIG","src/main/resources/configLogB.xml")
Si añadiré la constante, al menos 3 veces uso la misma cadena

2024-04-25 13:34 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/Logger.kt
> +            instance!!.logger = LoggerFactory.getLogger(classType)
No simplemente se actualiza el valor, es por la biblioteca para que en el formato del log se rellene el campo del nombre donde se ha llamado al Logger. Por ejemplo:
14:10:03.519 [Test worker] INFO  c.a.c.d.UserFilmReviewManagerTest - El usuario josejordan a creado una critica de la pelicula Toy Story

En este mensaje este campo "c.a.c.d.UserFilmReviewManagerTest" si no se le indica no se puede inicializar el logger.

2024-04-25 13:35 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        assertTrue( sizeLogInMemoryAfter-sizeLogInMemoryBefore == 3 )
No es el tamaño de logs es si se han añadido 3 logs a memoria, para comprobar que se han recogido los logs esperados

2024-04-25 15:39 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        assertTrue( sizeLogInMemoryAfter-sizeLogInMemoryBefore == 3 )
En todo caso, siempre es lo mismo, tienes que comprobar que la historia de desarrolador se cumpla

2024-04-25 16:46 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        assertTrue( sizeLogInMemoryAfter-sizeLogInMemoryBefore == 3 )
Pero para mí se cumple, eso me demuestra que se crean los logs cuando se producen acciones en la app. Entonces no entiendo que está mal

2024-04-25 20:18 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        assertTrue( sizeLogInMemoryAfter-sizeLogInMemoryBefore == 3 )
Te refieres a comprobar que el propio log este correcto, el nivel, la clase desde que se llamo...

2024-04-26 07:57 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        assertTrue( sizeLogInMemoryAfter-sizeLogInMemoryBefore == 3 )
Me refiero a que los tests deben comprobar comportamientos y comprobar que se ha solucionado lo que dice en #126. ¿De qué forma esto se corresponde a lo que dice en esa historia de desarrollador?

2024-04-26 17:32 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        assertTrue( sizeLogInMemoryAfter-sizeLogInMemoryBefore == 3 )
Claro, esto lo hace a través de los logs, por eso yo estaba comprobando que para un comportamiento concreto de la app o del usuario se crearan los pertinentes logs. Quizás deba comprobar que se crean en la secuencia perfecta para describir el comportamiento que están monitoreando. No sé si es a esto a lo que te refieres.

2024-04-29 09:31 UTC, JJ requested changes
En general, está correcto, aunque parece que hemos empezado a ampliar el ámbito del PR en la dirección de la gestión de errores, por ejemplo.
En todo caso, hay dos cosas que quedan por resolver
* Si `getLogger` genera una instancia cada vez que se le llama con un nombre de clase diferente y para qué usa ese nombre de clase. Si lo usa solo para un prefijo, puede ser conveniente, mantenerlo, pero quizás se quiera usar algún otro prefijo en vez del nombre de la clase. Si lo usa para algo más profundo, como conversión o introspección, habrá que usarlo para no tener que hacer conversiones a mano, por ejemplo. Pero si se trata de instancias diferentes y *quieres* que haya prefijo desde dónde se está haciendo, tienes que ver la forma de gestionarlo.
* No has hecho la refactorización para no repetir literales.

2024-04-29 14:43 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                        	"-user= $userAuthor\n" +
¿Está en la historia de desarrollador?
Si es así, una vez más, ¿no sería conveniente usar una función en vez de repetir código?

2024-04-29 17:53 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                "Review duplication event:\n" +
Puedo usar el toString del dataClass

2024-04-30 08:59 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                        	"-user= $userAuthor\n" +
Pero es que cada log vas a querer mostrar x datos, objetos diferentes, datos diferentes... No se me ocurre como poder hacerlo, ahora lo estoy intentando con una función que me devuelve en formato JSON un objeto, pero me devuelve evidentemente todos los atributos, pero puede que no los necesite para otros logs relacionados. Entonces me procede a explotar la cabeza.

2024-04-30 09:09 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                        	"-user= $userAuthor\n" +
No trates de resolver el problema equivocado. Plantea bien el problema y resuélvelo.

2024-05-01 12:07 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                        	"-user= $userAuthor\n" +
No se le estoy dando muchas vueltas al tema del formato y tal

2024-05-02 10:06 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
>  import kotlin.test.assertEquals
Al principio me dijiste que no usara el *, pero ahora supongo que es el momento de usarlo

2024-05-02 10:10 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
>  import kotlin.test.assertEquals
El * no lo dejan pasar los linters, pero usar import a,b,c from x como sea en Kotlin sí se puede hacer, ¿no?

2024-05-02 10:22 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
>  import kotlin.test.assertEquals
Supongo, ahora lo comprobare

2024-05-02 10:28 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +	logger = Logger.instance(logConfig)
Nada, ha sido mal entendimiento por mi parte, no estaba tratando logger como una interfaz

2024-05-02 10:30 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        var dataLog = ManagerLogger.dataLogs(
Pero es que no termino entender que tengo que testear de los test, ya testeaba que se creaban y no es suficiente, por lo que creía que era necesario comprobar que los datos de los test eran correctos. Pero parece que no, luego no sé qué tengo que testear más del log aparte de que se ha creado

2024-05-02 10:32 UTC, JJ requested changes
Por favor, ten en cuenta esto también.

2024-05-02 10:32 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +     var logger = Logger.instance(logConfig)
Si lo creas desde aquí en vez de inyectarlo, es imposible que uses un logger diferente dependiendo de la fase de despliegue de la aplicación (si es en test, o en staging, o lo que sea). logConfig es una constante también, así que sigue siendo imposible que lo hagas a través del cambio del valor de una variable. Puedes por supuesto usar esto como valor por omisión, pero no como única posibilidad.

2024-05-02 10:32 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                    ManagerLogger.createLog(trueFilm)
Una de las cosas esenciales, y que hay que seguir desde el principio, es que toda aportación de código debe añadir valor al cliente, y eso se ve en el mensaje de commit que debe siempre apuntar a un issue, y este a una HU. En este caso lo has añadido con 6eeb55f. Más o menos parece que corresponde a lo que comenté de que debías evitar repetir código usando una función que tome un objeto y lo formatee para el log.
Aquí, sin embargo, hay dos problemas
1. El nombre de todo: ManagerLogger parece que es un gestor de logs, y es un objeto. ¿Hace falta un objeto para formatear cadenas? `createLog` ¿es más adecuado que `formatLogEntry`? De hecho, si hubieras llamado así a la función, inmediatamente habría quedado claro que el `ManagerLogger` no tenía mucho que hacer.
2. Este es un log de `debug`. Con este tipo de log, ¿qué vas a hacer? Si vas a mirar valores, por ejemplo, o hacer búsquedas, ¿no sería mejor que se serializara el objeto en un formato determinado en vez de una cadena?

Mira, una estudiante del máster me decía que "Esto de programar es un calentaero de cabeza más grande que el escribir el código". Tienes que intentar calentarte la cabeza antes de escribir el código.

2024-05-02 10:32 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/ManagerLogger.kt
> +        return logInMemory
Uno de los principios SOLID más importantes es el SRP: Single Responsibility Principle. (La "S" de Solid") Esta clase, ¿qué hace? Como dices aquí 51333b4, separar el logger de la administración es un objetivo loable. Pero para empezar, en ese commit tampoco hay ningún issue al que se apunte. Si no lo hay, no se puede saber que está solucionando. Para seguir, no puedes separar eso (algo que no tengo muy claro que haga tampoco) para juntar la administración de un log en memoria (que no sigue el mismo interfaz que el log en fichero) con ¿el formateo de mensajes de log?

2024-05-02 10:39 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
> +        var dataLog = ManagerLogger.dataLogs(
Pues conviene que lo entiendas, porque si no lo entiendes no vas a ser capaz de solucionar el problema del desarrollador correspondiente.

2024-05-02 10:57 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +     var logger = Logger.instance(logConfig)
Creo que se esta juntando lo de el classType con esto. Aun así no entiendo, por qué no sé donde debería inyectarlo

2024-05-02 11:02 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +                    ManagerLogger.createLog(trueFilm)
Okay, te aseguro que me caliento la cabeza. Por otra parte el objeto esta serializado, de hecho si miras el código de ManagerLogger que cambiaré a LoggerManager, existe una función dataLog que te da en un mapa el objeto JSON para que puedas tratar los datos específicos de ese log

2024-05-02 11:03 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +     var logger = Logger.instance(logConfig)
Pues una vez más, convendría que entendieras el concepto de inyección de dependencias, en el contexto de los principios SOLID y aplicados en concreto a los logs. Mira por ejemplo [este material](https://jj.github.io/curso-tdd/temas/inversi%C3%B3n.html) de un curso que di; puedes consultar también la presentación y el resto del curso (donde habla, por ejemplo, de objetos de test)

2024-05-02 11:05 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/ManagerLogger.kt
> +        return logInMemory
Si estoy desvistiendo un santo para vestir a otro. Okay, pero no se me estoy perdiendo porque según lo dicho, voy a tener que hacer 3 ficheros cada uno para una cosa el log, el manager de los log, y el formateador de los logs

2024-05-02 11:13 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/logger/ManagerLogger.kt
> +        return logInMemory
No, vas a tener que formular los problemas correctamente y tratar de resolverlo de la mejor forma posible tras pensar un rato y aplicando buenas prácticas como los principios SOLID.
Porque no veo que este "loggermanager" gestione nada. Hace dos cosas: tiene un logger en memoria,  formatea. ¿Dónde está la gestión de loggers? ¿Por qué necesitas un gestor de loggers, si el logger es un singleton?

2024-05-02 11:14 UTC, JoseJordanF commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
>  import kotlin.test.assertEquals
Pues parece que no, no hay forma de hacer eso en Kotlin, lo único es usar el *

2024-05-02 11:31 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
>  import kotlin.test.assertEquals
Eso parece https://discuss.kotlinlang.org/t/importing-multiple-entries-in-a-single-line/3860/4

2024-05-02 11:32 UTC, JJ commented on claqueta_tfg/src/test/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManagerTest.kt
>  import kotlin.test.assertEquals
Resuelve, por favor.

2024-05-13 07:49 UTC, JJ approved these changes
Salvo algunos detalles, yo creo que ya está completo. :+1:

2024-05-13 07:49 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +            throw UserAlreadyExistsException("This user already exists")
Por favor, no te olvides de esto. Aunque no es para este PR, deberías abrir esa HD y resolver.

2024-05-13 07:49 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +            throw ReviewDuplicateException("You have already written a review of this movie")
¿No crees que el error lanzado debería tener la misma información que el log? Imagínate que esa excepción finalmente la lanzas al usuario, ¿cómo sabe cuál es "this"?
(En ese sentido, también tienes que clarificar las historias de usuario, ¿hablan inglés o no?)

2024-05-13 07:49 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +La implementación de esta funcionalidad será como la anterior, ya que también será una clase singleton llamada
¿El tribunal sabe qué es un singleton? ¿No podrías referenciar aquí el libro de patrones de programación?

2024-05-13 07:51 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +            throw ReviewDuplicateException("You have already written a review of this movie")
Si si, pero no añadí los cambios porque no son para este PR, como tú añadiste la HD lo pensaba hacer en el PR en que corrija algunas cosas para que la app sea más eficiente como hablamos

2024-05-13 07:54 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +La implementación de esta funcionalidad será como la anterior, ya que también será una clase singleton llamada
Como lo explico arriba por qué también lo hice para la configuración hay un par de enlaces de referencia, uno de ellos es este (https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/patron-singleton/) en el que se explica que es el patrón singleton

2024-05-13 07:55 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +            throw ReviewDuplicateException("You have already written a review of this movie")
Todo lo que hagas tiene que estar respaldado por una HU o HD, incluso el idioma. En todo caso, resuelve indicando la HU o HD que hayas creado .

2024-05-13 07:56 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +La implementación de esta funcionalidad será como la anterior, ya que también será una clase singleton llamada
A muchos #1 les gustan las referencias de verdad en libros. Y más si son libros que recomiendan en su asignatura. En algunos casos, #1 han preguntado al estudiante por qué no hay más referencias, así que cualquier oportunidad que tengas de mencionar una referencia _de verdad_, úsala.

2024-05-13 14:45 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/domain/UserFilmReviewManager.kt
> +            throw ReviewDuplicateException("You have already written a review of this movie")
Okay

2024-05-13 14:48 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +La implementación de esta funcionalidad será como la anterior, ya que también será una clase singleton llamada
Vale, pues buscaré más referencia de “verdad”, empezando por el patrón singleton que seguro que hay bastantes en libros.

2024-05-15 18:18 UTC, merged