Despliegue de la API para el acceso a recursos
JoseJordanF/Claqueta pull request #156
Opened 2024-06-13 16:48 UTC by JoseJordanF

En este PR se quiere desplegar la API para ello se ha diseñado una API para el acceso a los distintos recursos, se han diseñado las rutas hacia estos y se ha desplegado finalmente la API

(-closes #137)
(-closes #154)
(-closes #155)

2024-06-17 06:28 UTC, JJ requested changes
Me gustaría ver este PR, como todos, un poco más atómico: elección de la biblioteca usada para el API REST y la documentación por un lado, el resto por otro.  Si no corremos el riesgo de hacer un gran PR difícil de aceptar. Ya de por sí es trande.

2024-06-17 06:28 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/deployment/ClaquetaService.kt
> +        logger.log("Reviews affiliated to an id are requested.", arrayOf(id as String))
Deberías usar introspección para loguear el nombre de la función. Poner texto no parece que sea muy eficiente.
En algunos casos se pueden usar decoradores, o "aspect-oriented programming", en segunda refactorización. Por lo pronto, simplemente no uses palabras para describir algo que tiene una definición precisa.

2024-06-17 06:28 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\section{M6: Despliegue de la API}
Esto no se llama despliegue, sino diseño.

2024-06-17 07:48 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/deployment/ClaquetaService.kt
> +        logger.log("Reviews affiliated to an id are requested.", arrayOf(id as String))
(fc4228ad6ceafd31674dd2605155967a943ecab3)

2024-06-17 07:55 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\section{M6: Despliegue de la API}
(03590fd72aacc00abda78194478fba6100a4bfb4)

2024-06-17 11:14 UTC, JJ requested changes
Sobre el código no tengo mucho que decir, salvo que te asegures que pasa bien los tests y que has cubierto las historias de usuario. La documentación necesitaría otra vuelta, y también tendrías que añadir qué buenas prácticas has seguido en el diseño de las rutas, que la mayoría de #1 serán de "una ruta REST es una llamada a función"

2024-06-17 11:14 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\section{M6: Diseño de la API}
Un milestone nunca puede tener como resultado un diseño, sino un producto mínimamente viable.

2024-06-17 11:14 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +En este hito se pretende llevar a cabo el diseño de la API y su despliegue en local para poder acceder a todos
No estás haciendo el despliegue en local, sólo el testeo de las rutas. El despliegue es otra cosa (y probablemente debería ser otro milestone)

2024-06-17 11:14 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +curva de aprendizaje empinada, que sea modular\cite{modularSoft} para velar que su implementación sea ligera,
Empinada es chunga. Lo que buscas es lo contrario.

2024-06-17 11:14 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Ktor está guiada para aplicaciones ligeras y escalables, además el uso de Spring Boot es más complejo que el de
Como siempre, tienes que poner
* Criterios de búsqueda
* Opciones disponibles
* Criterios objetivos para poner uno u otro.

En este caso además es especialmente necesario, porque es poco probable que conozcan otra cosa que Spring Boot.

2024-06-17 11:16 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\section{M6: Diseño de la API}
Okay cambiaré el título

2024-06-17 11:16 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +En este hito se pretende llevar a cabo el diseño de la API y su despliegue en local para poder acceder a todos
Okay okay

2024-06-17 11:19 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +curva de aprendizaje empinada, que sea modular\cite{modularSoft} para velar que su implementación sea ligera,
No sabía que poner y al buscarlo para asegurarme di con esto https://es.wikipedia.org/wiki/Curva_de_aprendizaje puede que los ejes estén invertidos, luego en la de wikipidea empinada significa que aprendes mucho en poco tiempo.

2024-06-17 11:22 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +curva de aprendizaje empinada, que sea modular\cite{modularSoft} para velar que su implementación sea ligera,
No, significa que tienes que ascender esa cuesta y que cuesta mucho trabajo.

2024-06-17 11:24 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Ktor está guiada para aplicaciones ligeras y escalables, además el uso de Spring Boot es más complejo que el de
Vale, mi duda aquí seria, ¿cuál de los tres puntos faltaría? Es decir, establezco los criterios, presento en este caso dos opciones y escojo Ktor porque su curva de aprendizaje es mejor

2024-06-17 11:41 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +curva de aprendizaje empinada, que sea modular\cite{modularSoft} para velar que su implementación sea ligera,
Okay, pues entonces era como lo entendía al principio

2024-06-18 09:22 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +curva de aprendizaje empinada, que sea modular\cite{modularSoft} para velar que su implementación sea ligera,
([2ddf0d1](https://github.com/JoseJordanF/Claqueta/pull/156/commits/2ddf0d1d2b98d7a6b00f4a735dd543ffa2240d6a))

2024-06-18 09:23 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +En este hito se pretende llevar a cabo el diseño de la API y su despliegue en local para poder acceder a todos
([2ddf0d1](https://github.com/JoseJordanF/Claqueta/pull/156/commits/2ddf0d1d2b98d7a6b00f4a735dd543ffa2240d6a))

2024-06-18 15:18 UTC, JJ approved these changes
A estas alturas, seguir las buenas prácticas en REST es sólo conveniente, pero no necesario. Si tienes tiempo hazlo, sobre todo documenta lo que estás haciendo, si  no pues nada.

2024-06-18 15:18 UTC, JJ commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/deployment/plugins/Routing.kt
> +            get("/{idUser}/recommendations") {
Si yo entiendo bien como está organizado esto, para la recomendación del usuario 1 la ruta sería /users/1/recommendations.
El problema es que el interfaz REST se organiza en torno a URIs. Todo lo relativo al usuario 1 tendría que estar en /user/1 Usar el singular para identificar recursos también es una buena práctica. Usar POST sobre `/users'  sí sería correcto, para obtener un URI de un usuario.

2024-06-18 16:08 UTC, JoseJordanF commented on claqueta_tfg/src/main/kotlin/com/app/claquetaTfg/deployment/plugins/Routing.kt
> +            get("/{idUser}/recommendations") {
Okay lo cambiaré por /user/1 , no me había dado cuenta de eso

2024-06-19 07:41 UTC, merged