Redaccion de Historias de Usuario y reformulación de objetivos
JoseJordanF/Claqueta pull request #20
Opened 2023-05-30 08:39 UTC by JoseJordanF

En este PR se pretende resolver estos dos issues centrados en las historias de usuario y por consecuencia en la formulación de los objetivos, ya que estos deben reflejar la solución a los problemas de los usuarios en sus historias

- Incidir en los aspectos sociales en las historias de usuario, para formular los objetivos (closes #15)
- Reformular los objetivos de manera que sean específicos, medibles y alcanzables. Y que sean objetivos del usuario que quiere resolver un problema (closes #18)

2023-05-30 10:27 UTC, JJ requested changes
1. Tienes que entender bien el concepto de historia de usuario. Mira [este artículo](https://www.linkedin.com/pulse/comenzando-con-un-trabajo-fin-de-gradom%C3%A1ster-%C3%A1gil-juan-j-merelo/?originalSubdomain=es) donde explico cómo empezar un TFG usándolas.
2. Los objetivos son también muy importantes, tienen que emanar de las historias de usuario, pero lo importante es que deben ser comprobables y alcanzables. También [aquí](https://jjmerelo.medium.com/c%C3%B3mo-formular-buenos-objetivos-en-un-trabajo-7e68abf10028) cuento como hacerlo.

Lo principal es que tienes que ser capaz de formular claramente el problema o problema que quieres resolver, *no* lo que quieres hacer. Todo proyecto parte de tratar de encontrar la solución de un problema.

2023-05-30 10:27 UTC, JJ commented on doc/bibliografia.bib
> +	howpublished = {\url{https://www.ibm.com/mx-es/analytics/machine-learning}}
Si es un URL, es mejor que simplemente pongas el enlace en pie de página. Reserva esto para artículos publicados en revistas o libros. Que, pro cierto, sería mejor que esta referencia fuera un libro.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +A lo largo del tiempo, estos críticos han ayudado en gran medida a la industria cinematográfica
Los reformateos es mejor que los mantengas fuera de los PR, porque añaden ruido y hacen más difícil ver exactamente qué hay que corregir.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H6 - cinéfilo} Este otro usuario también tiene un problema con las críticas, en este caso con el orden. Le gustaría ordenar las críticas no solo en orden cronológico, sino también p
Me parece que estás descendiendo demasiado a detalle aquí. En particular, todas las historias de usuario del cinéfilo podrían ser una sola.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H1 - cinéfilo} Como apasionado del cine necesita un espacio en el que compartir su opinión y socializar con otros amantes del cine como lo es él. Siendo así un punto de encuentro.
No es realmente una historia, porque no dice claramente qué problema resuelve tener el sitio. Piensa que un sitio de alojamiento de páginas web o un blog directamente resolverían esta historia de usuario sin ninguna otra necesidad.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H2 - usuario medio} Como usuario que le gusta disfrutar del cine y las series de vez en cuando, necesita un lugar gracias al cual pueda decidir si ver o no cierto contenido. Ya que
Siempre que crees una historia de usuario, piensa en el problema que expresan, y cómo lo vas a resolver. Aquí el problema que se trasluce es asegurar la *realidad* y la *fiabilidad* de las críticas, no veo ningún otro. ¿Ese es el problema que quieres resolver? 
Mira también el error de "los" más reales.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H3 - crítico} Al igual que en la historia anterior, este usuario necesita que las reseñas sean fiables y reales. Ya que perjudican su trabajo y su repercusión. Y existen usuarios qu
¿Por qué necesita un crítico que sean fiables y reales? También si es "al igual de" es la misma historia de usuario. Las historias de usuario son herramientas que sirven para empezar a desarrollar código, y provienen de la empatización con los posibles clientes. No acumules HUs para llegar a un mínimo.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H4 - aficionado de las series} Un usuario amante del cine también lo suele ser de las series, al igual que este usuario estará cansado de que en las aplicaciones de reseñas se exclu
No me parece relevante ni algo que vaya a dar tiempo de hacer.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H5 - cinéfilo} Este usuario a la hora de ver sus reseñas se irrita porque no puede agrupar sus reseñas por sagas. De modo que las críticas referentes a las películas de la misma sag
NO entiendo muy bien este problema tampoco. ¿Por qué quiere ver todas las críticas en la saga juntas? ¿Quiere comparar sagas?

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ1} Diseñar y desarrollar un espacio software en el que un amante del cine pueda compartir sus reseñas y resguardarse socialmente. Convirtiéndose esta solución en un punto de encu
Los objetivos siempre están en el espacio del problema. El objetivo es que el usuario pueda hacer algo determinado, o un tipo de usuario pueda hacer algo determinado. No es nunca "diseñar y desarrollar". Eso es lo que vas descubriendo tú que tienes que hacer.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ2} Diseñar y desarrollar un sistema de reseñas equilibrado, objetivo y fiable. Ayudando a los usuarios en la toma de decisiones respecto al consumo de contenido. Dándole calidad
Igual que arriba. El objetivo es que el usuario pueda hacer algo, o que unos usuarios quieran hacer algo.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ3} Añadir a la solución no solo contenido cinematográfico, sino también series. Haciendo que los amantes de las series también encuentren su espacio donde socializar.
"añadir" es una tarea, no un objetivo. Los objetivos son cosas que va a poder hacer el usuario

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ4} Desarrollar un sistema por el cual puedas crear listas/grupos de reseñas sobre las películas que prefieras, agrupándose en sagas si es que seleccionas varias películas de la m
Si no está claro el problema que resuelve, no lo incluyas.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ5} Desarrollar un sistema para ordenar las críticas no solo las propias, sino las de usuarios comunes en las películas que consumas. Pudiendo ordenarlas en orden cronológico o se
Cómo aparezcan las pelis o reseñas es un detalle de implementación. No es un objetivo.

2023-05-30 10:27 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ6} La solución diseñada deberá ser accesible por todo usuario descrito en este capítulo, de modo que será de fácil acceso y de uso sencillo, teniendo en cuenta las capacidades de
Esto es algo que se debe intentar en todo desarrollo ágil, y va implícito en el desarrollo.

2023-06-01 22:27 UTC, JoseJordanF commented on doc/bibliografia.bib
> +	howpublished = {\url{https://www.ibm.com/mx-es/analytics/machine-learning}}
Bien buscaré la referencia en algún libro

2023-06-01 22:29 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +A lo largo del tiempo, estos críticos han ayudado en gran medida a la industria cinematográfica
De acuerdo no añadiré los saltos de línea en los próximos PRs

2023-06-01 22:30 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H6 - cinéfilo} Este otro usuario también tiene un problema con las críticas, en este caso con el orden. Le gustaría ordenar las críticas no solo en orden cronológico, sino también p
Vale, es que me pareció que era mejor separarlo para contemplarlo a la hora de formular los objetivos, pero bueno, una historia de usuario puede acarrear varios objetivos.

2023-06-01 22:31 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H1 - cinéfilo} Como apasionado del cine necesita un espacio en el que compartir su opinión y socializar con otros amantes del cine como lo es él. Siendo así un punto de encuentro.
Especificaré más porque debe ser este tipo de aplicación de reseñas

2023-06-01 22:33 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H2 - usuario medio} Como usuario que le gusta disfrutar del cine y las series de vez en cuando, necesita un lugar gracias al cual pueda decidir si ver o no cierto contenido. Ya que
Ahí en realidad quería reflejar el problema de no disponer de un sitio para resolver la toma de decisiones, pero lo junté un poco con la siguiente historia de usuario

2023-06-01 22:36 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ6} La solución diseñada deberá ser accesible por todo usuario descrito en este capítulo, de modo que será de fácil acceso y de uso sencillo, teniendo en cuenta las capacidades de
Si está implícito, no debería ser un objetivo entiendo

2023-06-01 22:39 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H3 - crítico} Al igual que en la historia anterior, este usuario necesita que las reseñas sean fiables y reales. Ya que perjudican su trabajo y su repercusión. Y existen usuarios qu
Vale, dispondré de HUs únicas

2023-06-01 22:42 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{H5 - cinéfilo} Este usuario a la hora de ver sus reseñas se irrita porque no puede agrupar sus reseñas por sagas. De modo que las críticas referentes a las películas de la misma sag
Por comodidad según el usuario, para tener mayor orden supongo en películas que estén relacionadas como las de las sagas.

2023-06-01 22:43 UTC, JoseJordanF commented
De acuerdo JJ, espero resolver todos los problemas, este finde. Muchas gracias por dedicarme tu tiempo

2023-06-02 06:27 UTC, JJ commented
> De acuerdo JJ, espero resolver todos los problemas, este finde. Muchas gracias por dedicarme tu tiempo

Faltaría más, para eso estamos.

2023-07-08 11:40 UTC, JoseJordanF commented
En el último commit cambio las HU y los objetivos según hablamos en la tutoría.

2023-07-17 10:54 UTC, JJ requested changes
Perdona ante todo la tardanza; en junio le di prioridad al resto de los TFGs que iban a presentar en esas fechas y que estaban un poco más avanzados. Ya presentan este mes y trataré de darle un empujón en estos 15 días antes de las vacaciones.

2023-07-17 10:54 UTC, JJ commented on doc/bibliografia.bib
> +
Alguna forma de encontrarlo o como ha sido publicado.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/01_introduccion.tex
>  preguntas '¿qué pensaste?' Una reseña de cine es una respuesta a una experiencia compartida de la
Creo que a LaTeX no le gustan estas comillas.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +CRITICISM}''\end{otherlanguage}\cite{3BrothersArticle}\footnote{\url{https://3brothersfilm.com/blog/2018/7/23/7rnnqs20722u62gz2hhwmrmwar1ut4}}. (el título del artículo y futuros términos en inglés se
Después de punto siempre es mayúsculas, aunque en vez de paréntesis sería mejor una nota a pie de página.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como cinéfilo, quiero poder acceder a reseñas detalladas y fiables, también a críticas de películas escíticas por expertos y críticos de cine para obtener una perspectiva más profunda y objetiva de l
Recuerda, como hablamos en la tutoría, que diferentes historias de usuario requieren milestones o productos diferentes y a menudo una lógica de negocio diferente.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como aficionado al cine, quiero poder buscar películas por género y recibir recomendaciones personalizadas para descubrir nuevas películas que se ajusten a mis gustos. También como aficionado al cine
Buscar ya se puede hacer con cualquier buscador. Lo que tienes que decir no es lo que quiere buscar, sino lo que quiere encontrar. También di recomendaciones personalizadas en base a qué. De las tres cosas que dices, sólo una está enfocada a un usuario determinado. El resto podrían ser visitantes casuales a un sitio; las películas populares lo serán independientemente del usuario, y "buscar por género" también. Si no son específicas de un usuario, no son historias de *este* usuario.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como cinéfilo, quiero poder acceder a reseñas detalladas y fiables, también a críticas de películas escíticas por expertos y críticos de cine para obtener una perspectiva más profunda y objetiva de l
Además, no digas lo que quiere hacer, sino lo que quiere conseguir. Si no dices por qué quiere acceder a reseñas, es imposible que las cualifiques como más o menos detalladas o más o menos fiables. Trata de evitar también términos que sea difícil convertir en requisitos técnicos: "perspectiva más profunda (?) y objetiva (?)"
Recuerda también lo que hablamos sobre esto en la tutoría. En todo caso, las historias de usuario no dicen lo que quieren hacer (o lo que tú quieres que haga) sino lo que quieren conseguir.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como crítico de cine, quiero tener la posibilidad de publicar mis reseñas y opiniones sobre películas en una plataforma para llegar a un público más amplio y generar discusiones. Como crítico, tambié
¿Por qué quiere publicar reseñas?
Recuerda que toda historia de usuario tiene que tener un problema que resolver. "Publicar reseñas" no es un problema, y si antecedes esta solución al problema, puedes acabar con una solución que no resuelva nada, o que simplemente se resuelva por su existencia: cualquier sitio que permita publicar reseñas, como un blog, lo permitirá. Si además tiene estadísticas, mejor. 
En *design thinking*, una de las fases imprescindibles es empatizar; si no eres capaz de empatizar con un cliente y ver lo que quiere, es muy complicado sacar de ahí una historia de usuario y posteriormente los problemas que hay que resolver.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +acaba de plantear en este capítulo. Haciendo uso de las historias de usuario descritas en este capítulo.
Aquí no va punto.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ1} Proporcionar a los usuarios la capacidad de descubrir películas que se ajusten a sus gustos y preferencias.
Los objetivos siempre están en el dominio del problema. Por favor, mira esto https://jjmerelo.medium.com/c%C3%B3mo-formular-buenos-objetivos-en-un-trabajo-7e68abf10028
Los objetivos normalmente preceden a las historias de usuario, porque son el marco general del problema.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ2} Proporcionar un espacio para la lectura y el intercambio de opiniones entre los usuarios, creando un espacio para debates, discusiones y comentarios sobre películas y series.
Una vez más, esto no está en el dominio del problema, y por eso es difícil de evaluar si es correcto o satisface al usuario o no. Simplemente proporcionar un "espacio para la lectura" sería correcto, sin embargo, en los detalles podría estar totalmente alejado de lo que quieren los usuarios.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Es este capítulo se va a contemplar el mercado en el que se encuentra situada la solución software
Es complicado que hables de la solución, porque todavía no lo has desarrollado. Aquí puedes hablar de dos cosas, en general
1. Productos que estén en el entorno general del problema, o que traten de resolver el problema.
2. Soluciones tecnológicas específicas: APIs, por ejemplo
3. Soluciones de más bajo nivel. En función de la anterior, puede haber lenguajes o marcos de aplicaciones que te lo hagan más fácil. Por ejemplo, un marco de gestión de contenidos.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
>  \section{Comparación entre aplicaciones}
La comparación merece la pena si lo vas a comparar con la tuya más adelante. Además, tendrás que decir qué problemas resuelve para tus clientes (o no)

2023-07-17 10:54 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +    \item \textbf{Ventajas}: Una amplia variedad de contenido, gran cantidad de reseñas y
No veo la necesidad de esto. Cada aplicación no tiene ventajas e inconvenientes sino que cubre o no las necesidades de tus clientes. Recuerda que esto es el estado del arte de *tu* proyecto, no un artículo sobre plataformas de reseñas de cine.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\section{Tendencias actuales}
Aquí deberías añadir alguna cita; una vez más si no lo vas a usar en tu TFG no tienes por qué incluirlo.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +En la primera sección, se describirá en detalle la metodología utilizada para abordar el desarrollo de este proyecto. Se explicarán las técnicas, herramientas y enfoques empleados, así como las razon
Recuerda que ágil no es una metodología, es una mentalidad.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Colaboración estrecha:} Fomenta la interacción constante entre los miembros del equipo de desarrollo, los stakeholders y los usuarios finales. Se promueve la comunicación abierta, el in
Pon sólo las partes que uses del manifiesto. Aquí no tienes clientes, y sólo yo trato de representarlos, pero eres tú el que formulas los problemas del cliente.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Orientación al cliente:} Se busca comprender las necesidades y expectativas del cliente y desarrollar soluciones que satisfagan sus requerimientos. La retroalimentación del cliente es f
Quizás deberías poner esto al principio.
Sería conveniente también cómo has aplicado cada uno de estos principios en la práctica.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Las ventajas que ofrece el desarrollo ágil sobre metodologías tradicionales:
Aquí deberías hacer una reflexión personal de qué ventajas tiene para ti, en la organización y el desarrollo de un proyecto. Hablar de satisfacción del cliente en un proyecto cuyo único cliente real es el tribunal, no lleva a ningún lado.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +{english}``\textit{stakeholders}''\end{otherlanguage}(partes interesadas). Además, facilitará la identificación temprana de problemas y la mejora constante de la calidad del producto.
Igual. ¿De qué stakeholders estamos hablando? Si no hay stakeholders, no pueden significar ninguna ventaja.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Se han creado issues en el repositorio de GitHub para realizar un seguimiento de las historias de usuario y las tareas asociadas a ellas. Estos issues describen el trabajo que debe realizarse y están
Pon enlaces.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Cada commit representa un avance en el código o en la documentación. En el mensaje del commit se proporciona una breve descripción de los cambios realizados para avanzar en el issue al que se hace re
Poner esto al mismo nivel que GitHub y milestones no tiene mucho sentido. Los commits tienen sentido en el contexto de un issue, y cómo se incluyen en PRs. Deberías hablar de issues, y de PRs y commits en el contexto de los mismos. En general, cuando hagas una lista los elementos de la misma deben estar en el mismo nivel semántico.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{M0. Configuración Inicial del TFG - Estructura, objetivos y metodología usada}
Lo más importante aquí son los sistemas de calidad: compilación del TFG y demás. El texto es importante, pero secundario.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +En este hito, se abstraerán los conceptos clave y se definirán los objetos de la aplicación. El objetivo es tener una estructura clara de los datos a utilizar. La abstracción nos permite identificar
Di primero lo que quieres obtener (el PMV); luego lo que vas a hacer.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Sin embargo, las desventajas de utilizar diagramas UML en un proyecto basado en desarrollo ágil puede no ser recomendable debido a la sobrecarga de documentación, la rigidez y falta de adaptabilidad,
Agh, no lo digas siquiera. Si pones esto en la memoria te lo preguntan seguro.

2023-07-17 10:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{M3. Lógica de Negocio - Operaciones sobre los datos}
Quizás esto sea demasiado amplio para un milestone. Lo más probable es que lo tengas que dividir en varios.

2023-07-17 15:50 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
>  \section{Comparación entre aplicaciones}
Podría compararla en la conclusión no?. De acuerdo indicaré que problemas resuelven estas aplicaciones a mis clientes.

2023-07-17 16:23 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Colaboración estrecha:} Fomenta la interacción constante entre los miembros del equipo de desarrollo, los stakeholders y los usuarios finales. Se promueve la comunicación abierta, el in
O sea que excluyo el principio de colaboración estrecha porque no existe un equipo de desarrollo.

2023-07-17 16:23 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Se han creado issues en el repositorio de GitHub para realizar un seguimiento de las historias de usuario y las tareas asociadas a ellas. Estos issues describen el trabajo que debe realizarse y están
Se me olvido el enlace al repositorio

2023-07-17 16:23 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Sin embargo, las desventajas de utilizar diagramas UML en un proyecto basado en desarrollo ágil puede no ser recomendable debido a la sobrecarga de documentación, la rigidez y falta de adaptabilidad,
¿Te refieres a lo de las desventajas?, o a todo.

2023-07-17 16:23 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\subsection{M3. Lógica de Negocio - Operaciones sobre los datos}
Si creo que lo mencionamos en la tutoría que tanto el M3 como M4 iban a ser sobre operaciones y otras operaciones sobre los datos.

2023-07-17 17:22 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Orientación al cliente:} Se busca comprender las necesidades y expectativas del cliente y desarrollar soluciones que satisfagan sus requerimientos. La retroalimentación del cliente es f
¿Al principio del capítulo?

2023-07-17 17:49 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
>  \section{Comparación entre aplicaciones}
La conclusión tiene que referirse a los objetivos y a lo que hayas aprendido. Si acaso cuando añadas una funcionalidad en un producto mínimamente viable. Pero recuerda que no estás haciendo un aplicación "como" estas, sino tu propia solución a tus propios problemas. Por eso la comparación no sé si es relevante.

2023-07-17 17:51 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\section{Tendencias actuales}
Pues eso. Que si haces afirmaciones, tienes que citar la fuente, como en la Wikipedia. Y con usarlo en el TFG me refiero a usarlo en el proyecto que hagas. ¿Las tendencias afectan a alguno de tus clientes? Recuerda que, como la espada del samurai, si la sacas debes usarla. Si hablas de tendencias es porque las vas a tener en cuenta en algún aspecto de tu aplicación.

2023-07-17 17:52 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Colaboración estrecha:} Fomenta la interacción constante entre los miembros del equipo de desarrollo, los stakeholders y los usuarios finales. Se promueve la comunicación abierta, el in
Bueno, hay un mini-equipo, tú y yo; y es software libre, así que podría haber algún colaborador. Pero no resolvemos conjuntamente los problemas, eso es tarea tuya (principalmente)

2023-07-17 17:52 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Orientación al cliente:} Se busca comprender las necesidades y expectativas del cliente y desarrollar soluciones que satisfagan sus requerimientos. La retroalimentación del cliente es f
No, de los items.

2023-07-17 17:52 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Se han creado issues en el repositorio de GitHub para realizar un seguimiento de las historias de usuario y las tareas asociadas a ellas. Estos issues describen el trabajo que debe realizarse y están
Digo a los issues.

2023-07-17 17:53 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Sin embargo, las desventajas de utilizar diagramas UML en un proyecto basado en desarrollo ágil puede no ser recomendable debido a la sobrecarga de documentación, la rigidez y falta de adaptabilidad,
Todo lo que se refiera a UML o cosas que no uses. No digas que no usas algo y por qué, es invitar al tribunal a que te lo vuelva a preguntar o a rebatirte.

2023-07-17 17:54 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{M3. Lógica de Negocio - Operaciones sobre los datos}
¿Ves lo que pasa con la tutoría, que luego hay que repetirlo en los comentarios?

2023-07-17 19:28 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
>  \section{Comparación entre aplicaciones}
Si quizá no merezca la pena comparar estas aplicaciones con mi solución.

2023-07-17 19:31 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\section{Tendencias actuales}
En la lógica de datos indico que en una versión futura de la aplicación se podría utilizar el aprendizaje automático (ML) para servir las recomendaciones a los usuarios. En referencia a esta parte del estado del arte.

2023-07-17 19:34 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Colaboración estrecha:} Fomenta la interacción constante entre los miembros del equipo de desarrollo, los stakeholders y los usuarios finales. Se promueve la comunicación abierta, el in
Vale. ¿Entonces la orientacion al cliente deberia excluirla tambien?

2023-07-17 19:36 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Orientación al cliente:} Se busca comprender las necesidades y expectativas del cliente y desarrollar soluciones que satisfagan sus requerimientos. La retroalimentación del cliente es f
Okay, me queda más claro. Además, me resuelve la duda anterior.

2023-07-17 19:37 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Se han creado issues en el repositorio de GitHub para realizar un seguimiento de las historias de usuario y las tareas asociadas a ellas. Estos issues describen el trabajo que debe realizarse y están
Vale.

2023-07-17 19:39 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Sin embargo, las desventajas de utilizar diagramas UML en un proyecto basado en desarrollo ágil puede no ser recomendable debido a la sobrecarga de documentación, la rigidez y falta de adaptabilidad,
Vale, mi intención era ver varias herramientas, en este caso UML y el DDD y compararlo. Entonces retiro toda mención a UML. Y para el futuro, no menciono o comparo diversas herramientas, simplemente describo la que he elegido y porque, no?.

2023-07-17 19:41 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\subsection{M3. Lógica de Negocio - Operaciones sobre los datos}
Si, totalmente. Gracias por responder tan rápido JJ. Por un momento me había abrumado tanto cambio y no entender algunos.

2023-07-18 15:19 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Colaboración estrecha:} Fomenta la interacción constante entre los miembros del equipo de desarrollo, los stakeholders y los usuarios finales. Se promueve la comunicación abierta, el in
No, esa la tienes en cuenta en las historias de usuario. Y es lo esencial del desarrollo ágil, no el kanban ni el scrum. Junto con la calidad.

2023-07-18 15:21 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Sin embargo, las desventajas de utilizar diagramas UML en un proyecto basado en desarrollo ágil puede no ser recomendable debido a la sobrecarga de documentación, la rigidez y falta de adaptabilidad,
UML no se pliega bien al desarrollo ágil; es para waterfall cuando todas las especificaciones están al principio. En desarrollo ágil, en general, se debe programar de forma que las relaciones entre objetos cambien. Tampoco está contrapuesto a DDD, creo. Es una forma de expresar relaciones entre objetos.

2023-07-18 15:22 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{M3. Lógica de Negocio - Operaciones sobre los datos}
Sin problemas. El problema es que PRs grandes normalmente requieren cambios abundantes, sobre todo al principio. Es mejor ir haciendo algunos pequeñitos...

2023-07-18 17:36 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Sin embargo, las desventajas de utilizar diagramas UML en un proyecto basado en desarrollo ágil puede no ser recomendable debido a la sobrecarga de documentación, la rigidez y falta de adaptabilidad,
No hay que darle opción al tribunal, okay.

2023-07-19 06:32 UTC, JJ requested changes
Mira esto también:
https://journals.sagepub.com/doi/10.2466/pr0.1990.67.1.243

En general, los objetivos son muy importantes porque es la primera decisión que tienes qeu tomar con respecto al desarrollo, es donde decides qué aspecto del problema es importante. Es un error decir que se van a abarcar todos los aspectos de todas las historias de usuario y se va a construir una aplicación final en tres plataformas con eso. Lo interesante es decidir qué aspectos son más interesantes, y resolverlos desde cero.
Creo que también hablamos de las métricas de confianza de Advogato en la tutoría, me refiero a esto https://en.wikipedia.org/wiki/Trust_metric. Es una forma alternativa de establecer fiabilidad basada en el usuario más que en el contenido.

2023-07-19 06:32 UTC, JJ commented on doc/bibliografia.bib
> +  title={\textit{A VERY SHORT HISTORY OF FILM CRITICISM}},
NO pongas marcas en la bibliografía; ya bibtex se encargará de poner lo que quiera.

2023-07-19 06:32 UTC, JJ commented on doc/bibliografia.bib
> +	title        = {\textit{Hands-On Machine Learning with Scikit-Learn and TensorFlow}},
Igual

2023-07-19 06:32 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como aficionado al cine, quiero encontrar películas a través de recomendaciones personalizadas basadas en mis gustos para descubrir nuevos contenidos que se ajusten a mí. También como aficionado al c
Solo recordarte que las historias de usuario son herramientas para el desarrollo. En particular, aquí tendrás que tener una forma de expresar esos gustos, y de encontrar cosas sólo con esos gustos.
El "También" no veo que encaje bien en la HU. Las historias de usuario deben expresar un solo deseo. "Encontrar" y "Saber si merece la pena" son dos historias de usuario diferentes.  El tener historias de usuario bien perfiladas ayuda a hacer más fácil el desarrollo.

2023-07-19 06:32 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como cinéfilo, quiero conseguir una visión profesional sobre las películas y series que consumo, a través de reseñas detalladas y fiables. Como cinéfilo, necesito participar en debates y discusiones
No entiendo muy bien lo de las series al final. Todo el tiempo has hablado de pelis. Si quieres hablar de series o de contenido audiovisual en general, el planteamiento es totalmente diferente. "A través de reseñas detalladas y fiables" es un detalle de implementación. En el desarrollo tendrás que interpretar qué es una visión "profesional". Y te vuelvo a insistir que esto es una herramienta de desarrollo. Si hablas de "debates" y "discusiones" es que estás hablando de dos cosas diferentes. "Más contenido que ver" es lo mismo que arriba, y son HUs diferentes. Y como te digo, si hablas de reseñas "detalladas" y "fiables" esas son dos características que tendrás que implementar y por supuesto testear.

2023-07-19 06:32 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como crítico de cine, quiero conseguir que lo que escribo llegue a mucha gente que pueda apreciar mi pasión por el cine y use mis críticas para discernir entre buenas películas y no tan buenas desarr
NO puedes garantizar que llegue a 7 o a 700. NO añadas detalles irrelevantes. A ver, para empezar esta HU suena un poco ególatra.  Corrige "mi el impacto". Y recuerda que las HUs expresan beneficios para una persona. ¿Qué beneficio puede reportar publicar una crítica para esa persona específicamente?

2023-07-19 06:32 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ1} Construir una aplicación que pueda proporcionar un espacio en el que los usuarios encuentren películas apegadas a sus preferencias
Se un poco menos específico aquí. Hay tres tipos de usuarios, algunos quieren encontrar películas otros otras cosas. Los objetivos deben referirse a los usuarios.

2023-07-19 06:32 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ2} Construir una aplicación que proporcione un espacio para la lectura y punto de encuentro para el intercambio de opiniones sobre películas que consumen los usuarios.
No son dos cosas diferentes, es básicamente el mismo objetivo anterior, pero para otros usuarios.
Creo que aquí deberías, en el objetivo, decidir exactamente qué vas a hacer. Puede ser una aplicación, un backend o una biblioteca, dependiendo de dónde te vayas a centrar. Igual te centras en la fiabilidad de una reseña, o de un algoritmo de ordenación que use algún aspecto determinado de las reseñas.
En un TFG debes tratar de hacer cosas bien, más que de terminar cosas rápido. Por eso debes tomar de los objetivos aspectos que te puedan interesar: creación de órdenes personalizados para usuarios, un algoritmo para establecer la fiabilidad de las reseñas, cosas así, y eso es lo que tienes que plasmar en los objetivos. Reorganizar las historias de usuario y expresarlas de otra forma no es expresar los objetivos; son la primera fase en en proceso de desarrollo donde decides en qué te vas a centrar y qué forma (más o menos) le vas a dar.

2023-07-19 06:32 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +        \item \textbf{SOBJ2.1} Asegurar la fiabilidad de las reseñas escritas por los usuarios en un %.
Es posible que esto debiera ser el objetivo principal...

2023-07-19 06:32 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\section{Aplicaciones de reseñas cinematográficas}
Si te vas a centrar en la fiabilidad de las reseñas, deberías quizás mirar trabajos publicados o algoritmos que hablen de ello.
Mira esto por ejemplo https://www.nyfa.edu/student-resources/9-tips-for-writing-a-film-review/ o esto https://www.researchgate.net/publication/311639430_Reliability_measurement_system_for_movie_review_rating

2023-07-19 06:32 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\section{Tendencias actuales}
No, me refiero a que cites por qué esto de lo que hablas es tendencia.

2023-07-20 08:38 UTC, JoseJordanF commented on doc/bibliografia.bib
> +	title        = {\textit{Hands-On Machine Learning with Scikit-Learn and TensorFlow}},
Pero si he añadido cuando fue publicado, por quién, quién fue el editor, el isbn. Podría poner el enlace al libro, pero no sería legal, por eso no lo aporto. ¿O lo pongo sin más?.

2023-07-20 08:42 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +Como aficionado al cine, quiero encontrar películas a través de recomendaciones personalizadas basadas en mis gustos para descubrir nuevos contenidos que se ajusten a mí. También como aficionado al c
O sea HU más simples y que solo expresen un deseo, pudiendo añadir varias HU de distintos aficionados?. Es que si no recuerdo mal, en una corrección me dijiste que podía unir varias HU. Pero quizá lo interprete mal. Entonces lo adecuado sería HU de distintos aficionados que expresaran un solo deseo cada una.

2023-07-20 08:48 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +Como cinéfilo, quiero conseguir una visión profesional sobre las películas y series que consumo, a través de reseñas detalladas y fiables. Como cinéfilo, necesito participar en debates y discusiones
Nada las series desaparecen, suficiente tengo ya con las pelis. Vale, lo correcto sería abolir "detalladas", ya que nos íbamos a centrar en la fiabilidad de esas reseñas, además eso es una característica que yo no puedo asegurar. Lo que no entiendo muy bien es lo que me quieres decir con esto "Si hablas de "debates" y "discusiones" es que estás hablando de dos cosas diferentes".

2023-07-20 09:10 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +Como crítico de cine, quiero conseguir que lo que escribo llegue a mucha gente que pueda apreciar mi pasión por el cine y use mis críticas para discernir entre buenas películas y no tan buenas desarr
Reconocimiento, ya que con su crítica va a orientar al público, teniendo impacto en la recepción de la película de la que haya hablado. Además, también obtendrá influencia, o sea respeto. Quizá oportunidades de trabajo para medios de comunicación.

2023-07-20 09:13 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +Como aficionado al cine, quiero encontrar películas a través de recomendaciones personalizadas basadas en mis gustos para descubrir nuevos contenidos que se ajusten a mí. También como aficionado al c
Otra cosa más, donde debo expresar que son esos gustos. O debo hacerlo directamente en la HU.

2023-07-20 09:17 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ1} Construir una aplicación que pueda proporcionar un espacio en el que los usuarios encuentren películas apegadas a sus preferencias
O sea que no exprese que los usuarios quieren encontrar películas. Si no, por ejemplo, "un espacio en el que los usuarios puedan satisfacer sus necesidades".

2023-07-20 09:22 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ2} Construir una aplicación que proporcione un espacio para la lectura y punto de encuentro para el intercambio de opiniones sobre películas que consumen los usuarios.
Vale, creo que entiendo lo que me intentas decir. Aunque me contradiga un poco con la corrección anterior, donde dices que no sea tan específico. Entiendo que estoy apegando los objetivos a las HU.

2023-07-20 09:23 UTC, JoseJordanF commented on doc/secciones/02_descripcion.tex
> +        \item \textbf{SOBJ2.1} Asegurar la fiabilidad de las reseñas escritas por los usuarios en un %.
De acuerdo

2023-07-20 09:34 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\section{Aplicaciones de reseñas cinematográficas}
No me deja leer el texto completo del artículo.

2023-07-20 10:12 UTC, JoseJordanF commented
Voy a subir varios commits para que te sea más fácil y más rápida la corrección. Y así yo puedo realizar entregas más rápidas.

2023-07-25 18:35 UTC, JJ commented
¿Está listo para revisión? Por favor, pídela explícitamente cuando lo esté.

2023-07-25 18:46 UTC, JJ requested changes
OK, todavía hay algunos asuntos pendientes de los comentarios anteriores; he tratado de responder a tus dudas y añadir algún otro detalle. Ya estás más cerca de este objetivo, en todo caso.

2023-07-25 18:46 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Como crítico de cine, quiero conseguir que lo que escribo llegue a mucha gente que pueda apreciar mi pasión por el cine y use mis críticas para discernir entre buenas películas y no tan buenas desarr
Si lo que quieres es diferenciar creadores profesionales de contenidos de otros, y darles más herramientas para ver el éxito que ha tenido, quizás también para cobrarles, inclúyelo así. Todas las historias de usuario deben de ir enfocadas a explicar cosas que nosotros tendremos que implementar.

2023-07-27 17:28 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +Así, el problema planteado en el siguiente capítulo recae en la calidad de las reseñas, en su veracidad
Si voy a centrarme en la veracidad de las reseñas

2023-07-27 17:31 UTC, JoseJordanF commented
Ha habido un error, ese no es el commit.

2023-07-27 18:14 UTC, JJ requested changes
El problema principal es que es demasiado extenso este PR, deberíamos haberlo abordado por separado. Te indico aquí qué es lo que te quedó en la última revisión y qué deberías hacer para esta.
La parte donde describes los milestones, en todo caso, la sacaría a otra rama diferente para más adelante, cuando se comience a hacer la implementación.

2023-07-27 18:14 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{Encuentra tu voz}, los mejores críticos tienen una personalidad propia que se refleja en sus escritos. Esto no se consigue de la noche a la mañana, así que aprovecha cada ocasión de esc
Está bien que menciones estas cosas, pero recuerda el tropo de "La pistola de Chejov" o la "espada del samurai". Si lo sacas, tiene que hacer sangre. De lo que hay arriba, hay cosas que puedes forzar por diseño de la aplicación: por ejemplo, releer y reescribir. Puedes marcar spoilers de alguna forma, como hacen en GoodReads. Del resto, puedes forzar el diseño para que lo incluya: una sección de interpretación, por ejemplo. Pero ¿cómo "encuentras tu voz"? ¿Cómo "piensas en el público? ¿Cómo te aseguras que se ha estudiado a los profesionales? Asegúrate de no crear falsas expectativas mediante la mención de características a las que luego no vas a hacer caso.

2023-07-27 18:14 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{IMDb:} En esta plataforma se nos ponen una serie de reglas \footnote{\url{https://acortar.link/MSYUlC}} que nos indican que debemos incluir en nuestras reseñas y que no. Haciendo uso de
Estos estudios quedan bien en papel, pero tienen un problema
1. Ocultan el problema principal que estás resolviendo. Si te vas a centrar en la calidad de las reseñas, debes sólo mencionar eso, por ejemplo diciendo que en Rotten Tomatoes scrapean reseñas de publicaciones, y estas están aparte de los revisores estrella (que no sé cómo se nombran) y del resto. Además, el público y los profesionales tienen puntuaciones diferentes.
2. Dan muy poco juego en la presentación. Con 20 minutos no puedes perder el tiempo exponiendo las diferentes plataformas y sus características poco relevantes.
3. El tribunal #1 es muy posible que se los salte de todas maneras si ocupan mucho espacio.

2023-07-27 18:14 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{Rotten Tomatoes:} En esta plataforma poseen un código de conducta para sus consumidores \footnote{\url{https://editorial.rottentomatoes.com/otg-article/community-code-of-conduct}}. Nos
El código de conducta responde a una necesidad muy específica, que tú no tienes en tus HUs. Pero desde el punto de vista técnico, tienes que establecer workflows para implementar este código de conducta: moderación obligatoria, mecanismos de denuncia (con alguien que lo compruebe)... Una vez más, si describes las plataformas es para tomar nota de las soluciones que adoptan a problemas que tú también tienes, y para que las menciones en la sección de implementación cuando lo hagas. Si no, al final es ruido. Y el ruido es peligroso, porque no ayuda a #1 a evaluar correctamente el trabajo hecho.

2023-07-27 18:14 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\section{Tendencias actuales}
En todo caso, si sólo es para trabajo futuro te lo puedes ahorrar.

2023-07-27 18:14 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\subsection{Propuesta}
En desarrollo ágil no tienes por qué hacer aquí ningún tipo de propuesta. La propuesta se va haciendo poco a poco en la implementación.

2023-07-27 18:14 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{Concepto y Características}
No uses mayúsculas Arbitrarias.

2023-07-27 18:14 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{Conclusión}
Este es el capítulo de planificación. Por lo tanto, debes indicar lo que vas a usar: milestones, y quizás decir el primero o los primeros, cómo vas a decidir qué issue abordar dentro de cada milestone (usando Kanban o cualquier otra metodología, o simplemente buscando dependencias y yendo primero a por el que más dependencias tenga).

2023-07-27 18:14 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{M0. Configuración Inicial del TFG - Estructura, objetivos y metodología usada}
Después de las presentaciones de este mes de julio, creo que es mejor incluir los milestones y su descripción en el capítulo de implementación. En desarrollo ágil no se planifica, sino que se va decidiendo sobre la marcha cuál es el próximo PMV. Si planificas de antemano todos los milestones, puedes encontrarte con problemas luego #43

2023-07-27 18:32 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{Encuentra tu voz}, los mejores críticos tienen una personalidad propia que se refleja en sus escritos. Esto no se consigue de la noche a la mañana, así que aprovecha cada ocasión de esc
Puedo dejarlas ahí como indicativo de como debería escribirse una buena reseña. Pero indicar lo que me acabas de compartir que hay puntos que son imposibles de controlar y, por tanto, no se van a tener en cuenta.

2023-07-27 18:34 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{IMDb:} En esta plataforma se nos ponen una serie de reglas \footnote{\url{https://acortar.link/MSYUlC}} que nos indican que debemos incluir en nuestras reseñas y que no. Haciendo uso de
Pero entonces lo dejo, aunque se lo salten. Yo creo que si me voy a centrar en la calidad y fiabilidad de las reseñas está bien que muestre como lo intentan otras plataformas, ¿no?.

2023-07-27 18:36 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\subsection{Propuesta}
pues las tendencias y la propuesta las elimino.

2023-07-27 18:37 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{Encuentra tu voz}, los mejores críticos tienen una personalidad propia que se refleja en sus escritos. Esto no se consigue de la noche a la mañana, así que aprovecha cada ocasión de esc
Recuerda que cada vez que menciones una cosa que no vas a hacer abres un ángulo de ataque. Con lo que tienes que quedarte aquí es con que reescribas esos punto y uses una redacción que deje claro qué esperar. Por ejemplo, "entre los puntos mencionados por xx nos quedamos con..."

2023-07-27 18:38 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{IMDb:} En esta plataforma se nos ponen una serie de reglas \footnote{\url{https://acortar.link/MSYUlC}} que nos indican que debemos incluir en nuestras reseñas y que no. Haciendo uso de
Pero si se lo salta sí se van a perder las cosas que *sí* vas a usar...

2023-07-27 18:41 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{Rotten Tomatoes:} En esta plataforma poseen un código de conducta para sus consumidores \footnote{\url{https://editorial.rottentomatoes.com/otg-article/community-code-of-conduct}}. Nos
He pensado que quizá coja la forma de puntuación que usan IMDB y letterboxd. Piensas que es trabajo innecesario, y debería borrar toda esta parte?. Es que si no que incluyo en el estado del arte. Si me centro en la fiabilidad de las reseñas y veo otras plataformas y no veo los sistemas para garantizar esa fiabilidad, carece de sentido. Bueno soy yo el que no lo entiende.

2023-07-27 18:56 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{Encuentra tu voz}, los mejores críticos tienen una personalidad propia que se refleja en sus escritos. Esto no se consigue de la noche a la mañana, así que aprovecha cada ocasión de esc
Vale, pero sin escribir los puntos que no voy a usar. Okay

2023-07-27 19:02 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +\item \textbf{IMDb:} En esta plataforma se nos ponen una serie de reglas \footnote{\url{https://acortar.link/MSYUlC}} que nos indican que debemos incluir en nuestras reseñas y que no. Haciendo uso de
Vale, pero lo sigo sin entender. Si el estado del arte está guiado a ver que hacen otras aplicaciones para resolver el problema que tú estás planteando, no tengo por qué usar las mismas técnicas que usan ellos. Solo presentar como esas otras plataformas lo intentan resolver.

2023-07-30 17:11 UTC, JoseJordanF commented
No sé si ha visto los cambios en el capítulo 2 sobre los objetivos y las historias de usuario

2023-07-31 09:09 UTC, JJ reviewed
Hay comentarios sobre los que no has reaccionado; idealmente, para que se apruebe un PR tienen que estar todos los comentarios resueltos. Algunos que no requieren cambio en la línea en la que se han hecho deben dar lugar habitualmente a un issue que se pueda tratar más adelante.

2023-07-31 09:09 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Por ello se debe abordar este problema y buscar mecanismos que promuevan reseñas de calidad,
:arrow_up:

2023-10-06 06:48 UTC, JJ commented
Esto no deberías cerrarlo, porque pierdes todos los comentarios que has hecho. Déjalo y vuelve a trabajar en él cuando lo necesites.

2023-10-06 06:54 UTC, JoseJordanF commented
Vale lo reabro. Es que como lo he reescrito en otro PR pense que este deberia cerrarlo

2023-10-06 07:04 UTC, JJ commented
Cuando fusiones main a este o hagas un rebase se quitará todo lo que hayas movido ahí, pero igual queda algo.

2023-10-06 07:07 UTC, JoseJordanF commented
Vale, lo veremos entonces más adelante.

2023-10-09 06:43 UTC, JJ commented
Quizás deberías de mover esto a otro milestone, fusionar lo que haya en main, resolviendo los conflictos.

2023-10-09 07:19 UTC, JoseJordanF commented
El caso es que este ha sido completamente reescrito en el otro PR por eso aunque resuelva conflictos no habrá nada que añadir. Es un PR "vacio"

2023-10-09 07:20 UTC, JJ commented
> El caso es que este ha sido completamente reescrito en el otro PR por eso aunque resuelva conflictos no habrá nada que añadir. Es un PR "vacio"

OK, pon entonces "closes #<este número>" en ese PR para que cuando lo fusiones se cierre este automáticamente.

2023-10-09 07:21 UTC, JoseJordanF commented
Okay

2023-10-09 07:49 UTC, merged