Modelado de objetos y abstracción del proyecto.(M1)
JoseJordanF/Claqueta pull request #31
Opened 2023-06-19 18:51 UTC by JoseJordanF

En este PR se pretende resolver los issues relevantes al Milestone 1:

- Decidir concretamente como definir los objetos de la aplicación (closes #26)
- Búsqueda de información sobre el Diseño Dirigido por el Dominio(DDD) (closes #28)
- Búsqueda de herramientas para crear el modelo de dominio de la aplicación (closes #29)
- Los objetos en sí que debo definir para ser fiel a los objetivos del proyecto (closes #30)

2023-07-07 08:46 UTC, JoseJordanF commented
El último commit es lo que hay que revisar

2023-07-07 09:03 UTC, JJ requested changes
El problema principal es que los milestones son marcas en el camino, y no se puede avanzar a otro milestone hasta que no hayas completado el anterior, porque se puede dar lugar a cambios totales de lo escrito. Todavía no está fusionado el #20, y por tanto no está terminado el milestone 0, que tiene que dar lugar a un entregable. Hasta que no lo termines, es conveniente que no progreses a los posteriores.
Por favor, revisa bien el concepto de milestone/producto mínimamente viable no sólo para usarlo, sino para describirlo correctamente en la memoria.

2023-07-07 09:03 UTC, JJ commented on claquta_CS/servidor/app.js
> +require('dotenv').config()
No puedes empezar a definir ya el servidor. Estás modelando los objetos. Cómo se sirvan esos objetos no puedes hacerlo todavía.

2023-07-07 09:03 UTC, JJ commented on claquta_CS/servidor/app.js
> +require('dotenv').config()
La configuración tampoco es parte de este milestone.

2023-07-07 09:10 UTC, JJ commented
Aparte de eso, tienes un error en el nombre del directorio `claquta`

2023-07-07 09:10 UTC, JoseJordanF commented on claquta_CS/servidor/app.js
> +require('dotenv').config()
Vale terminaré el #20 y procederé a seguir con el M1 por orden, empezando solo por los objetos. Por otro lado, el servidor entiendo que tanto su definición como la configuración son parte de la lógica de negocio.

2023-07-07 09:19 UTC, JJ commented on claquta_CS/servidor/app.js
> +require('dotenv').config()
No, la lógica de negocio se tiene que desarrollar de forma independiente. Presentación y procesamiento de información son cosas diferentes, y en arquitectura limpia se busca que se desarrolle y se pruebe cada componente por separado para garantizar una integración con éxito (y una evolución posterior también con éxito)

2023-07-17 11:09 UTC, JJ requested changes
Es muy probable que este PR tengas que reescribirlo casi completo, incluyendo PRs anteriores donde se establezca el lenguaje que vas a usar. En todo caso, te hago una serie de comentarios generales para el futuro.

2023-07-17 11:09 UTC, JJ commented on claquta_CS/models/Film.js
> +const filmSchema = new Schema({
El commit de este objeto no se corresponde a ningún issue, así que es imposible saber qué problema resuelve y si lo resuelve correctamente.

2023-07-17 11:09 UTC, JJ commented on claquta_CS/models/Film.js
> +const {Schema, model}  = require('mongoose')
En la fase de abstracción no puedes tomar una decisión sobre el modelo de datos que vas a usar. No está en el milestone, ni es necesario para definir y testear la abstracción de los datos.
En cada milestone se trata de crear productos mínimamente viables. Los datos no necesitan dónde almacenarse, así que no sería mínimamente viable.

2023-07-17 11:09 UTC, JJ commented on claquta_CS/models/Film.js
> +module.exports = model( "Film", filmSchema)
Trata de seguir unas reblas de JS determinadas a la hora de usar los fuentes. En concreto, este tipo de forma para exportar no se usa casi nunca.

2023-07-17 11:09 UTC, JJ commented on claquta_CS/models/Film.js
> +    cover_1: {
Es necesario expresar las historias de usuario con claridad, y sólo incluir en los datos lo que soliciten estas historias de usuario. Es imposible saber aquí de que HU estás hablando, porque no figura en el commit; pero es complicado que la lógica de negocio yse de alguna forma algo llamado "cover"

2023-07-17 11:09 UTC, JJ commented on claquta_CS/models/Film.js
> +    score: {
No sé a qué se refiere el score aquí, por lo ya dicho. Pero el diseño consiste principalmente, en la aplicación de los principios de domain driven design, de distiguir entre objetos valor (inmutables) y entidades (que relacionarán esos objetos valor con valores variables, como la puntuación).
En todo caso, los atributos que uses o no para describir las cosas deben plantearse en issues de los cuales escribas el código.

2023-07-17 11:09 UTC, JJ commented on claquta_CS/models/Film.js
> +        type: String,
Estás usando tipos en la descripción de los objetos, pero tipos asociados a la serialización, en vez de tipos en el ecosistema de JavaScript. Si quieres hacerlo, tendrás que considerar lenguajes tomo TypeScript; por supuesto también cualquier otro lenguaje que tenga tipos.

2023-07-17 11:09 UTC, JJ commented on claquta_CS/models/Film.js
> +        type: String,
El diseño incluye usar para cada variable el tipo que más se ajuste; para eso hay que plantear también qué problemas ser van a resolver con esos atributos, pero en todo caso, ¿te parece que algo llamado "Date" se represente mejor con un String?

2023-07-17 12:04 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +    cover_1: {
O sea que debo expresarlo en la HU que las películas tengan portada. Yo creía que era algo implícito, como una app de citas está claro que quieres ver las fotos de los usuarios. No sé cómo expresarlo, pero lo intentaré en la HU expresando que necesitan de portadas para que las recomendaciones llamen más al usuario y para una descripción más completa de la película.

2023-07-17 12:20 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +    score: {
El score sería la puntuación referente a la película, dictada por los usuarios. Lo plantearé en issues.

2023-07-17 12:36 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +        type: String,
De momento lo tenía como String, pero podría ser de tipo Date. Lo dejé como String por poder formatearlo como quisiera

2023-07-17 12:46 UTC, JJ commented on claquta_CS/models/Film.js
> +    cover_1: {
No. Los issues son problemas. Vienen a decir qué es lo que hace falta para llevar a cabo lo que pide el HU, *y solo eso*.

2023-07-17 12:47 UTC, JJ commented on claquta_CS/models/Film.js
> +    score: {
NO sé lo que es, pero como ya he dicho, el commit no se refiere a ningún issue y en todo caso debes tratar de distinguir entre objetos valor (inmutables) y entidades. Eso te ayuda a entender realmente qué es la puntuación, que no creo que sea un atributo de un objeto; por supuesto, siempre con su issue correspondiente.

2023-07-17 12:48 UTC, JJ commented on claquta_CS/models/Film.js
> +        type: String,
Si lo formateas como quieras, no lo puedes validar. Y si no lo validas, no lo puedes usar en la lógica de negocio. De hecho, ni siquiera sabes si se va a usar en la lógica de negocio, ¿no?

2023-07-17 21:48 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +const filmSchema = new Schema({
¿Pero te refieres al objeto Film?.

2023-07-18 09:19 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +        type: String,
¿Pero a qué tipos te refieres?

2023-07-18 09:27 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +    cover_1: {
Pero no lo entiendo, si no lo pide la HU no se debe incluir. O sea, las películas deberían estar sin portada, porque como expreso en la HU que deben tener portada. "Como aficionado quiero conseguir recomendaciones de películas a través de mis gustos, bien presentadas con sus portadas", por ejemplo?.

2023-07-18 12:41 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +    score: {
Puntuación es un value object, un objeto inmutable. El caso es que si es inmutable cada vez que se quiera cambiar el valor de la puntuación, se creara un nuevo value object puntuación. En vez de cambiar el valor interno del objeto. Pero hay habría un problema porque como voy a crear un nuevo objeto puntuación cada vez que cambie si depende del valor que ya tenía anteriormente. Ya que la puntuación se va a calcular gracias a lo que indiquen los usuarios.

2023-07-18 18:24 UTC, JoseJordanF commented on claquta_CS/models/Film.js
> +        type: String,
Pero eso es sintaxis json para definir objetos de la API de GraphQL.

2023-07-19 11:47 UTC, JJ commented on claquta_CS/models/Film.js
> +        type: String,
A ver, rebobinemos un poco. Aquí estás definiendo el tipo de un atributo. Supongamos por un momento que esto se ha hecho correctamente usando DDD. Has decidido que el título sea un String. Pero en vez de usar un lenguaje que te permita tipos, estás usando algo que todavía no deberías usar, que es un Schema específico de una base de datos específica. Estos tienes que usarlos para declarar tipos que ya hayas declarado en el código, no para imponerlo. Pero el tema es que haciéndolo de esta forma, lo que has evidenciado es que usar un lenguaje con tipos te ahorraría tiempo con respecto a usar uno con tipos graduales o sin tipos en atributos como JavaScript. Por lo tanto, cuando elijas el lenguaje tendrás que incluir este requisito para documentar la decisión: los tipos están bien, nos ahorran trabajo. Y luego elegirlo con respecto a ese requisito (si es que finalmente decides adoptarlo)

2023-10-16 08:28 UTC, closed without merging