Revisión del capitulo de planificación
JoseJordanF/Claqueta pull request #52
Opened 2023-08-04 14:34 UTC by JoseJordanF

En este PR se pretende resolver estos issues centrados en el capítulo de planificación, donde encontramos el enfoque usado y las herramientas para el desarrollo del proyecto.

- Decidir, según las herramientas y necesidades, el tipo de aplicación a desarrollar (closes #27 )
- Debemos decidir porque crear un tipo de API u otro (closes #50)
- Debemos encontrar herramientas que nos permitan crear ese tipo de API (closes #51)
- Debemos decidir que lenguaje usar dependiendo del tipo de aplicación (closes #49)
- Debemos decidir que frameworks tenemos que usar debido a su variedad (closes #48)

2023-09-25 15:47 UTC, JJ requested changes
El problema principal es que has incluido decisiones de implementación en un capítulo donde no es lo esperable. Trata de centrar un poco el tiro en este PR, y guarda lo que no corresponda para un PR en el futuro.

2023-09-25 15:47 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +En esta sección, se presentará la mentalidad utilizada en el desarrollo de este TFG, centrada en el enfoque ágil. Se explicarán en detalle los conceptos, características y ventajas de este enfoque, a
Más bien los principios (del manifiesto ágil) y las metodologías específicas (que se acogen a esos principios)

2023-09-25 15:47 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +El desarrollo ágil es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptabilidad y enfoque iterativo e incremental. A diferencia de
Recuerda poner referencias para estas cosas.

2023-09-25 15:47 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\subsection{Concepto y características}
Debe ser fácil de entender de qué va la subsección sin mucho contexto; el índice debe expresar una especie de narrativa. En este caso la sección es "enfoque utilizado" y la subsección "Concepto y características". Pero si no sabes que se está hablando de desarrollo ágil, no se entiende qué concepto vas a explicar. Por favor, revisa los capítulos de secciones de esta forma y haz que se entiendan fácilmente, como una especie de referencia.

2023-09-25 15:47 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Entrega temprana y continua:} El enfoque ágil se enfoca en generar valor para el cliente de manera temprana y constante. Se priorizan las funcionalidades más importantes y se entregan e
Si hablas de sprints, tienes que explicar a qué corresponden en este caso. Supongo que será a milestones, pero si lo haces en unidades más pequeñas, explícalo.

2023-09-25 15:47 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Mayor visibilidad y control:} El enfoque ágil proporciona una mayor visibilidad del progreso del proyecto y permite un mayor control sobre el desarrollo, ya que se realizan seguimientos
Visibilidad, ¿de qué?
Mayor control... no sé...

En todo caso, también conviene que estas cosas las apoyes en alguna referencia, por si #1 te pregunta.

2023-09-25 15:47 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Algo muy importante es que Kotlin es un lenguaje de propósito general, lo cual nos permite crear diversos proyectos, entre los que se encuentra el \begin{otherlanguage}
Estás poniendo esto en planificación. Las decisiones que tomes las debes incluir en el capítulo de implementación.

2023-09-25 15:47 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Un proyecto con un enfoque ágil está sujeto a pruebas constantemente, como ya sabemos de esta manera aseguramos la calidad del producto y nos cerciora de que todo funciona como debería. Consiguiendo
Los milestones también necesitan PMVs continuamente.

2023-09-26 07:34 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +En esta sección, se presentará la mentalidad utilizada en el desarrollo de este TFG, centrada en el enfoque ágil. Se explicarán en detalle los conceptos, características y ventajas de este enfoque, a
Okay, lo cambiare

2023-09-26 07:35 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +El desarrollo ágil es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptabilidad y enfoque iterativo e incremental. A diferencia de
Okayy

2023-09-26 07:36 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\subsection{Concepto y características}
Vale, haré que se entienda fácilmente

2023-09-26 07:56 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Entrega temprana y continua:} El enfoque ágil se enfoca en generar valor para el cliente de manera temprana y constante. Se priorizan las funcionalidades más importantes y se entregan e
Lo indicaré

2023-09-26 08:13 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +\item \textbf{Mayor visibilidad y control:} El enfoque ágil proporciona una mayor visibilidad del progreso del proyecto y permite un mayor control sobre el desarrollo, ya que se realizan seguimientos
Del progreso de proyecto, ambas. Lo indicaré en el título para que quede claro y lo apoyaré con alguna referencia

2023-09-26 08:15 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Algo muy importante es que Kotlin es un lenguaje de propósito general, lo cual nos permite crear diversos proyectos, entre los que se encuentra el \begin{otherlanguage}
Es cierto, al final estoy decidiendo que tipo de app hacer. Ahí solo debería indicar que tengo que tomar esa decisión no?, y decidirlo y el porqué en la implementación.

2023-09-26 08:19 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Algo muy importante es que Kotlin es un lenguaje de propósito general, lo cual nos permite crear diversos proyectos, entre los que se encuentra el \begin{otherlanguage}
Claro; se trata de la planificación. Puedes apuntar a dónde vas a tomar cada decisión, pero sólo si está en los milestones iniciales (que el resto, en ágil, se van creando sobre la marcha)

2023-09-26 22:38 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +En esta sección, se presentará la mentalidad utilizada en el desarrollo de este TFG, centrada en el enfoque ágil. Se explicarán en detalle los conceptos, características y ventajas de este enfoque, a
Perfecto, lo cambio.

2023-09-26 22:38 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +El desarrollo ágil es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptabilidad y enfoque iterativo e incremental. A diferencia de
Okay

2023-09-27 08:01 UTC, JJ requested changes
Por un lado está bien que limites los cambios a un solo fichero, que ayuda bastante a limitar el ámbito del PR y por tanto a revisarlo.

El problema principal es que estás explicando todos los principios del desarrollo ágil dentro del capítulo de planificación. El desarrollo ágil incluye muchas metodologías y buenas prácticas, pero cuando empiezas a contar que está centrado en el cliente y todo eso ves que realmente no encaja dentro del marco "planificación".

Si quieres hablar de desarrollo ágil en general, yo creo que el lugar adecuado es la introducción; en este capítulo lo más adecuado sería quizás que contaras qué dice este de planificación (básicamente, que no puedes planificar con mucha anticipación)

Aparte, creo que incluir este capítulo en el milestone 0 lo hincha mucho y retrasa su aceptación. Creo que lo mejor sería que el capítulo de planificación fuera en su propio milestone, con poco o nada más (salvo lo que tengas que organizar en el repo de la misma), y que muevas la descripción de desarrollo ágil a la introducción, cerrando el M0 y pasando al que incluya este.

2023-09-27 16:27 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
Intentaré usar mas citas a libros

2023-09-27 16:40 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Por ello se han presentado los usuarios y se han visto reflejadas sus necesidades en las historias de usuario, descritas en el segundo capítulo junto al problema. Además de la reflexión del primer ca
No sé a qué te refieres

2023-09-27 16:51 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Por ello se han presentado los usuarios y se han visto reflejadas sus necesidades en las historias de usuario, descritas en el segundo capítulo junto al problema. Además de la reflexión del primer ca
de la reflexión del primer capítulo... "que hemos hecho en no sé qué sección"

2023-09-27 17:45 UTC, JoseJordanF commented on doc/secciones/04_planificacion.tex
> +Por ello se han presentado los usuarios y se han visto reflejadas sus necesidades en las historias de usuario, descritas en el segundo capítulo junto al problema. Además de la reflexión del primer ca
A vale que especifique la sección del capítulo al que hago referencia

2023-09-28 12:11 UTC, JoseJordanF commented
Ya he reorganizado todo. La parte de la introducción está en este PR para que le eches un vistazo #56

2023-09-28 15:32 UTC, JJ approved these changes
:+1:

2023-10-03 14:09 UTC, merged