Reorganización de la metodología de desarrollo
JoseJordanF/Claqueta pull request #56
Opened 2023-09-28 12:01 UTC by JoseJordanF

En este PR simplemente se pretende reorganizar ciertas partes de la documentación que no estaban en un buen lugar de cara al #1. También se han añadido algunas citas.

2023-10-02 05:41 UTC, JJ approved these changes
No sé qué cambios has hecho en el capítulo 3, pero como te dije debería ir fuera. Como parece que es simplemente cambio de formato, no pasa nada.

2023-10-02 05:41 UTC, JJ commented on doc/bibliografia.bib
> +  year={1987}
Deberías cuidar un poco estas referencias; normalmente se pone volumen, número y páginas, así como el URL. Tampoco se suele traducir el título. Puedes sacar el .bib normalmente en el mismo artículo, suele tener un botón para generarlo.

2023-10-02 05:41 UTC, JJ commented on doc/bibliografia.bib
>  	howpublished = {\url{https://gs.statcounter.com/os-market-share/mobile}}
Este no es el URL. También la Wikipedia tiene un botón para general la bibliografía.

2023-10-02 05:41 UTC, JJ commented on doc/bibliografia.bib
> +	title        = {Agile Estimating and Planning (Estimación y Planificación Ágil)},
No traduzcas los títulos.

2023-10-02 06:54 UTC, JoseJordanF commented on doc/bibliografia.bib
> +  year={1987}
Vale, añadiré esos datos

2023-10-02 06:57 UTC, JoseJordanF commented on doc/bibliografia.bib
>  	howpublished = {\url{https://gs.statcounter.com/os-market-share/mobile}}
Pero ese enlace es por la gráfica

2023-10-02 06:57 UTC, JoseJordanF commented on doc/bibliografia.bib
> +	title        = {Agile Estimating and Planning (Estimación y Planificación Ágil)},
Okay

2023-10-02 07:07 UTC, JJ commented on doc/bibliografia.bib
>  	howpublished = {\url{https://gs.statcounter.com/os-market-share/mobile}}
Ah, cierto. Resuelve entonces.

2023-10-02 08:10 UTC, JoseJordanF commented
Lo que he añadido en el segundo capítulo es un cambio de cita

2023-10-02 10:35 UTC, JJ requested changes
Los problemas principales son los errores en la bibliografía, el resto son de detalle pero sí es conveniente que las tengas en cuenta. Por otro lado, sería conveniente que no hicieras ningún PR que abarcara varios capítulos, porque es imposible que todos se vayan a terminar dentro de un mismo PR. Lo más correcto si se pide que algo se mueva de capítulo es que se borre del PR en el que está y se abra uno nuevo, sólo con el capítulo.

2023-10-02 10:35 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Este libro\cite{MetodDesa} es ampliamente respetado en la comunidad de desarrollo ágil y proporciona una visión detallada de cómo llevar a cabo estimaciones y planificaciones efectivas en proyectos d
Antes de esto, deberías decir que efectivamente vas a ir por el desarrollo ágil. Trata de introducir todos los conceptos correctamente; estamos en la introducción y citar un libro del tirón posiblemente no lo vean bien #1

2023-10-02 10:35 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Debido a la importancia de establecer una metodología a seguir para nuestro proyecto, nos centraremos en el enfoque ágil \cite{WhyAgile}. Procedamos a presentar los principios en los que se basa el m
Por ejemplo, este párrafo antes del otro.

2023-10-02 10:35 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
Ya has puesto citas de desarrollo ágil, no pontas ahora enlaces; ponlo también como cita y ponlos todos a la vez en la misma cita cuando lo menciones la primera vez.

2023-10-02 10:35 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\subsection{Ventajas}
Esta es la subsección de una sección qeu se llama "*metodología* de desarrollo". Ya sabemos que ágil no es una metodología, es un conjunto de buenas prácticas para seleccionar metodologías específicas en cada fase. Pero el problema aquí es que como desciende de "metodología" se leería como "Ventajas de la metodología de desarrollo", no ventajas específicas del marco de desarrollo que vas a elegir. Trata de pensar en una mejor estructura una vez más para que la rúbrica de expresión escrita evaluada por #1 consiga una buena nota.

2023-10-02 10:35 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +\subsection{Conclusión}
Está bien que todos los capítulos los termines de esta forma, pero comprueba por favor si no quieres decir "Conslusiones" en vez de una sola conclusión.

2023-10-02 10:35 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
Usa referencias en la bibliografía, no notas a pie de página.

2023-10-03 22:45 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +Debido a la importancia de establecer una metodología a seguir para nuestro proyecto, nos centraremos en el enfoque ágil \cite{WhyAgile}. Procedamos a presentar los principios en los que se basa el m
Cierto

2023-10-03 22:48 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
Yo pensaba que quedaría mejor donde menciono ciertos términos como manifiesto ágil, cito el manifiesto

2023-10-04 05:33 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
OK, como tú veas. En todo caso, es mejor una cita que un URL en una nota a pie de página.

2023-10-04 07:02 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +Este libro\cite{MetodDesa} es ampliamente respetado en la comunidad de desarrollo ágil y proporciona una visión detallada de cómo llevar a cabo estimaciones y planificaciones efectivas en proyectos d
Intercambiaré los párrafos como mencionas en el siguiente comentario.

2023-10-04 07:04 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
Si cambiare las urls a pie de página. ¿Incluso debería hacer un PR pequeño donde cambie todas las urls a pie de página que existen en varios capítulos por citas??

2023-10-04 07:06 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
En general, como te digo, #1 prefiere citas a notas a pie de página. Sin embargo, no todos los URLs pueden convertirse en citas; es mejor que sólo conviertas en citas los artículos con autor identificado o libros, no manuales y cosas así.

2023-10-04 07:10 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +\subsection{Conclusión}
Vale

2023-10-04 09:05 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
Perfecto

2023-10-04 09:06 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +\subsection{Ventajas}
Vale, a ver si doy con la tecla

2023-10-04 22:55 UTC, JoseJordanF commented
He cambiado todas las referencias bien documentadas por citas y la sección y subsección que has mencionado.

2023-10-09 06:38 UTC, JJ reviewed
Creo que aquí todavía queda algún comentario por resolver, ¿no?

2023-10-09 06:38 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Debido a la importancia de establecer una metodología a seguir para nuestro proyecto, nos centraremos en el enfoque ágil \cite{WhyAgile}. Procedamos a presentar los principios en los que se basa el m
Si has hecho esto, resuelve y pon el commit donde se haya hecho.

2023-10-09 07:16 UTC, JoseJordanF commented
Diría que no, que todos están resueltos en el último commit: 
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6#diff-009e51c1bc0768d10b79412fefe284f3ea1f4033e3a5060fa02f77c1a69aca97)

2023-10-09 07:18 UTC, JJ commented
> Diría que no, que todos están resueltos en el último commit: ([8007c92#diff-009e51c1bc0768d10b79412fefe284f3ea1f4033e3a5060fa02f77c1a69aca97](https://github.com/JoseJordanF/Claqueta/commit/8007c92beb8a282edf8ab2eedcefc46da5778ad6#diff-009e51c1bc0768d10b79412fefe284f3ea1f4033e3a5060fa02f77c1a69aca97))

Pues lo dicho, pon ese commit en el comentario que yo haya incluído y a continuación resuelve.

2023-10-09 07:24 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +El desarrollo ágil \footnote{\url{https://www.agilealliance.org/agile101/}} es un enfoque metodológico utilizado en proyectos de desarrollo de software que se caracteriza por su flexibilidad, adaptab
(https://github.com/JoseJordanF/Claqueta/commit/8007c92beb8a282edf8ab2eedcefc46da5778ad6#diff-009e51c1bc0768d10b79412fefe284f3ea1f4033e3a5060fa02f77c1a69aca97)

2023-10-09 07:24 UTC, JoseJordanF commented
Hecho

2023-10-09 08:33 UTC, JJ requested changes
El principal problema es el comentario que no has resuelto, pero por favor mira los otros comentarios, y resuelve los que hayas hecho con el commit en el que se haya hecho.

2023-10-09 08:33 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +CRITICISM}''\end{otherlanguage}\cite{3BrothersArticle}. \footnote{El título del artículo y futuros términos en inglés serán marcados para preservar la calidad del texto y poder realizar comprobacione
¿Por qué va ese título en mayúsculas?

2023-10-09 08:33 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
:arrow_up: No está resuelto.

2023-10-09 08:34 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +Debido a la importancia de establecer una metodología a seguir para nuestro proyecto, nos centraremos en el enfoque ágil \cite{WhyAgile}. Procedamos a presentar los principios en los que se basa el m
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6)

2023-10-09 08:35 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6)

2023-10-09 08:40 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +CRITICISM}''\end{otherlanguage}\cite{3BrothersArticle}. \footnote{El título del artículo y futuros términos en inglés serán marcados para preservar la calidad del texto y poder realizar comprobacione
Pues creo que lo copie así del artículo y no caí en cambiarlo

2023-10-09 08:42 UTC, JoseJordanF commented on doc/bibliografia.bib
> +  year={1987}
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6)

2023-10-09 08:43 UTC, JoseJordanF commented on doc/bibliografia.bib
> +	title        = {Agile Estimating and Planning (Estimación y Planificación Ágil)},
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6)

2023-10-09 08:43 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +Este libro\cite{MetodDesa} es ampliamente respetado en la comunidad de desarrollo ágil y proporciona una visión detallada de cómo llevar a cabo estimaciones y planificaciones efectivas en proyectos d
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6)

2023-10-09 08:44 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +\subsection{Ventajas}
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6)

2023-10-09 08:44 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +\subsection{Conclusión}
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/8007c92beb8a282edf8ab2eedcefc46da5778ad6)

2023-10-09 09:00 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +CRITICISM}''\end{otherlanguage}\cite{3BrothersArticle}. \footnote{El título del artículo y futuros términos en inglés serán marcados para preservar la calidad del texto y poder realizar comprobacione
(https://github.com/JoseJordanF/Claqueta/commit/768853508a9f20e4dfc3a9bffe838690360bec7e)

2023-10-09 09:01 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
(https://github.com/JoseJordanF/Claqueta/commit/156f67f80fcde4592d326d0524ef3220f082a7ae)

2023-10-09 09:08 UTC, JJ requested changes
El principal problema es el link que sigue ahí, a pie de página (busca `acortar.link` ).

2023-10-09 09:08 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
(Convendría que configuraras el editor para que te dividiera las líneas, así sería más fácil comentar en líneas específicas).

:warning: El que sigue "aplicaciones a mejorar" está todavía sin cambiar.

2023-10-09 09:08 UTC, JJ commented on doc/secciones/01_introduccion.tex
> +Debido a la importancia de establecer una metodología a seguir para nuestro proyecto, nos centraremos en el enfoque ágil \cite{WhyAgile}. Procedamos a presentar los principios en los que se basa el m
Fíjate que estás hablando de "una metodología" y sin embargo te refieres al "enfoque ágil". En general, no deberías hablar de **una** metodología. Un enfoque, o marco de desarrollo como tú dices, es un conjunto no sólo de metodologías, sino de buenas prácticas. Quizás sustituyendo "metodología" por "conjunto de metodologías y buenas prácticas" sea un poco más preciso. Considéralo, por favor, y trata de entender por qué es así.

2023-10-09 09:53 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +Debido a la importancia de establecer una metodología a seguir para nuestro proyecto, nos centraremos en el enfoque ágil \cite{WhyAgile}. Procedamos a presentar los principios en los que se basa el m
Sii entiendo por qué es así, creía que lo había cambiado anteriormente pero se me olvidaría

2023-10-09 09:56 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
Es que cuando estuve buscando como hacerlo, no lo encontré y lo deje pasar. Esta tarde lo configuro y cambio esto para que por fin podamos cerrar el M0

2023-10-09 16:12 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
JJ nada de lo que pruebo permite que cada 80 caracteres se produzca un salto de línea a no ser que lo reemplace a mano, no sé de qué manera lo puedo hacer automático. Uso Overleaf

2023-10-09 17:31 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
Ah, pensaba que usabas para todo VSCode. Igual sería conveniente que abrieras un issue en el que hablaras de las herramientas que usas, y por qué; Overleaf realmente no te aporta mucho si no estás colaborando online. Además, ¿lo usas directamente desde este repo o vas copiando?

2023-10-09 19:28 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
La verdad que con VSCode supongo que será mucho más cómodo, aunque ya estoy acostumbrado a Overleaf y para lo que me queda. Lo empecé a usar porque me era más cómodo usar en todas partes.

2023-10-10 05:38 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +Referente a las tendencias actuales en las aplicaciones de reseñas, podemos encontrar una mayor integración de las redes sociales, ya que cada vez son más las aplicaciones que permiten compartir rese
(https://github.com/JoseJordanF/Claqueta/commit/6b6929dbdc76d2d231719a9ae310366238f3149c)

2023-10-10 06:15 UTC, JoseJordanF commented on doc/secciones/01_introduccion.tex
> +Debido a la importancia de establecer una metodología a seguir para nuestro proyecto, nos centraremos en el enfoque ágil \cite{WhyAgile}. Procedamos a presentar los principios en los que se basa el m
(https://github.com/JoseJordanF/Claqueta/pull/56/commits/c3a55e96151895eebb4de8d96629ba27f3dff4fa)

2023-10-10 07:43 UTC, JoseJordanF commented on doc/secciones/03_estado_del_arte.tex
> +comunidad de usuarios comprometidos y su enfoque en el cine de autor. \vspace{1cm}
Ya debería haberlo hecho en un commit directamente a la master

2023-10-10 07:44 UTC, JoseJordanF commented
Todo correcto?, fusiono entonces?

2023-10-10 08:10 UTC, JJ commented
Está aprobado, así que...

2023-10-10 08:16 UTC, JoseJordanF commented
Perfecto no lo había visto

2023-10-10 08:16 UTC, merged