Documentacion y PMV del M1
JoseJordanF/Claqueta pull request #60
Opened 2023-10-16 08:33 UTC by JoseJordanF

En este PR se pretende resolver los issues relevantes al Milestone 1, obteniendo tanto la documentación referente a este como los modelos del proyecto:

- Decidir concretamente como definir los objetos de la aplicación (closes #26)
- Búsqueda de información sobre el Diseño Dirigido por el Dominio(DDD) (closes #28)
- Búsqueda de herramientas para crear el modelo de dominio de la aplicación (closes #29)
- Los objetos en sí que debo definir para ser fiel a los objetivos del proyecto (closes #30)
- Donde debía decidir que tipo de aplicación desarrollar (closes #27)
- Cuáles eran las opciones para test unitarios (closes #48)
- Cuál sería el lenguaje más adecuado según las necesidades del proyecto (closes #49 )

2023-10-16 08:44 UTC, JoseJordanF commented
Hay un error con la subida de código, hago un commit ahora mismo.

2023-10-16 10:01 UTC, JJ reviewed
Hay 59 ficheros, muchos de los cuales no tendrían que estar ahí. Ni los del directorio .idea ni los de .gradle deberían estar en el PR. Es una mala práctica hacer `git add .`, pero también lo es no revisar lo que hay en el PR para ver si hay ficheros que no deberían estar ahí. En general, no aconsejo que se hagan rebases o squish commit, pero esta rama contiene muchos ficheros binarios que van a quedar ahí si no los eliminas mediante un squish commit. Por favor, hazlo así (o como mejor veas para eliminarlos no sólo de la rama, sino también de la historia)

2023-10-16 10:02 UTC, JJ commented
También tienes ficheros que son parte del UI, lo que no corresponde aparentemente al ámbito de este PR.

2023-10-16 10:09 UTC, JJ requested changes
Siendo un milestone de implementación, la buena práctica sería primero llevar a cabo la implementación, y simultáneamente describir qué se está haciendo y los restos que hay.

2023-10-16 10:09 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +En este capítulo se va a proceder a desarrollar cada uno de los hitos, obteniendo en un PMV. Además,
hitos de implementación

2023-10-16 10:09 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Otra gran entidad sería el usuario, sus atributos serían los necesarios para identificarse, como el
En general, la forma de aplicar el DDD sería efectivamente crear las estructuras de datos. Y para crear las estructuras de datos tienen que obtenerse una serie de problemas que surjan de las historias de usuario que se están implementando.

2023-10-16 16:07 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Otra gran entidad sería el usuario, sus atributos serían los necesarios para identificarse, como el
O sea que haga referencia a que parte de las HU hacen referencia las características de cada entidad

2023-10-17 06:15 UTC, JoseJordanF commented
JJ entonces te refieres a hacer un squash and merge cuando se apruebe el PR??

2023-10-17 06:20 UTC, JJ commented
> JJ entonces te refieres a hacer un squash and merge cuando se apruebe el PR??

Sí, eso evita un force push.

2023-10-17 06:20 UTC, JoseJordanF commented
Okay

2023-10-17 06:20 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +En este capítulo se va a proceder a desarrollar cada uno de los hitos, obteniendo en un PMV. Además,
(8d37f26b04b46cde67474346d382b360ca211937)

2023-10-17 06:21 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Otra gran entidad sería el usuario, sus atributos serían los necesarios para identificarse, como el
#62 (8d37f26b04b46cde67474346d382b360ca211937)

2023-10-17 07:01 UTC, JJ requested changes
Me temo que es muy prematuro describir el análisis dirigido por el dominio antes de llevar a cabo el análisis y el código. 
Te recomendaría que hicieras tres partesde este PR
1. Exclusivamente la parte de introducción del capítulo y descripciones genéricas (biblio y 06_implementacion.tex, lo que *no* se refiere a DDD)
2. Código
3. Cuando 2 esté aprobada, pasas a la descripción en si.

2023-10-17 07:14 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +De esta manera se busca, priorizar el desarrollo real, la retroalimentación continua y prácticas como
Sii está activado

2023-10-17 07:17 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\section{M1. Definición de objetos - Abstracción del proyecto}
Si el M0 al ser configuración lo explicamos en el cap de planificación

2023-10-17 07:21 UTC, JJ requested changes
Algunos comentarios sobre el código en sí, pero el principal es que debes seguir una metodología estricta para desarrollar ese código: todo el análisis DDD debe estar en sus correspondientes issues, que se enlacen con las HUs.
En todo caso, considera la posibilidad de dejar sólo la intro al capítulo en este PR, y desarrollar el código más sistemáticamente y en más PRs

2023-10-17 07:21 UTC, JJ commented on model/domain/User.kt
> +data class User(
En DDD tienes que llegar a los objetos más simples posibles que puedan soportar la lógica de negocio; generalmente, esos objetos serán inmutables y por tanto objeto valor. El que sean inmutables te indica que habrá una parte referida al objeto que no varíe, y otra, la que varía, que tiene que gestionarse a un nivel superior, generalmente a través de una entidad.

2023-10-17 07:21 UTC, JJ commented on model/domain/User.kt
> +    val email: String,
Todo este fichero se ha subido con un commit cuyo mensaje es "subida de código".
Todo el desarrollo ágil se enfoca hacia el cliente, y la forma de reflejar el cliente es, en cada trozo de código, reflejar de qué manera aporta valor al cliente. Los mensajes genéricos como "subida de código" no sólo impiden saber qué es lo que aporta al cliente, también impiden saber qué se ha hecho y qué decisiones se han tomado.
Te dejo aquí [esta guía sobre los issues](https://www.linkedin.com/pulse/los-issues-y-su-importancia-en-la-organizaci%25C3%25B3n-de-un-proyecto-merelo/?trackingId=snKNI3haQJCx4x9Q2Lod%2Fg%3D%3D), a ver si te puede ayudar a llevar a cabo esta fase.

2023-10-17 07:21 UTC, JJ commented on model/domain/User.kt
> +    val password: String,
Siempre en ingeniería tienes que trabajar hacia el próximo producto mínimamente viable. ¿Te parece que la lógica de negocio vaya a usar el password en algún momento?

2023-10-17 07:21 UTC, JJ commented on model/domain/User.kt
> +    val reputation : Int = 0
Si el usuario "aloja" su reputación, tiene que ser el usuario el gue la gestione. ¿La lógica de negocio para gestionar la reputación de un usuario la va a tener el propio usuario? ¿O habrá una entidad que la necesite?

2023-10-17 07:21 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\section{M1. Definición de objetos - Abstracción del proyecto}
A que hagas un enlace desde el texto al milestone en GitHub.

2023-10-17 07:24 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +Otra gran entidad sería el usuario, sus atributos serían los necesarios para identificarse, como el
No creo que el usuario sea un objeto valor, ya que debe tener un identificador único que identifique a cada usuario. O al menos yo lo veo así. Y no entiendo lo del código, si lo he subido a la vez que la documentación, y lo he hecho a la vez. Primero debería haber hecho el código y después esa parte de la documentación entiendo.

2023-10-17 07:28 UTC, JoseJordanF commented on model/domain/User.kt
> +    val password: String,
Los usuarios al fin y al cabo deben identificarse

2023-10-17 07:33 UTC, JoseJordanF commented on model/domain/User.kt
> +    val reputation : Int = 0
En teoría es el usuario el que la gestiona de manera indirecta con sus acciones, por eso está ahí. Pero si la debería gestionar otra entidad

2023-10-17 07:34 UTC, JoseJordanF commented on model/domain/User.kt
> +    val email: String,
Okay

2023-10-17 07:35 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Otra gran entidad sería el usuario, sus atributos serían los necesarios para identificarse, como el
No se trata de que lo creas o no. Se trata de que debes hacer una serie de issues que salgan de la HU y resolverlos mediante código. DDD no va de ponerle nombres a las cosas. Se trata de ver qué controla qué, y de cómo se gestionan los diferentes objetos del problema.

2023-10-17 07:36 UTC, JJ commented on model/domain/User.kt
> +    val password: String,
Una cosa es que es deban autenticar (que no identificar), otra es que lo pongas en la misma clase, o siquiera de que debas decididr en esta fase del desarrollo cómo se van a autentificar.
Hay por otro lado muchas formas de autenticarse. La forma que vayas a usar es una decisión técnicas que tienes que tomar durante el desarrollo, en el momento que sea necesaria.

2023-10-17 07:37 UTC, JJ commented on model/domain/User.kt
> +    val reputation : Int = 0
¿Cuando dices "de manera indirecta", quieres decir que va a ser una entidad quien las gestione? ¿No significa eso que habrá algún tipo de objeto que relacione usuarios con reputación en una entidad?

2023-10-17 07:38 UTC, JoseJordanF commented on model/domain/User.kt
> +data class User(
Con esto te refieres, poniendo de ejemplo el comentario de la reputación. Que user sea un VO como has mencionado y exista una entidad como por ejemplo Sesión que sea la que gestione la sesión de los usuarios y por ende la reputación estando este atributo en esta entidad y en user solo lo necesario que lo haga inmutable.

2023-10-17 07:43 UTC, JJ commented on model/domain/User.kt
> +data class User(
No. Me refiero a que tienes que plantear todos los problemas que se planteen en las historias de usuario (identificar de forma única a los usuarios, gestionar su reputación, qué es la reputación, todo eso) en issues e ir creando PRs que resuelvan esos problemas, lo más atómicamente posible. 
En ingeniería del software, a diferencia de cómo lo puedan contar en la carrera, rara vez hay una única forma de hacer las cosas. Hay metodologías que, si se siguen, te aseguran la creación de un producto de calidad, de forma eficiente, y que pueda adaptarse fácilmente a nuevas necesidades. Si no se sigue la metodología es imposible saber si lo que sugieres es bueno, malo o simplemente indecidible porque no está bien definido el problema.
Quizás deberías empezar a plantear los diferentes problemas que están relacionados con el usuario, por ejemplo: tiene que estar identificado de forma única.

2023-10-17 07:51 UTC, JoseJordanF commented on doc/secciones/06_implementacion.tex
> +\section{M1. Definición de objetos - Abstracción del proyecto}
De acuerdo

2023-10-17 07:54 UTC, JoseJordanF commented on model/domain/User.kt
> +    val reputation : Int = 0
Si, cierto

2023-10-17 07:56 UTC, JoseJordanF commented on model/domain/User.kt
> +    val password: String,
Vale, lo siento es que al no desarrollar nunca una app de esta manera, tengo cosas que yo creo que son obvias, que ni siquiera se deben plantear ahora

2023-10-18 06:40 UTC, JJ approved these changes
:+1:

2023-10-18 06:41 UTC, JoseJordanF commented
¿Si hago el squash se perderán los comentarios?

2023-10-18 06:44 UTC, JJ commented
> ¿Si hago el squash se perderán los comentarios?

Los comentarios se quedan aquí. Pero si quieres tenerlos en cuenta, es mejor que abras un issue.

2023-10-18 07:28 UTC, JoseJordanF commented
Entonces hago un squash, pero creo un issue que me recuerde que tengo estos comentarios aquí

2023-10-18 09:20 UTC, merged