Formulacion de objetivos contundentes, concisos y viables. Acotado
JoseJordanF/Claqueta pull request #7
Opened 2023-04-23 17:55 UTC by JoseJordanF

En este PR se quiere cerrar los issues referentes al capítulo 2 y así avanzar en el Milestone 0 :

- La escritura del capítulo y la formulación de los objetivos (closes #6)

2023-04-24 05:40 UTC, JJ commented
Deberías tener ya el workflow para comprobar la ortografía; no se debe incorporar a main nada sin que se compruebe.

2023-04-24 05:49 UTC, JJ requested changes
Por favor, lee [este artículo](https://www.linkedin.com/pulse/comenzando-con-un-trabajo-fin-de-gradom%2525C3%2525A1ster-%2525C3%2525A1gil-juan-j-merelo%3FtrackingId=w3wI%252FG7froav130rUVRwCA%253D%253D/?trackingId=w3wI%2FG7froav130rUVRwCA%3D%3D) sobre como empezar el TFG. Es esencial que formules los user journeys y definas los clientes antes de llegar a los objetivos.

2023-04-24 05:49 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +interesara a los demás.
Ten mucho cuidado con los argumentos que no sean relevantes para tu proyecto. Tienes que tratar de plantear problemas reales de tus clientes en la medida de lo posible.

2023-04-24 05:49 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Con la llegada de las redes sociales paso hacer algo más fácil, todo el mundo puede decir lo que quiera
Relee la frase y reescríbela, por favor.

2023-04-24 05:49 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +esos usuarios. El problema radica en que es una red social para socializar cualquier cosa, por eso se
"socializar" no es transitivo, no se puede socializar "cualquier cosa"

2023-04-24 05:49 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +Por esta razón es muy importante escuchar al cliente, ya que son ellos los que van a explotar el
No queda muy claro cuál es "esta razón". En todo caso, escuchar al cliente es lo que pide el desarrollo ágil.

2023-04-24 05:49 UTC, JJ commented on doc/secciones/02_descripcion.tex
> +    \item \textbf{OBJ1} Llegar a diseñar y desarrollar un espacio software en el que sea posible
Los objetivos tienen que ser resolver los problemas que plantee el cliente, y para ello tienes que expresarlos siempre en el espacio del problema. Esos objetivos se alcanzarán a través de una serie de milestones, que serán productos de complejidad creciente. No puedes mezclar los unos con los otros, porque si no tienes claro qué problema vas a resolver, tampoco queda claro qué hacer para resolverlo y se corre el riesgo de hacer cosas que no resuelvan nada, pero sobre todo, no se sabe si lo que haces es correcto o no porque no está claro cuál es el problema.

2023-05-02 07:33 UTC, JJ commented
Convendría que incluyeras antes el comprobador ortográfico; el desarrollo ágil hace énfasis en la calidad, y también la ortografía es parte de la misma.

2023-05-02 08:49 UTC, JoseJordanF commented
No entiendo por qué al hacer el push no hace el check, creo que es por la rama, pero es que si hago el push con la rama master no aparece aquí. Y me esta empezando a agobiar porque no encuentro como resolverlo

2023-05-02 09:07 UTC, JJ commented
> No entiendo por qué al hacer el push no hace el check, creo que es por la rama, pero es que si hago el push con la rama master no aparece aquí. Y me esta empezando a agobiar porque no encuentro como resolverlo. He comprobado haciendo un push con la rama master y si realiza el check. El problema que ahora tengo conflictos entre ambas ramas. (Resuelto)

Vamos a ver qué pasa. Lo más probable es que tengas que mergear master en esta rama, porque sólo se usan las actions de la rama que se está haciendo push. Segundo más probable, que el path para que se lance sea incorrecto. Miro y te digo.

2023-05-02 09:12 UTC, JJ commented
Parece que ya lo has solucionado; salvo el tema de que tienes que cualificar los paths y demás para que sólo compile cuando sea necesario.

2023-05-02 09:22 UTC, JoseJordanF commented
Vale, no sé cómo se cualifican los paths, pero intentaré averiguar como hacerlo. Soy nuevo usando GitHub y se nota bastante. Gracias JJ

2023-05-02 09:23 UTC, JJ commented
@JoseJordanF pones 
push:
    paths:
       -

2023-05-02 09:26 UTC, JoseJordanF commented
Vale, ya lo entiendo, solo hago que se ejecute cuando se realice un push en la carpeta de la documentación

2023-05-02 09:28 UTC, JoseJordanF commented
Si especificando *.tex supongo

2023-05-03 08:41 UTC, JoseJordanF commented
De esta manera solo se comprobarán las secciones/capitulos:
on: 
  push:
    paths:
      - 'doc/secciones/*.tex'

2023-05-10 07:31 UTC, JJ commented
Tienes que resolver los conflictos; lo puedes hacer manualmente, o mediante el interfaz web aquí

2023-05-11 08:15 UTC, JoseJordanF commented
¿Fusiono ya con la rama máster?

2023-05-11 10:04 UTC, JJ commented
O sea, que para el caso, sí, fusiona, pero vamos, no te va a dejar. En todo caso los contenidos que hay en la rama principal tienes que revisarlos.

2023-05-12 08:05 UTC, merged