Definicion de entidades y value object
JoseJordanF/Claqueta pull request #73
Opened 2023-10-19 09:15 UTC by JoseJordanF

En este PR se pretende modelar los objetos necesarios, designando las entidades y los objetos valor. Resolviendo algunos de los problemas planteados:

- (closes #66)
- (closes #67)
- (closes #68)
- (closes #70)
- (closes #71)
- (closes #72)

2023-10-23 08:01 UTC, JJ requested changes
Sólo he revisado el primero, pero dado que es un problema de metodología, también afecta al resto. El código que se desarrolla sin mirar (y enlazar desde el commit) un issue no está ni bien ni mal, simplemente no se puede decidir si ayuda al cliente o no, y por tanto es inválido. El código tiene que resolver problemas planteados en issues, y estos a su vez enlazados en historias de usuario. Así el que revisa el PR puede decidir (antes o en parallo a los tests automáticos) si se está aportando valor al usuario o no. En cualquier caso un PR no es un trámite, es una forma de transmisión de conocimiento, y ese conocimiento se halla en los mensajes de commit y en el código; si uno de los dos aspectos no está claro o no está enlazado correctamente, es muy complicado para quien revisa aportar a su vez valor a quien desarrolla (y al cliente) aportando sugerencias o aprobando.

2023-10-23 08:29 UTC, JoseJordanF commented on domain/Film.kt
> +    val movieDirector : String,
En películas es raro ver más de un director, pero se puede plantear en un issue

2023-10-23 08:30 UTC, JoseJordanF commented on domain/Film.kt
> +    val description: String,
Como presentación para el usuario, pero si no se da ese aspecto en ninguna HU

2023-10-23 08:34 UTC, JJ commented on domain/Film.kt
> +    val movieDirector : String,
Joer, ¿y los Javis?
En todo caso la cuestión es que esto debe ser una decisión explícita, explicada en el mensaje de commit, a un problema que se plantee en un issue que se enlace en el mismo mensaje. Y el problema no es tanto si hay uno o dos directores, sino qué estructura de datos se va a usar para representarlo, y si el concepto de "Director" necesita también su propia dataclass o no. Dependiendo de la HU, puede que se busque analizar las reviews medias por escritor, por ejemplo, con lo que hay que individuarlos.

2023-10-23 09:10 UTC, JoseJordanF commented on domain/Film.kt
> +    val movieDirector : String,
Cierto jajajaja

2023-10-23 09:52 UTC, JoseJordanF commented
¿Es así como debo de realizar los commits?

2023-10-23 12:34 UTC, JJ requested changes
Aparte de los problemas indicados, issues como #71 no están ligados a ninguna HU, por lo qeu es imposible saber qué valor aportan al usuario.

2023-10-23 12:34 UTC, JJ commented on domain/Film.kt
> +    val duration : Int = 0,
¿Qué HU pide la duración de la película?

2023-10-23 12:34 UTC, JJ commented on domain/Review.kt
> +    val howUseful : Double
Este atributo no resuelve #71. Si acaso, permite almacenar un valor númerico sobre ello.
En todo caso, aquí habría dos consideraciones.
1. Producto mínimamente viable. Tienes que estructurar bien qué vas a tener en el primer prototipo y qué en otros prototipos. ¿En el primero va a haber un i/f para que se vote lo útil qeu es una review?
2. No estás usando una dataclass porque ese valor no es variable; pero es el único valor que no es variable; el resto son constantes. Cuando sucede esto, lo primero que tienes que pensar es quién va a gestionar la parte variable, y en general domain driven design te va a decir "que lo gestione otro".

2023-10-23 12:34 UTC, JJ commented on domain/Review.kt
> +    val containSpoiler: Boolean,
¿También tendría que estar en el PMV?

2023-10-23 15:43 UTC, JoseJordanF commented on domain/Film.kt
> +    val duration : Int = 0,
Hablamos de las formas en las que recomendar a los usuarios. Todos esos atributos forman parte de ese si consumes películas de poca duración, se te van a recomendar películas de entorno a esa duración. Lo mismo pasa con el director y con la fecha de estreno. Los 3 sirven para las recomendaciones.

2023-10-23 15:52 UTC, JoseJordanF commented on domain/Review.kt
> +    val howUseful : Double
Ciertamente, estoy introduciendo atributos que quizá es demasiado pronto para el primer pmv o primer prototipo. Y howUseful es variable, ya que con ello quiero mostrar la media de las personas a las que le ha sido útil dicha reseña a sí que a medida que la gente interactúa con ella esta variable cambiara y, por tanto, eso hay que gestionarlo probablemente con un value Object que sea el que calcule esa media.

2023-10-23 15:52 UTC, JoseJordanF commented on domain/Review.kt
> +    val containSpoiler: Boolean,
A qué atributo o atributos te refieres

2023-10-23 16:08 UTC, JJ commented on domain/Review.kt
> +    val howUseful : Double
Lo más probable que quien gestione lo que sea es una entidad, y que tenga almacenados value objects con cada una de las "usefulness"

2023-10-23 16:15 UTC, JoseJordanF commented on domain/Film.kt
> +    val duration : Int = 0,
No te preocupes, lo especifico en la HUs ,yo pensaba que estaba implícito

2023-10-24 09:51 UTC, JJ requested changes
Tienes que tratar de mirar a todo el modelo en conjunto y ver que sea coherente; aparte, como te he comentado, es imprescindible que *todos* los issues estén relacionados con una HU.

2023-10-24 09:51 UTC, JJ commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
Aparte de lo comentado en #78, aquí estás tomando varias decisiones que no has explicado. Primero, usar un map para mapear un `Long` (que no está cualificado de ninguna forma) a una lista de Review. Eso implica que la forma de acceso principal va a ser desde la película. Pero si lo que vas a hacer es usar las reviews para recomendaciones, ¿no debería accederse por usuario, y no por película?
El problema es que, como te he indicado, no hay enlace entre el issue #78 y alguna HU; por eso es imposible saber si eso está bien o no.

2023-10-24 09:51 UTC, JJ commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
Tienes la lista de Reviews en dos lugares entonces, ¿no?

2023-10-24 09:51 UTC, JJ commented on domain/Film.kt
> +    val title : String,
No hay ningún atributo aquí que permita enlazar un Film con el "long" que usas para representarlo.

2023-10-24 09:53 UTC, JoseJordanF commented on domain/Film.kt
> +    val title : String,
Si es la pregunta que te he hecho por telegram por eso no había puesto el id, lo introduciré aunque no dire como se calcula hasta que sea el momento

2023-10-24 09:57 UTC, JoseJordanF commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
Hay una idea equivocada, las recomendaciones no se harán a través de las reseñas, sino a través de las películas en las que tú escribas reseñas

2023-10-24 09:59 UTC, JoseJordanF commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
Por lo mencionado arriba, son dos listas diferentes, por eso hay dos asociaciones diferentes

2023-10-24 10:00 UTC, JJ commented on domain/Film.kt
> +    val title : String,
Si no quieres comprometerte con una implementación u otra, declara un interfaz para los IDs que vayas a usar y listo. REcuerda en en programación lo que hay que hacer es desacoplar el interfaz de la implementación.

2023-10-24 10:02 UTC, JJ commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
A través de qué se hagan es un poco irrelevante. Lo que tienes que hacer es modelizar bien cada reseña, y decidir quién gestiona la asociación entre reseña, usuario y película. Si esas asociaciones son inmutables, quizás deberían ser parte del propio objeto en vez de tener una entidad externa que las gestione. Si creas una entidad externa lo que vienes a decir es "Esta entidad decide, en un momento determinado, a qué peli y a qué usuario corresponde una reseña"

2023-10-24 10:03 UTC, JoseJordanF commented on domain/Film.kt
> +    val title : String,
No si no es problema ya tengo el código de snowflake para generar los IDs

2023-10-24 10:03 UTC, JJ commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
Volvemos a lo mismo, tienes que plantear un poco mejor los issues y los problemas que se plantean y desarrollar el código con respecto a ello.
En todo caso, lo que hay aquí, que sería el modelo que se ve, no aparenta lo que dices. Son listas de "REview", y las review son el objeto completo, no referencias al objeto. Lo que viene a indicar eso es que el modelo que tienes de Review no está muy claro. Quizás #66 deberías aclararlo un poco más, añadiendo todo lo que sabes de una review por tu conocimiento del tema.

2023-10-24 10:07 UTC, JJ commented on domain/Film.kt
> +    val title : String,
Insisto, es un detalle de implementación. En esta fase, que es la del modelo, lo que tienes que hacer es atender a los interfaces y tipos, para luego incluir la implementación que sea más conveniente.

2023-10-24 10:09 UTC, JoseJordanF commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
Es algo que me temia, la review debe tener un ID unico que la identifique para estar bien definida. De este modo, en las entidades que gestionan las listas de reviews solo tendrían una referencia a esas reviews.

2023-10-24 10:10 UTC, JoseJordanF commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
Claro, eso es lo que intento decir con cada asociación. Podría haber creado una sola entidad que gestionara las dos asociaciones con dos listas.

2023-10-24 10:12 UTC, JJ commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
Solo si permites más de una review por peli y usuario. Si no, la combinación de estos dos va a ser única.

2023-10-24 10:13 UTC, JJ commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
Insisto, una entidad gestiona esas asociaciones. Lo que estás implicando con el uso de la entidad es que cuando se crea un review no se sabe ni de qué usuario ni de qué película se trata, sino que debe haber una entidad que lo asigne (y que pueda cambiar esa asociación en un momento determinado)

2023-10-24 10:17 UTC, JoseJordanF commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
Solo se permite una reseña por usuario en cada peli.

2023-10-24 10:19 UTC, JoseJordanF commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
Claro, pero no entiendo que problema hay en eso

2023-10-24 10:26 UTC, JJ commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
Deberías poner esa restricción en el issue, entonces. Y el modelo garantizarlo.

2023-10-24 10:28 UTC, JJ commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
Si la asociación peli-reseñador-reseña es inmutable, el modelo debe garantizarlo. Hay muchas formas de hacerlo, pero una de ellas es simplemente que la reseña incluya peli y reseñador y que sea inmutable.

2023-10-24 10:31 UTC, JoseJordanF commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
Vamos que cada reseña haga referencia a un id que identifique la peli y a un id que identifique al usuario, en este caso el usuario ya esta ya que se guardaria el email como autor de la reseña.

2023-10-24 10:36 UTC, JJ commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
id u objeto. Una vez más, es cuestión de desacoplar lo que necesitas (un ID único) de cómo lo vayas a implementar (snowflake, long int, nick de usuario, lo que sea...)
Y no digas lo que se guardaría o no. Son decisiones de implementación. Si no están en la HU, tienes que usar la solución más simple, que sería posiblemente un nick y listo.
Si usas el correo electrónico es información personal, y #1 evaluará tu conocimiento de la legislación e implicaciones legales... Lo que implica que *tienes que incluir en la arquitectura los derechos a los que asista esa persona por la LOPD*.

2023-10-24 18:05 UTC, JJ requested changes
El principal problema, y perdona por no haber caído antes, es implementar un workflow con un linter y fusionarlo antes qeu este PR. En cuanto que se incluye algún código se debe incluir una comprobación automática de calidad de código, aunque sea a nivel mínimo de comprobación de buenas prácticas.

2023-10-24 18:05 UTC, JJ commented on domain/Film.kt
> +    val title : String,
Si esto está solucionado, resuelve comentando el commit donde se ha hecho.

2023-10-24 18:05 UTC, JJ commented on domain/Review.kt
> +import java.util.*
Creo que no es una buena práctica importar todos los objetos de un espacio de nombres. Quizás sería conveniente, antes de que fusiones esto, que incluyas `ktlint` para linting. Supongo que tienes ya configurado Android Studio para que te haga el linting sobre la marcha, pero aún así, es conveniente que lo ejecutes automáticamente, sobre todo para posibles PRs.

2023-10-25 06:38 UTC, JoseJordanF commented on domain/Film.kt
> +    val title : String,
(8ab0f1dd9e1002a3b8b7214bac85cadb66601883)

2023-10-25 06:38 UTC, JoseJordanF commented on domain/LinkUserReviews.kt
> +    val links : MutableMap<String, List<Review>> = mutableMapOf()
(8ab0f1dd9e1002a3b8b7214bac85cadb66601883)

2023-10-25 06:39 UTC, JoseJordanF commented on domain/LinkFilmReviews.kt
> +    val links : MutableMap<Long, List<Review>> = mutableMapOf()
(8ab0f1dd9e1002a3b8b7214bac85cadb66601883)

2023-10-25 06:39 UTC, JoseJordanF commented on domain/Review.kt
> +    val containSpoiler: Boolean,
(b00643a722160d1ad59e788442033482e6b2fb5a)

2023-10-25 06:40 UTC, JoseJordanF commented on domain/Review.kt
> +    val howUseful : Double
(b00643a722160d1ad59e788442033482e6b2fb5a)

2023-10-25 06:40 UTC, JoseJordanF commented on domain/Film.kt
> +    val duration : Int = 0,
(b00643a722160d1ad59e788442033482e6b2fb5a)

2023-10-25 06:43 UTC, JoseJordanF commented on domain/Film.kt
> +    val movieDirector : String,
(d2274c9f169cff18eb54b970f19cc7b63a040ee9)

2023-10-25 06:44 UTC, JoseJordanF commented on domain/Film.kt
> +    val description: String,
(d2274c9f169cff18eb54b970f19cc7b63a040ee9)

2023-10-25 07:26 UTC, JoseJordanF commented on domain/Review.kt
> +import java.util.*
(530ce89b78cade7c2824db5dc333541e18575b86)

2023-10-25 10:02 UTC, JJ requested changes
El principal problema que bloquea esto es que issues como #70, que has usado para desarrollar código, no están enlazados a ninguna historia de usuario.
Hay problemas adicionales. No está claro que gestionar cada tipo de objeto con su propia entidad sea una alternativa a gestionarlos todos en una sola entidad, por ejemplo. No bloquea, pero deberías considerarlo. No está claro cómo se gestionan los IDs en el caso que la entidad los gestione.
Pero también es un problema que no se haya fusionado el comprobador automático de calidad de código. Quizás deberías crear, como te he dicho, ese PR y fusionarlo antes de que volvamos a este.

2023-10-25 16:14 UTC, JoseJordanF commented on domain/ManagerFilms.kt
> +    val films:  MutableMap<Long, Film> = mutableMapOf()
¿Te refieres a como se crean? y luego no se a que te refieres con "No bloquea, pero deberías considerarlo"

2023-10-25 16:21 UTC, JJ commented on domain/ManagerFilms.kt
> +    val films:  MutableMap<Long, Film> = mutableMapOf()
No, cuál es el modelo. Este milestone incluye el modelo de todo, incluyendo las IDs, por lo que si Long son IDs, tendrás que incluir en el modelo cómo generarlos. Una vez más, considera la posibilidad de usar o interfaces u otro mecanismo que especifique esto claramente en el modelo, si no del código sólo no está claro.

2023-10-25 17:09 UTC, JoseJordanF commented on domain/ManagerFilms.kt
> +    val films:  MutableMap<Long, Film> = mutableMapOf()
Okay

2023-10-25 18:16 UTC, JoseJordanF commented on domain/ManagerFilms.kt
> +    val films:  MutableMap<Long, Film> = mutableMapOf()
(28a26f358ad267387e8521bd3a5a20dca3885290)

2023-10-30 09:59 UTC, JJ commented
¿No has fusionado con esta rama la que incluye el linter?
Si no lo haces, es posible que te dé algún error cuando lo fusiones

2023-10-30 10:00 UTC, JoseJordanF commented
Estaba esperando que me dieras el visto bueno al codigo

2023-10-30 10:01 UTC, JJ requested changes
Tienes que tratar siempre de buscar el código mínimo que cumpla una condición.

2023-10-30 10:01 UTC, JJ commented on domain/valueObjects/User.kt
> +data class User(
¿Has considerado en este caso simplemente no usar una clase? Si es un username, y es la entidad que lo maneje la que lo va a comprobar si es único, ¿hace falta esta clase en este momento?

2023-10-30 10:02 UTC, JJ commented
> Estaba esperando que me dieras el visto bueno al codigo

Antes de dar el visto bueno hay que saber si sigue las mejore prácticas y para eso está el linter. Como ya está fusionado a main, no tienes más que fusionar main en esta rama para que lo pase.

2023-10-30 10:02 UTC, JoseJordanF commented on domain/valueObjects/User.kt
> +data class User(
La verdad que no porque para guardar solo un string no merece la pena

2023-10-30 10:03 UTC, JoseJordanF commented
Entonces hago un merge desde esta rama a la main ?

2023-10-30 19:15 UTC, JoseJordanF commented
POR FIN

2023-10-30 19:15 UTC, JJ commented
Eso es un comentario sentío.

2023-10-30 19:16 UTC, JJ approved these changes
:clap: salvo el tema de los nombres, dale una pequeña vuelta.

2023-10-30 19:17 UTC, JoseJordanF commented on domain/Manager.kt
> +data class Manager(
Claro como lo maneja todo, ManagerFilmsUsersReviews

2023-10-30 19:22 UTC, JoseJordanF commented on domain/Manager.kt
> +data class Manager(
(f50ed6811c9a9f6f466380239314a3919d06a397)

2023-10-31 09:17 UTC, merged